import { definePack, p, universe, w } from './types';

export default definePack({
  id: 'animaux',
  name: 'Animaux',
  description: 'De la savane aux océans : bêtes à plumes, à poils et à écailles.',
  icon: 'paw-print',
  universes: [
    universe({
      id: 'general',
      name: 'Animaux',
      precise: false,
      words: {
        // Mammifères terrestres
        lion: w('Lion', 'Fauve des savanes africaines vivant en troupe, dont le mâle porte une crinière.'),
        tigre: w('Tigre', 'Grand fauve d’Asie au pelage orangé rayé de noir, excellent nageur.'),
        guepard: w('Guépard', 'Félin élancé au pelage tacheté, animal terrestre le plus rapide du monde.'),
        leopard: w('Léopard', 'Félin puissant à taches en rosettes, qui hisse ses proies dans les arbres.'),
        chat: w('Chat', 'Petit félin domestique qui ronronne, miaule et retombe souvent sur ses pattes.'),
        lapin: w('Lapin', 'Petit mammifère aux longues oreilles, élevé à la ferme ou adopté en appartement.'),
        chien: w('Chien', 'Animal domestique fidèle qui aboie, dressé pour la garde, la chasse ou la compagnie.'),
        loup: w('Loup', 'Canidé sauvage vivant en meute, connu pour ses hurlements, revenu dans les Alpes.'),
        renard: w('Renard', 'Petit canidé roux à queue touffue, réputé rusé dans les fables.'),
        ours: w('Ours', 'Grand mammifère massif et omnivore, qui hiberne l’hiver et raffole du miel.'),
        panda: w('Panda', 'Mammifère noir et blanc des montagnes de Chine, qui se nourrit de bambou.'),
        koala: w('Koala', 'Marsupial grimpeur d’Australie qui dort beaucoup et mange des feuilles d’eucalyptus.'),
        vache: w('Vache', 'Ruminant de ferme élevé pour son lait et sa viande, qui meugle dans les prés.'),
        chevre: w('Chèvre', 'Ruminant à cornes et à barbichette, agile grimpeur, élevé pour son lait.'),
        mouton: w('Mouton', 'Ruminant de ferme élevé pour sa laine et sa viande, qui bêle en troupeau.'),
        lama: w('Lama', 'Animal des Andes au long cou, porteur de charges, réputé pour cracher.'),
        dromadaire: w('Dromadaire', 'Mammifère à une bosse d’Afrique du Nord et d’Arabie, surnommé vaisseau du désert.'),
        ane: w('Âne', 'Équidé aux longues oreilles, réputé têtu, qui brait et porte des charges.'),
        cheval: w('Cheval', 'Grand équidé domestique qu’on monte, qui galope et hennit.'),
        zebre: w('Zèbre', 'Équidé africain au pelage rayé noir et blanc, vivant en troupeau.'),
        girafe: w('Girafe', 'Mammifère africain au très long cou, le plus haut des animaux terrestres.'),
        cochon: w('Cochon', 'Animal de ferme rose au groin, qui se roule dans la boue.'),
        sanglier: w('Sanglier', 'Mammifère sauvage des forêts au groin puissant et aux défenses, gibier de chasse.'),
        elephant: w('Éléphant', 'Plus grand animal terrestre, doté d’une trompe et de défenses en ivoire.'),
        rhinoceros: w('Rhinocéros', 'Gros herbivore à peau épaisse, portant une ou deux cornes sur le nez.'),
        hippopotame: w('Hippopotame', 'Énorme herbivore africain qui passe ses journées dans l’eau des fleuves et des lacs.'),
        ecureuil: w('Écureuil', 'Petit rongeur roux à queue en panache, qui vit dans les arbres.'),
        marmotte: w('Marmotte', 'Rongeur des montagnes qui siffle pour alerter et hiberne longuement.'),

        // Oiseaux
        poule: w('Poule', 'Oiseau de basse-cour qui caquette, gratte le sol et pond des œufs.'),
        dinde: w('Dinde', 'Grosse volaille originaire d’Amérique, traditionnellement farcie à Noël.'),
        canard: w('Canard', 'Oiseau aux pattes palmées qui barbote dans les mares et cancane.'),
        paon: w('Paon', 'Oiseau qui déploie en roue une traîne ornée d’ocelles bleus et verts.'),
        cygne: w('Cygne', 'Grand oiseau aquatique au long cou courbé, généralement blanc, symbole d’élégance.'),
        flamant: w('Flamant rose', 'Échassier des lagunes qui dort sur une patte, coloré par sa nourriture.'),
        aigle: w('Aigle', 'Grand rapace aux serres puissantes, qui niche souvent en montagne.'),
        vautour: w('Vautour', 'Grand rapace au cou déplumé qui se nourrit de charognes.'),
        hibou: w('Hibou', 'Rapace nocturne reconnaissable aux aigrettes de plumes sur sa tête.'),
        'chauve-souris': w('Chauve-souris', 'Mammifère volant nocturne qui se repère par écholocation et dort la tête en bas.'),
        perroquet: w('Perroquet', 'Oiseau tropical coloré au bec crochu, capable d’imiter la voix.'),
        toucan: w('Toucan', 'Oiseau tropical d’Amérique au bec énorme et coloré.'),

        // Reptiles, amphibiens et petites bêtes
        crocodile: w('Crocodile', 'Grand reptile aux mâchoires puissantes, qui guette ses proies à fleur d’eau.'),
        serpent: w('Serpent', 'Reptile sans pattes qui rampe et change de peau, parfois venimeux.'),
        lezard: w('Lézard', 'Petit reptile à quatre pattes et longue queue, qui se chauffe au soleil sur les murs.'),
        grenouille: w('Grenouille', 'Amphibien à peau lisse et humide, bon sauteur, qui coasse près des mares.'),
        tortue: w('Tortue', 'Reptile lent protégé par une carapace dans laquelle il rentre la tête.'),
        escargot: w('Escargot', 'Mollusque qui porte une coquille en spirale et laisse une trace de bave.'),
        abeille: w('Abeille', 'Insecte butineur qui produit le miel et vit en colonie autour d’une reine.'),
        bourdon: w('Bourdon', 'Insecte velu et trapu qui butine les fleurs en vrombissant bruyamment.'),
        guepe: w('Guêpe', 'Insecte rayé jaune et noir à taille fine, attiré par le sucre en été.'),
        fourmi: w('Fourmi', 'Petit insecte social qui vit en fourmilière et transporte des charges énormes.'),
        moustique: w('Moustique', 'Insecte dont la femelle pique pour se nourrir de sang, surtout le soir.'),
        mouche: w('Mouche', 'Insecte bourdonnant qui se pose sur la nourriture et les déchets.'),
        papillon: w('Papillon', 'Insecte aux ailes colorées couvertes d’écailles, issu d’une chenille.'),
        libellule: w('Libellule', 'Insecte aux ailes transparentes et au long abdomen, qui chasse près de l’eau.'),

        // Animaux aquatiques
        dauphin: w('Dauphin', 'Mammifère marin joueur et intelligent, qui se repère par écholocation.'),
        orque: w('Orque', 'Mammifère marin noir et blanc, grand chasseur vivant en groupe familial.'),
        requin: w('Requin', 'Poisson prédateur au squelette cartilagineux et aux rangées de dents.'),
        phoque: w('Phoque', 'Mammifère marin au corps fuselé, qui se déplace à terre en rampant sur le ventre.'),
        loutre: w('Loutre', 'Mammifère aquatique joueur au pelage dense, qui pêche des poissons.'),
        castor: w('Castor', 'Rongeur aquatique à queue plate qui construit des barrages.'),
        manchot: w('Manchot', 'Oiseau nageur de l’hémisphère Sud, aux ailes en nageoires, vivant en colonies.'),
        pieuvre: w('Pieuvre', 'Mollusque marin à huit bras munis de ventouses, qui crache de l’encre.'),
        meduse: w('Méduse', 'Animal marin gélatineux et translucide, aux filaments urticants.'),
        crabe: w('Crabe', 'Crustacé à large carapace et à pinces, qui se déplace de côté sur les plages.'),
        homard: w('Homard', 'Crustacé marin à grosses pinces, bleu vivant et rouge une fois cuit.'),
      },
      pairs: [
        p('lion', 'guepard', 'Animaux de la savane'),
        p('guepard', 'leopard', 'Animaux sauvages'),
        p('leopard', 'tigre', 'Prédateurs'),
        p('chat', 'lapin', 'Animaux de compagnie'),
        p('chien', 'loup', 'Mammifères'),
        p('loup', 'renard', 'Animaux de la forêt'),
        p('loup', 'ours', 'Prédateurs'),
        p('ours', 'panda', 'Mammifères'),
        p('panda', 'koala', 'Animaux mignons'),
        p('vache', 'chevre', 'Animaux de la ferme'),
        p('mouton', 'lama', 'Animaux d’élevage'),
        p('lama', 'dromadaire', 'Animaux du bout du monde'),
        p('dromadaire', 'ane', 'Animaux qu’on monte'),
        p('cheval', 'zebre', 'Mammifères'),
        p('zebre', 'girafe', 'Animaux d’Afrique'),
        p('cochon', 'sanglier', 'Animaux de la campagne'),
        p('elephant', 'rhinoceros', 'Animaux de la savane'),
        p('rhinoceros', 'hippopotame', 'Animaux d’Afrique'),
        p('hippopotame', 'crocodile', 'Animaux d’Afrique'),
        p('ecureuil', 'marmotte', 'Animaux de montagne et de forêt'),

        p('poule', 'dinde', 'Animaux de la ferme'),
        p('poule', 'canard', 'Animaux de la ferme'),
        p('dinde', 'paon', 'Oiseaux'),
        p('canard', 'cygne', 'Animaux des lacs et rivières'),
        p('cygne', 'flamant', 'Oiseaux'),
        p('aigle', 'vautour', 'Oiseaux'),
        p('hibou', 'chauve-souris', 'Animaux de la nuit'),
        p('perroquet', 'toucan', 'Animaux de la jungle'),

        p('serpent', 'lezard', 'Animaux à écailles'),
        p('lezard', 'crocodile', 'Animaux à écailles'),
        p('lezard', 'grenouille', 'Petites bêtes du jardin'),
        p('tortue', 'escargot', 'Petites bêtes du jardin'),
        p('abeille', 'bourdon', 'Insectes'),
        p('bourdon', 'guepe', 'Insectes'),
        p('abeille', 'fourmi', 'Petites bêtes'),
        p('moustique', 'mouche', 'Insectes'),
        p('papillon', 'libellule', 'Insectes'),

        p('dauphin', 'orque', 'Animaux marins'),
        p('orque', 'requin', 'Prédateurs'),
        p('phoque', 'loutre', 'Animaux aquatiques'),
        p('loutre', 'castor', 'Animaux des lacs et rivières'),
        p('phoque', 'manchot', 'Animaux des pays froids'),
        p('pieuvre', 'meduse', 'Animaux marins'),
        p('crabe', 'homard', 'Fruits de mer'),
      ],
    }),
  ],
});
