import { definePack, p, universe, w } from './types';

export default definePack({
  id: 'anime-manga',
  name: 'Anime & Manga',
  description: 'Héros de shōnen, films cultes et rivalités légendaires.',
  icon: 'swords',
  universes: [
    universe({
      id: 'general',
      name: 'Anime & Manga',
      precise: false,
      words: {
        // Œuvres
        'one-piece': w('One Piece', 'Manga d’Eiichirō Oda sur un équipage de pirates en quête d’un trésor légendaire.'),
        'fairy-tail': w('Fairy Tail', 'Manga de Hiro Mashima qui suit une guilde de mages et leurs missions.'),
        'hunter-x-hunter': w('Hunter x Hunter', 'Manga de Yoshihiro Togashi où un garçon part sur les traces de son père.'),
        'dragon-ball': w('Dragon Ball', 'Manga d’Akira Toriyama où des combattants cherchent sept boules magiques.'),
        chevaliers: w('Les Chevaliers du Zodiaque', 'Manga de Masami Kurumada où des guerriers en armure protègent la déesse Athéna.'),
        ken: w('Ken le Survivant', 'Manga post-apocalyptique où un maître d’arts martiaux frappe les points vitaux.'),
        bleach: w('Bleach', 'Manga de Tite Kubo où un lycéen qui voit les fantômes devient faucheur d’âmes.'),
        'jujutsu-kaisen': w('Jujutsu Kaisen', 'Manga où un lycéen avale un doigt maudit et rejoint une école d’exorcistes.'),
        'demon-slayer': w('Demon Slayer', 'Manga où un jeune garçon traque des démons pour guérir sa sœur transformée.'),
        'chainsaw-man': w('Chainsaw Man', 'Manga où un jeune endetté fusionne avec un démon et se change en homme-tronçonneuse.'),
        'attaque-titans': w('L’Attaque des Titans', 'Manga où l’humanité survit derrière d’immenses murs face à des géants dévoreurs.'),
        'tokyo-ghoul': w('Tokyo Ghoul', 'Manga où un étudiant devient mi-humain, mi-goule après une greffe d’organes.'),
        'death-note': w('Death Note', 'Manga où un lycéen trouve un cahier qui tue quiconque y est nommé.'),
        'code-geass': w('Code Geass', 'Anime où un prince exilé obtient le pouvoir d’imposer sa volonté par le regard.'),
        'my-hero-academia': w('My Hero Academia', 'Manga où des lycéens dotés de super-pouvoirs étudient pour devenir héros professionnels.'),
        'one-punch-man': w('One Punch Man', 'Manga parodique dont le héros chauve bat n’importe quel ennemi d’un seul coup.'),
        'black-clover': w('Black Clover', 'Manga où un orphelin né sans magie rêve de devenir l’empereur-mage de son royaume.'),
        pokemon: w('Pokémon', 'Franchise japonaise où des dresseurs capturent des créatures et les font combattre.'),
        'yu-gi-oh': w('Yu-Gi-Oh!', 'Manga et jeu de cartes où des duellistes invoquent des monstres pour s’affronter.'),
        digimon: w('Digimon', 'Franchise japonaise de monstres numériques vivant dans un monde informatique.'),
        chihiro: w('Le Voyage de Chihiro', 'Film de Hayao Miyazaki où une fillette travaille dans des bains fréquentés par des esprits.'),
        mononoke: w('Princesse Mononoké', 'Film de Hayao Miyazaki où un jeune prince maudit croise une fille élevée par des loups.'),
        'chateau-ambulant': w('Le Château ambulant', 'Film de Hayao Miyazaki où une jeune fille changée en vieille dame rejoint un magicien.'),
        'sailor-moon': w('Sailor Moon', 'Collégienne qui se transforme en guerrière de l’amour et de la justice, guidée par un chat.'),
        sakura: w('Sakura, chasseuse de cartes', 'Écolière qui doit retrouver des cartes magiques échappées d’un livre enchanté.'),
        'olive-et-tom': w('Olive et Tom', 'Anime où un jeune prodige du ballon rond rêve de gagner la Coupe du monde.'),
        'inazuma-eleven': w('Inazuma Eleven', 'Jeux vidéo et anime où des collégiens jouent au foot avec des tirs spéciaux.'),
        'blue-lock': w('Blue Lock', 'Manga où des attaquants s’affrontent dans un centre fermé pour former le meilleur buteur.'),
        'slam-dunk': w('Slam Dunk', 'Manga de Takehiko Inoue où un voyou roux rejoint une équipe pour plaire à une fille.'),
        kuroko: w('Kuroko’s Basket', 'Manga où un joueur presque invisible sur le terrain excelle dans l’art de la passe.'),
        haikyuu: w('Haikyuu!!', 'Manga où un lycéen de petite taille se passionne pour le volley-ball.'),
        'nicky-larson': w('Nicky Larson', 'Nettoyeur de Tokyo, tireur d’élite hors pair et dragueur invétéré.'),
        cobra: w('Cobra', 'Pirate de l’espace qui cache une arme redoutable dans son bras gauche.'),
        albator: w('Albator', 'Capitaine pirate balafré qui sillonne l’espace à bord de son vaisseau, l’Arcadia.'),
        doraemon: w('Doraemon', 'Chat-robot bleu venu du futur, qui sort des gadgets de sa poche magique.'),
        'shin-chan': w('Shin-chan', 'Petit garçon de cinq ans espiègle et insolent, célèbre pour ses bêtises.'),
        'solo-leveling': w('Solo Leveling', 'Webtoon coréen où le plus faible des chasseurs de monstres devient surpuissant.'),
        'sword-art-online': w('Sword Art Online', 'Light novel où des joueurs restent piégés dans un jeu en réalité virtuelle.'),

        // Personnages, créatures et techniques
        goku: w('Goku', 'Guerrier au cœur pur élevé sur Terre, toujours en quête d’adversaires à sa mesure.'),
        luffy: w('Luffy', 'Capitaine pirate au chapeau de paille dont le corps s’étire comme du caoutchouc.'),
        naruto: w('Naruto', 'Jeune ninja blond et bruyant qui rêve de devenir le chef de son village.'),
        deku: w('Deku', 'Garçon aux cheveux verts né sans pouvoir, qui hérite d’un pouvoir surpuissant.'),
        tanjiro: w('Tanjirō', 'Jeune épéiste au grand cœur, doté d’un odorat exceptionnel, qui traque les démons.'),
        eren: w('Eren', 'Jeune soldat impulsif qui a juré d’exterminer les géants après la mort de sa mère.'),
        mikasa: w('Mikasa', 'Jeune soldate aux cheveux noirs, redoutable au combat et fidèle à son ami d’enfance.'),
        nezuko: w('Nezuko', 'Jeune fille changée en démon, qui porte un bâillon de bambou.'),
        kakashi: w('Kakashi', 'Ninja aux cheveux argentés, le bas du visage masqué, qui encadre de jeunes élèves.'),
        gojo: w('Gojo', 'Exorciste aux cheveux blancs, les yeux bandés, réputé le plus puissant de son époque.'),
        sukuna: w('Sukuna', 'Roi des fléaux aux quatre bras et quatre yeux, dont les doigts maudits sont dispersés.'),
        muzan: w('Muzan', 'Premier des démons, capable de changer les humains en démons avec son sang.'),
        pikachu: w('Pikachu', 'Petite souris jaune qui produit de l’électricité avec ses joues.'),
        rondoudou: w('Rondoudou', 'Créature rose et ronde dont la chanson endort ceux qui l’écoutent.'),
        totoro: w('Totoro', 'Grand esprit de la forêt, gris et poilu, qui se lie d’amitié avec deux fillettes.'),
        ponyo: w('Ponyo', 'Petit poisson rouge magique qui rêve de devenir une petite fille.'),
        kamehameha: w('Kamehameha', 'Rayon d’énergie lancé à deux mains, enseigné par un vieux maître des arts martiaux.'),
        rasengan: w('Rasengan', 'Sphère d’énergie tourbillonnante formée dans la paume et plaquée sur l’adversaire.'),

        // Vocabulaire et culture
        manga: w('Manga', 'Bande dessinée japonaise, lue traditionnellement de droite à gauche.'),
        manhwa: w('Manhwa', 'Bande dessinée coréenne, souvent en couleur et lue en défilement vertical.'),
        shonen: w('Shōnen', 'Catégorie de mangas destinée aux jeunes garçons, centrée sur l’action et l’amitié.'),
        seinen: w('Seinen', 'Catégorie de mangas destinée aux jeunes adultes, aux récits souvent sombres.'),
        shojo: w('Shōjo', 'Catégorie de mangas destinée aux jeunes filles, souvent centrée sur les sentiments.'),
        opening: w('Opening', 'Générique de début d’un anime, souvent une chanson pop ou rock entraînante.'),
        ending: w('Ending', 'Générique de fin d’un anime, souvent accompagné d’une chanson calme.'),
        senpai: w('Senpai', 'Terme japonais désignant un aîné ou un camarade expérimenté, à l’école ou au travail.'),
        sensei: w('Sensei', 'Terme japonais désignant un professeur, un médecin ou un maître respecté.'),
      },
      pairs: [
        p('one-piece', 'fairy-tail', 'Mangas d’aventure'),
        p('one-piece', 'hunter-x-hunter', 'Mangas d’aventure'),
        p('dragon-ball', 'chevaliers', 'Classiques du Club Dorothée'),
        p('chevaliers', 'ken', 'Mangas de combat'),
        p('bleach', 'jujutsu-kaisen', 'Mangas surnaturels'),
        p('jujutsu-kaisen', 'demon-slayer', 'Mangas d’action récents'),
        p('jujutsu-kaisen', 'chainsaw-man', 'Mangas d’action récents'),
        p('demon-slayer', 'attaque-titans', 'Mangas d’action'),
        p('attaque-titans', 'tokyo-ghoul', 'Mangas sombres'),
        p('death-note', 'code-geass', 'Anime à suspense'),
        p('my-hero-academia', 'one-punch-man', 'Mangas d’action'),
        p('my-hero-academia', 'black-clover', 'Mangas d’action'),
        p('pokemon', 'yu-gi-oh', 'Franchises japonaises'),
        p('pokemon', 'digimon', 'Franchises japonaises'),
        p('chihiro', 'mononoke', 'Films d’animation'),
        p('chihiro', 'chateau-ambulant', 'Films d’animation'),
        p('sailor-moon', 'sakura', 'Anime des années 90'),
        p('olive-et-tom', 'inazuma-eleven', 'Sport en animation'),
        p('olive-et-tom', 'blue-lock', 'Sport en animation'),
        p('slam-dunk', 'kuroko', 'Mangas de sport'),
        p('kuroko', 'haikyuu', 'Mangas de sport'),
        p('nicky-larson', 'cobra', 'Héros d’anime rétro'),
        p('cobra', 'albator', 'Héros d’anime rétro'),
        p('doraemon', 'shin-chan', 'Anime pour enfants'),
        p('solo-leveling', 'sword-art-online', 'Aventures façon jeu vidéo'),
        p('goku', 'luffy', 'Héros de shōnen'),
        p('luffy', 'naruto', 'Héros de shōnen'),
        p('naruto', 'deku', 'Héros de shōnen'),
        p('deku', 'tanjiro', 'Héros de shōnen'),
        p('tanjiro', 'eren', 'Héros de manga'),
        p('mikasa', 'nezuko', 'Héroïnes de manga'),
        p('kakashi', 'gojo', 'Personnages de manga'),
        p('sukuna', 'muzan', 'Méchants de manga'),
        p('pikachu', 'rondoudou', 'Créatures et mascottes'),
        p('pikachu', 'totoro', 'Créatures et mascottes'),
        p('totoro', 'ponyo', 'Personnages de films d’animation'),
        p('kamehameha', 'rasengan', 'Techniques de combat'),
        p('manga', 'manhwa', 'Lecture et édition'),
        p('shonen', 'seinen', 'Vocabulaire des fans'),
        p('shonen', 'shojo', 'Vocabulaire des fans'),
        p('opening', 'ending', 'Vocabulaire des fans'),
        p('senpai', 'sensei', 'Culture japonaise'),
      ],
    }),

    universe({
      id: 'one-piece',
      name: 'One Piece',
      precise: true,
      words: {
        luffy: w('Luffy', 'Capitaine au chapeau de paille dont le corps s’étire comme du caoutchouc.'),
        ace: w('Ace', 'Commandant pirate torse nu au chapeau orange, capable de se changer en flammes.'),
        sabo: w('Sabo', 'Révolutionnaire au haut-de-forme, longtemps cru mort après une attaque subie enfant.'),
        law: w('Trafalgar Law', 'Chirurgien pirate au bonnet tacheté, qui découpe et déplace tout dans sa sphère.'),
        zoro: w('Zoro', 'Épéiste aux cheveux verts qui combat avec trois sabres et se perd sans cesse.'),
        sanji: w('Sanji', 'Cuisinier blond au sourcil en spirale, qui se bat uniquement avec ses jambes.'),
        nami: w('Nami', 'Navigatrice rousse passionnée de cartes marines et très attachée à l’argent.'),
        robin: w('Robin', 'Archéologue brune capable de faire pousser des bras sur n’importe quelle surface.'),
        usopp: w('Usopp', 'Tireur d’élite au long nez, grand menteur et inventeur de munitions farfelues.'),
        chopper: w('Chopper', 'Renne doué de la parole, médecin de l’équipage, coiffé d’un chapeau rose.'),
        shanks: w('Shanks', 'Pirate roux et balafré, qui a perdu un bras pour sauver un jeune garçon.'),
        kaido: w('Kaido', 'Pirate colossal à cornes, réputé invincible, capable de se changer en dragon.'),
        'big-mom': w('Big Mom', 'Pirate géante et gourmande, mère d’une immense famille et reine d’un archipel.'),
        doflamingo: w('Doflamingo', 'Pirate à lunettes et manteau de plumes roses, qui manipule les gens avec des fils.'),
        crocodile: w('Crocodile', 'Pirate au crochet en or et au cigare, capable de se changer en sable.'),
        akainu: w('Akainu', 'Amiral impitoyable qui se change en magma, devenu amiral en chef de la Marine.'),
        aokiji: w('Aokiji', 'Amiral nonchalant capable de tout geler, qui finit par quitter la Marine.'),
        mera: w('Mera Mera no Mi', 'Fruit du démon qui permet de produire des flammes et de se changer en feu.'),
        magu: w('Magu Magu no Mi', 'Fruit du démon qui permet de produire de la lave et de se changer en magma.'),
        'haki-armement': w('Haki de l’armement', 'Volonté qui durcit le corps ou une arme, souvent visible sous forme de noirceur.'),
        'haki-observation': w('Haki de l’observation', 'Volonté qui permet de percevoir les présences et d’anticiper les attaques.'),
        alabasta: w('Alabasta', 'Royaume du désert menacé par une rébellion orchestrée en secret.'),
        dressrosa: w('Dressrosa', 'Royaume de l’amour et des jouets vivants, dominé par un roi pirate.'),
        wano: w('Wano', 'Pays de samouraïs fermé au monde, gouverné par un shogun tyrannique.'),
        'thousand-sunny': w('Thousand Sunny', 'Navire à tête de lion, construit par un charpentier cyborg pour l’équipage.'),
        'vogue-merry': w('Vogue Merry', 'Caravelle à tête de mouton, premier vrai navire de l’équipage.'),
      },
      pairs: [
        p('luffy', 'ace', 'Personnages'),
        p('luffy', 'law', 'Capitaines et pirates'),
        p('ace', 'sabo', 'Personnages'),
        p('zoro', 'sanji', 'Membres d’équipage'),
        p('zoro', 'law', 'Combattants'),
        p('nami', 'robin', 'Membres d’équipage'),
        p('nami', 'usopp', 'Membres d’équipage'),
        p('usopp', 'chopper', 'Membres d’équipage'),
        p('shanks', 'kaido', 'Capitaines et pirates'),
        p('kaido', 'big-mom', 'Capitaines et pirates'),
        p('doflamingo', 'crocodile', 'Adversaires'),
        p('akainu', 'aokiji', 'Personnages'),
        p('mera', 'magu', 'Pouvoirs'),
        p('haki-armement', 'haki-observation', 'Pouvoirs et combat'),
        p('alabasta', 'dressrosa', 'Lieux'),
        p('dressrosa', 'wano', 'Lieux'),
        p('thousand-sunny', 'vogue-merry', 'Objets et véhicules'),
      ],
    }),

    universe({
      id: 'naruto',
      name: 'Naruto',
      precise: true,
      words: {
        naruto: w('Naruto', 'Jeune ninja blond et bruyant qui rêve de devenir le chef de son village.'),
        gaara: w('Gaara', 'Ninja du désert aux cheveux roux, qui manipule le sable et porte une gourde.'),
        'rock-lee': w('Rock Lee', 'Ninja en combinaison verte, incapable de ninjutsu, qui mise tout sur le taijutsu.'),
        neji: w('Neji', 'Prodige aux yeux blancs, persuadé que le destin de chacun est écrit d’avance.'),
        sasuke: w('Sasuke', 'Ninja taciturne aux cheveux noirs, en quête de vengeance après le massacre de son clan.'),
        itachi: w('Itachi', 'Ninja prodige qui a décimé son propre clan avant de rejoindre l’Akatsuki.'),
        obito: w('Obito', 'Ninja longtemps cru mort, caché derrière un masque orange en spirale.'),
        pain: w('Pain', 'Chef de l’Akatsuki au visage couvert de piercings, qui contrôle six corps à distance.'),
        kakashi: w('Kakashi', 'Ninja aux cheveux argentés, le bas du visage masqué, qui encadre de jeunes élèves.'),
        jiraiya: w('Jiraiya', 'Ermite des crapauds, auteur de romans coquins et maître de plusieurs ninjas célèbres.'),
        tsunade: w('Tsunade', 'Ninja médecin à la force colossale, joueuse invétérée et petite-fille du premier Hokage.'),
        sakura: w('Sakura', 'Ninja aux cheveux roses, experte en soins médicaux et dotée d’une force redoutable.'),
        hinata: w('Hinata', 'Héritière timide d’un noble clan, secrètement amoureuse du héros du village.'),
        konoha: w('Konoha', 'Village caché de la Feuille, niché au pied d’une falaise sculptée de visages.'),
        suna: w('Suna', 'Village caché du Sable, bâti au milieu du désert et protégé par des falaises.'),
        rasengan: w('Rasengan', 'Sphère d’énergie tourbillonnante formée dans la paume et plaquée sur l’adversaire.'),
        chidori: w('Chidori', 'Décharge de foudre concentrée dans la main, dont le bruit évoque un chant d’oiseaux.'),
        sharingan: w('Sharingan', 'Œil rouge à virgules noires, capable de copier les techniques observées.'),
        byakugan: w('Byakugan', 'Œil blanc sans pupille visible qui voit à travers les obstacles, presque à 360 degrés.'),
        rinnegan: w('Rinnegan', 'Œil violet orné de cercles concentriques, réputé le plus puissant des pouvoirs oculaires.'),
        uchiwa: w('Uchiwa', 'Clan célèbre pour ses pupilles rouges et sa maîtrise des techniques de feu.'),
        hyuga: w('Hyûga', 'Clan noble aux yeux blancs, divisé entre une branche principale et une branche secondaire.'),
        hokage: w('Hokage', 'Titre du chef du village de la Feuille, dont le visage est sculpté dans la falaise.'),
        kazekage: w('Kazekage', 'Titre du chef du village du Sable, choisi parmi ses ninjas les plus puissants.'),
        chunin: w('Chûnin', 'Grade de ninja confirmé, obtenu en réussissant un examen organisé entre villages.'),
        jonin: w('Jônin', 'Grade de ninja d’élite, souvent chargé d’encadrer une équipe de jeunes recrues.'),
      },
      pairs: [
        p('naruto', 'gaara', 'Personnages'),
        p('naruto', 'rock-lee', 'Personnages'),
        p('rock-lee', 'neji', 'Ninjas'),
        p('sasuke', 'neji', 'Ninjas'),
        p('itachi', 'obito', 'Personnages'),
        p('obito', 'pain', 'Adversaires'),
        p('kakashi', 'jiraiya', 'Ninjas'),
        p('jiraiya', 'tsunade', 'Personnages'),
        p('tsunade', 'sakura', 'Ninjas'),
        p('sakura', 'hinata', 'Personnages'),
        p('konoha', 'suna', 'Lieux'),
        p('rasengan', 'chidori', 'Techniques'),
        p('sharingan', 'byakugan', 'Pouvoirs et techniques'),
        p('sharingan', 'rinnegan', 'Pouvoirs et techniques'),
        p('uchiwa', 'hyuga', 'Familles et organisations'),
        p('hokage', 'kazekage', 'Titres et grades'),
        p('chunin', 'jonin', 'Titres et grades'),
      ],
    }),

    universe({
      id: 'dragon-ball',
      name: 'Dragon Ball',
      precise: true,
      words: {
        goku: w('Goku', 'Guerrier au cœur pur élevé sur Terre, toujours en quête d’adversaires à sa mesure.'),
        gohan: w('Gohan', 'Fils aîné du héros, demi-Saiyan dont la colère libère une puissance cachée.'),
        trunks: w('Trunks', 'Demi-Saiyan venu du futur, épée dans le dos, pour empêcher une catastrophe.'),
        vegeta: w('Vegeta', 'Prince orgueilleux d’une race de guerriers, obsédé par la puissance.'),
        piccolo: w('Piccolo', 'Guerrier namek à la peau verte, ancien ennemi devenu un allié fidèle.'),
        krilin: w('Krilin', 'Moine chauve aux six points sur le front, meilleur ami du héros.'),
        yamcha: w('Yamcha', 'Ancien bandit du désert, combattant souvent battu, passionné de baseball.'),
        bulma: w('Bulma', 'Inventrice géniale aux cheveux bleus, héritière d’une grande entreprise.'),
        chichi: w('Chichi', 'Fille d’un roi, épouse au caractère explosif qui veut que ses fils étudient.'),
        'tortue-geniale': w('Tortue Géniale', 'Vieil ermite pervers à carapace, légende des arts martiaux vivant sur une île.'),
        kaio: w('Maître Kaïo', 'Divinité à antennes vivant sur une petite planète, qui entraîne des guerriers morts.'),
        freezer: w('Freezer', 'Empereur galactique cruel et raffiné, capable de plusieurs transformations.'),
        cell: w('Cell', 'Créature artificielle née des cellules de grands combattants, qui absorbe des androïdes.'),
        boo: w('Majin Boo', 'Créature rose et caoutchouteuse, créée par un sorcier, qui change ses ennemis en bonbons.'),
        kamehameha: w('Kamehameha', 'Rayon d’énergie lancé des deux mains jointes, enseigné par un vieil ermite.'),
        'final-flash': w('Final Flash', 'Rayon d’énergie dévastateur, lancé mains ouvertes, créé par le prince des Saiyans.'),
        genkidama: w('Genkidama', 'Immense sphère formée avec l’énergie prêtée par les êtres vivants alentour.'),
        kaioken: w('Kaioken', 'Technique qui multiplie la force un court moment, entourant le corps d’une aura rouge.'),
        'super-saiyan-blue': w('Super Saiyan Blue', 'Transformation divine aux cheveux et à l’aura bleus, née de la maîtrise du ki divin.'),
        'ultra-instinct': w('Ultra Instinct', 'État divin où le corps esquive et riposte seul, reconnaissable à ses cheveux argentés.'),
        fusion: w('Fusion', 'Danse synchronisée qui unit deux combattants de force égale pour une trentaine de minutes.'),
        potara: w('Potara', 'Paire de boucles d’oreilles divines qui unit leurs deux porteurs en un seul guerrier.'),
        'nuage-magique': w('Nuage magique', 'Nuage jaune volant sur lequel seules les personnes au cœur pur peuvent monter.'),
        'baton-magique': w('Bâton magique', 'Bâton rouge qui s’allonge à volonté, hérité d’un grand-père adoptif.'),
        'salle-esprit-temps': w('Salle de l’Esprit et du Temps', 'Pièce hors du monde où une année d’entraînement ne dure qu’une journée dehors.'),
        'tour-karine': w('Tour de Karine', 'Tour immense où vit un chat ermite qui cultive des haricots guérisseurs.'),
      },
      pairs: [
        p('goku', 'gohan', 'Personnages'),
        p('gohan', 'trunks', 'Personnages'),
        p('vegeta', 'piccolo', 'Combattants'),
        p('piccolo', 'krilin', 'Combattants'),
        p('krilin', 'yamcha', 'Combattants'),
        p('bulma', 'chichi', 'Personnages'),
        p('tortue-geniale', 'kaio', 'Personnages'),
        p('freezer', 'cell', 'Adversaires'),
        p('cell', 'boo', 'Adversaires'),
        p('kamehameha', 'final-flash', 'Techniques de combat'),
        p('kamehameha', 'genkidama', 'Techniques de combat'),
        p('genkidama', 'kaioken', 'Techniques de combat'),
        p('kaioken', 'ultra-instinct', 'Pouvoirs et transformations'),
        p('super-saiyan-blue', 'ultra-instinct', 'Pouvoirs et transformations'),
        p('fusion', 'potara', 'Pouvoirs et transformations'),
        p('nuage-magique', 'baton-magique', 'Objets'),
        p('salle-esprit-temps', 'tour-karine', 'Lieux'),
      ],
    }),
  ],
});
