import { definePack } from './types';

export default definePack({
  id: 'anime-manga',
  name: 'Anime & Manga',
  description: 'Héros de shōnen, films cultes et rivalités légendaires.',
  icon: 'swords',
  pairs: [
    ['Naruto', 'Sasuke'],
    ['One Piece', 'Fairy Tail'],
    ['Goku', 'Vegeta'],
    ['Luffy', 'Zoro'],
    ['Dragon Ball', 'Saint Seiya'],
    ['Death Note', 'Code Geass'],
    ['Demon Slayer', 'Jujutsu Kaisen'],
    ["L'Attaque des Titans", 'Tokyo Ghoul'],
    ['Pikachu', 'Rondoudou'],
    ['Pokémon', 'Digimon'],
    ['Kakashi', 'Itachi'],
    ['Nami', 'Robin'],
    ['Gon', 'Killua'],
    ['Totoro', 'Ponyo'],
    ['Le Voyage de Chihiro', 'Princesse Mononoké'],
    ['Sailor Moon', 'Sakura chasseuse de cartes'],
    ['Olive et Tom', 'Inazuma Eleven'],
    ['Nicky Larson', 'Cobra'],
    ['Bleach', 'Black Clover'],
    ['My Hero Academia', 'One Punch Man'],
    ['Tanjiro', 'Nezuko'],
    ['Eren', 'Livaï'],
    ['Gojo', 'Sukuna'],
    ['Deku', 'Bakugo'],
    ['Freezer', 'Cell'],
    ['Ace', 'Sabo'],
    ['Manga', 'Manhwa'],
    ['Blue Lock', 'Haikyuu'],
    ["Kuroko's Basket", 'Slam Dunk'],
    ['Solo Leveling', 'Sword Art Online'],
    ['Doraemon', 'Shin-chan'],
    ['Chainsaw Man', 'Dandadan'],
    ['Ken le Survivant', "JoJo's Bizarre Adventure"],
    ['Kamehameha', 'Rasengan'],
    ['Sharingan', 'Byakugan'],
  ],
});
