import { definePack, pair } from './types';

export default definePack({
  id: 'anime-manga',
  name: 'Anime & Manga',
  description: 'Héros de shōnen, films cultes et rivalités légendaires.',
  icon: 'swords',
  pairs: [
    pair(
      'Univers ninja',
      ['Naruto', 'Jeune ninja blond et bruyant qui rêve de devenir le chef de son village.'],
      ['Sasuke', 'Ninja taciturne aux cheveux noirs, en quête de vengeance après le massacre de son clan.'],
    ),
    pair(
      'Shōnen d’aventure',
      ['One Piece', 'Manga d’Eiichirō Oda sur un équipage de pirates en quête d’un trésor légendaire.'],
      ['Fairy Tail', 'Manga de Hiro Mashima qui suit une guilde de mages et leurs missions.'],
    ),
    pair(
      'Guerriers extraterrestres',
      ['Goku', 'Guerrier au cœur pur élevé sur Terre, toujours en quête d’adversaires plus forts.'],
      ['Vegeta', 'Prince orgueilleux d’une race de guerriers, obsédé par la puissance.'],
    ),
    pair(
      'Équipage pirate',
      ['Luffy', 'Capitaine au chapeau de paille dont le corps est élastique comme du caoutchouc.'],
      ['Zoro', 'Épéiste aux cheveux verts qui combat avec trois sabres.'],
    ),
    pair(
      'Shōnen culte des années 80',
      ['Dragon Ball', 'Manga d’Akira Toriyama où des combattants cherchent sept boules magiques.'],
      ['Saint Seiya', 'Manga de Masami Kurumada où des chevaliers en armure protègent la déesse Athéna.'],
    ),
    pair(
      'Anti-héros et pouvoir surnaturel',
      ['Death Note', 'Manga où un lycéen trouve un cahier qui tue quiconque y est nommé.'],
      ['Code Geass', 'Anime où un prince exilé obtient le pouvoir d’imposer sa volonté par le regard.'],
    ),
    pair(
      'Shōnen surnaturel récent',
      ['Demon Slayer', 'Manga où un jeune garçon traque les démons pour guérir sa sœur transformée.'],
      ['Jujutsu Kaisen', 'Manga où un lycéen avale un doigt maudit et rejoint une école d’exorcistes.'],
    ),
    pair(
      'Manga sombre et horrifique',
      ["L'Attaque des Titans", 'Manga où l’humanité survit derrière d’immenses murs face à des géants.'],
      ['Tokyo Ghoul', 'Manga où un étudiant devient mi-humain, mi-goule après une greffe d’organes.'],
    ),
    pair(
      'Créatures à collectionner',
      ['Pikachu', 'Petite souris jaune qui produit de l’électricité avec ses joues.'],
      ['Rondoudou', 'Créature rose et ronde dont la chanson endort ceux qui l’écoutent.'],
    ),
    pair(
      'Créatures qui évoluent',
      ['Pokémon', 'Franchise japonaise où des dresseurs capturent des créatures et les font combattre.'],
      ['Digimon', 'Franchise japonaise de monstres numériques vivant dans un monde informatique.'],
    ),
    pair(
      'Ninjas d’élite',
      ['Kakashi', 'Ninja aux cheveux argentés, le bas du visage masqué, qui encadre de jeunes élèves.'],
      ['Itachi', 'Ninja prodige qui a quitté son village après avoir décimé son propre clan.'],
    ),
    pair(
      'Héroïnes pirates',
      ['Nami', 'Navigatrice rousse passionnée de cartes marines et très attachée à l’argent.'],
      ['Robin', 'Archéologue brune capable de faire pousser des bras sur n’importe quelle surface.'],
    ),
    pair(
      'Duo de jeunes aventuriers',
      ['Gon', 'Jeune garçon de la campagne, pêcheur doué, parti à la recherche de son père.'],
      ['Killua', 'Jeune garçon aux cheveux blancs issu d’une célèbre famille d’assassins.'],
    ),
    pair(
      'Créature de film d’animation',
      ['Totoro', 'Grand esprit de la forêt, gris et poilu, qui se lie d’amitié avec deux fillettes.'],
      ['Ponyo', 'Petit poisson rouge magique qui rêve de devenir une petite fille.'],
    ),
    pair(
      'Films d’animation japonais',
      ['Le Voyage de Chihiro', 'Film de Hayao Miyazaki où une fillette travaille dans des bains fréquentés par des esprits.'],
      ['Princesse Mononoké', 'Film de Hayao Miyazaki où un jeune prince maudit croise une fille élevée par des loups.'],
    ),
    pair('Héroïnes d’anime des années 90',
      ['Sailor Moon', 'Collégienne qui se transforme en guerrière de l’amour et de la justice, guidée par un chat.'],
      ['Sakura chasseuse de cartes', 'Écolière qui doit retrouver des cartes magiques échappées d’un livre enchanté.'],
    ),
    pair(
      'Sport en animation japonaise',
      ['Olive et Tom', 'Anime où un jeune prodige du ballon rond rêve de gagner la Coupe du monde.'],
      ['Inazuma Eleven', 'Jeux vidéo et anime où des collégiens jouent au foot avec des tirs spéciaux.'],
    ),
    pair(
      'Héros d’action rétro',
      ['Nicky Larson', 'Nettoyeur de Tokyo, tireur d’élite hors pair et dragueur invétéré.'],
      ['Cobra', 'Pirate de l’espace qui cache une arme redoutable dans son bras gauche.'],
    ),
    pair(
      'Shōnen fantastique',
      ['Bleach', 'Manga où un lycéen qui voit les fantômes devient faucheur d’âmes.'],
      ['Black Clover', 'Manga où un orphelin né sans magie rêve de devenir le plus grand des mages.'],
    ),
    pair(
      'Super-héros japonais',
      ['My Hero Academia', 'Manga où des lycéens dotés de super-pouvoirs étudient pour devenir héros professionnels.'],
      ['One Punch Man', 'Manga parodique dont le héros chauve bat n’importe quel ennemi d’un seul coup.'],
    ),
    pair('Héros de manga récents',
      ['Tanjiro', 'Jeune épéiste au grand cœur, doté d’un odorat exceptionnel.'],
      ['Nezuko', 'Jeune fille changée en démon, qui porte un bâillon de bambou.'],
    ),
    pair('Héros de manga sombres',
      ['Eren', 'Jeune soldat impulsif qui a juré d’exterminer les géants après la mort de sa mère.'],
      ['Livaï', 'Capitaine petit et maniaque de la propreté, réputé le soldat le plus fort de l’humanité.'],
    ),
    pair('Personnages de shōnen récents',
      ['Gojo', 'Exorciste aux cheveux blancs, les yeux bandés, réputé le plus puissant de son époque.'],
      ['Sukuna', 'Roi des fléaux aux quatre bras et quatre yeux, dont les doigts maudits sont dispersés.'],
    ),
    pair('Personnages de shōnen',
      ['Deku', 'Garçon aux cheveux verts né sans pouvoir, qui hérite d’un pouvoir surpuissant.'],
      ['Bakugo', 'Lycéen colérique et orgueilleux qui provoque des explosions avec ses mains.'],
    ),
    pair(
      'Grands méchants de shōnen',
      ['Freezer', 'Empereur galactique cruel et raffiné, capable de plusieurs transformations.'],
      ['Cell', 'Créature artificielle née des cellules de grands combattants, qui absorbe des androïdes.'],
    ),
    pair('Personnages de manga',
      ['Ace', 'Pirate torse nu au chapeau orange, capable de se transformer en flammes.'],
      ['Sabo', 'Révolutionnaire au haut-de-forme, longtemps cru mort après une attaque subie enfant.'],
    ),
    pair(
      'Bande dessinée asiatique',
      ['Manga', 'Bande dessinée japonaise, lue traditionnellement de droite à gauche.'],
      ['Manhwa', 'Bande dessinée coréenne, souvent en couleur et lue en défilement vertical.'],
    ),
    pair(
      'Manga sportif de compétition',
      ['Blue Lock', 'Manga où des attaquants s’affrontent dans un centre fermé pour former le meilleur buteur.'],
      ['Haikyuu', 'Manga où un lycéen de petite taille se passionne pour le volley-ball.'],
    ),
    pair(
      'Manga de sport lycéen',
      ["Kuroko's Basket", 'Manga où un joueur presque invisible sur le terrain excelle dans l’art de la passe.'],
      ['Slam Dunk', 'Manga de Takehiko Inoue où un voyou roux rejoint une équipe pour plaire à une fille.'],
    ),
    pair(
      'Aventures façon jeu vidéo',
      ['Solo Leveling', 'Webtoon coréen où le plus faible des chasseurs de monstres devient surpuissant.'],
      ['Sword Art Online', 'Light novel où des joueurs restent piégés dans un jeu en réalité virtuelle.'],
    ),
    pair(
      'Humour animé pour enfants',
      ['Doraemon', 'Chat-robot bleu venu du futur, qui sort des gadgets de sa poche magique.'],
      ['Shin-chan', 'Petit garçon de cinq ans espiègle et insolent, célèbre pour ses bêtises.'],
    ),
    pair(
      'Manga d’action déjanté',
      ['Chainsaw Man', 'Manga où un jeune endetté fusionne avec un démon et se change en homme-tronçonneuse.'],
      ['Dandadan', 'Manga mêlant fantômes et extraterrestres autour de deux lycéens aux croyances opposées.'],
    ),
    pair(
      'Combattants musclés des années 80',
      ['Ken le Survivant', 'Manga post-apocalyptique où un maître d’arts martiaux frappe les points vitaux.'],
      ["JoJo's Bizarre Adventure", 'Saga de Hirohiko Araki qui suit plusieurs générations d’une même famille.'],
    ),
    pair(
      'Techniques de combat célèbres',
      ['Kamehameha', 'Rayon d’énergie lancé à deux mains, enseigné par un vieux maître des arts martiaux.'],
      ['Rasengan', 'Sphère d’énergie tourbillonnante formée dans la paume et plaquée sur l’adversaire.'],
    ),
    pair('Pouvoirs de manga',
      ['Sharingan', 'Œil rouge à virgules noires capable de copier les techniques observées.'],
      ['Byakugan', 'Œil blanc sans pupille visible qui voit à travers les obstacles, presque à 360 degrés.'],
    ),
  ],
});
