import { definePack } from './types';

export default definePack({
  id: 'animaux',
  name: 'Animaux',
  description: 'De la savane aux océans : bêtes à plumes, à poils et à écailles.',
  icon: 'paw-print',
  pairs: [
    ['Tigre', 'Lion'],
    ['Dauphin', 'Baleine'],
    ['Chat', 'Chien'],
    ['Loup', 'Renard'],
    ['Aigle', 'Faucon'],
    ['Cheval', 'Âne'],
    ['Mouton', 'Chèvre'],
    ['Vache', 'Cochon'],
    ['Lapin', 'Lièvre'],
    ['Souris', 'Hamster'],
    ['Crocodile', 'Alligator'],
    ['Serpent', 'Anguille'],
    ['Grenouille', 'Crapaud'],
    ['Abeille', 'Guêpe'],
    ['Papillon', 'Libellule'],
    ['Moustique', 'Mouche'],
    ['Requin', 'Orque'],
    ['Pingouin', 'Manchot'],
    ['Hibou', 'Chouette'],
    ['Perroquet', 'Toucan'],
    ['Pigeon', 'Mouette'],
    ['Poule', 'Canard'],
    ['Girafe', 'Zèbre'],
    ['Éléphant', 'Rhinocéros'],
    ['Phoque', 'Otarie'],
    ['Ours', 'Panda'],
    ['Kangourou', 'Koala'],
    ['Chimpanzé', 'Gorille'],
    ['Escargot', 'Limace'],
    ['Hérisson', 'Porc-épic'],
    ['Poisson rouge', 'Poisson-clown'],
    ['Pieuvre', 'Méduse'],
    ['Crabe', 'Homard'],
    ['Chameau', 'Dromadaire'],
    ['Guépard', 'Léopard'],
    ['Écureuil', 'Marmotte'],
    ['Cerf', 'Chevreuil'],
    ['Flamant rose', 'Cygne'],
    ['Paon', 'Faisan'],
    ['Lama', 'Alpaga'],
    ['Loutre', 'Castor'],
    ['Fourmi', 'Termite'],
  ],
});
