import { definePack, pair } from './types';

export default definePack({
  id: 'animaux',
  name: 'Animaux',
  description: 'De la savane aux océans : bêtes à plumes, à poils et à écailles.',
  icon: 'paw-print',
  pairs: [
    pair('Grands félins', ['Tigre', 'Fauve d’Asie au pelage orangé rayé de noir, excellent nageur.'], ['Lion', 'Fauve des savanes africaines vivant en troupe, dont le mâle porte une crinière.']),
    pair('Mammifères marins', ['Dauphin', 'Mammifère marin joueur et intelligent, qui se repère par écholocation.'], ['Baleine', 'Immense mammifère marin qui se nourrit de krill filtré par ses fanons.']),
    pair('Animaux de compagnie', ['Chat', 'Petit félin domestique qui ronronne et miaule.'], ['Chien', 'Animal domestique fidèle qui aboie, descendant du loup.']),
    pair('Canidés sauvages', ['Loup', 'Canidé sauvage vivant en meute, connu pour ses hurlements.'], ['Renard', 'Petit canidé roux à queue touffue, réputé rusé dans les fables.']),
    pair('Rapaces diurnes', ['Aigle', 'Grand rapace aux serres puissantes, qui niche souvent en montagne.'], ['Faucon', 'Rapace rapide aux ailes pointues, champion du vol en piqué.']),
    pair('Animaux domestiques', ['Cheval', 'Grand équidé domestique qu’on monte, qui galope et hennit.'], ['Âne', 'Équidé aux longues oreilles, réputé têtu, qui brait.']),
    pair('Petits ruminants de ferme', ['Mouton', 'Ruminant de ferme élevé pour sa laine et sa viande, qui bêle.'], ['Chèvre', 'Ruminant à cornes et barbichette, dont le lait sert à faire des fromages.']),
    pair('Animaux de la ferme', ['Vache', 'Ruminant de ferme élevé pour son lait, qui meugle dans les prés.'], ['Cochon', 'Animal de ferme rose au groin, qui se roule dans la boue.']),
    pair('Petits mammifères sauteurs', ['Lapin', 'Petit mammifère aux longues oreilles vivant en terrier, souvent domestiqué.'], ['Lièvre', 'Mammifère sauvage des plaines, coureur très rapide aux grandes pattes arrière.']),
    pair('Petits rongeurs', ['Souris', 'Petit rongeur gris à longue queue fine, qui couine.'], ['Hamster', 'Rongeur dodu qui stocke sa nourriture dans ses bajoues.']),
    pair('Reptiles', ['Crocodile', 'Grand reptile au museau pointu, présent en Afrique, en Asie et en Australie.'], ['Alligator', 'Grand reptile au museau large et arrondi, vivant surtout dans le sud-est des États-Unis.']),
    pair('Animaux au corps allongé', ['Serpent', 'Reptile sans pattes qui rampe et change de peau, parfois venimeux.'], ['Anguille', 'Poisson au corps allongé et visqueux, qui migre en mer pour se reproduire.']),
    pair('Animaux des mares',['Grenouille', 'Amphibien à peau lisse et humide, bon sauteur, qui coasse.'], ['Crapaud', 'Amphibien trapu à la peau épaisse et verruqueuse, surtout nocturne.']),
    pair('Insectes à dard', ['Abeille', 'Insecte butineur qui produit le miel et vit en ruche.'], ['Guêpe', 'Insecte rayé jaune et noir à taille fine, attiré par le sucre en été.']),
    pair('Insectes aux grandes ailes', ['Papillon', 'Insecte aux ailes colorées couvertes d’écailles, issu d’une chenille.'], ['Libellule', 'Insecte aux ailes transparentes et au long abdomen, qui chasse près de l’eau.']),
    pair('Insectes agaçants', ['Moustique', 'Insecte dont la femelle pique pour se nourrir de sang.'], ['Mouche', 'Insecte bourdonnant qui se pose sur la nourriture et les déchets.']),
    pair('Prédateurs des océans', ['Requin', 'Poisson prédateur au squelette cartilagineux et aux rangées de dents.'], ['Orque', 'Mammifère marin noir et blanc, grand chasseur vivant en groupe familial.']),
    pair('Oiseaux des mers froides', ['Pingouin', 'Oiseau marin noir et blanc de l’Atlantique Nord, qui niche sur les falaises.'], ['Manchot', 'Oiseau nageur de l’hémisphère Sud, aux ailes en nageoires, vivant en colonies.']),
    pair('Oiseaux de la forêt', ['Hibou', 'Rapace nocturne reconnaissable aux aigrettes de plumes sur sa tête.'], ['Chouette', 'Rapace nocturne à tête ronde, symbole de sagesse et d’Athéna.']),
    pair('Oiseaux tropicaux colorés', ['Perroquet', 'Oiseau tropical coloré au bec crochu, capable d’imiter la voix.'], ['Toucan', 'Oiseau tropical d’Amérique au bec énorme et coloré.']),
    pair('Oiseaux des villes', ['Pigeon', 'Oiseau gris des places publiques, jadis utilisé pour porter des messages.'], ['Mouette', 'Oiseau blanc et gris des côtes, au cri perçant, qui suit les bateaux.']),
    pair('Volailles de la basse-cour', ['Poule', 'Oiseau de basse-cour qui caquette et pond des œufs.'], ['Canard', 'Oiseau aux pattes palmées qui barbote dans les mares et cancane.']),
    pair('Animaux de la savane', ['Girafe', 'Mammifère africain au très long cou, le plus haut des animaux terrestres.'], ['Zèbre', 'Équidé africain au pelage rayé noir et blanc, vivant en troupeau.']),
    pair('Géants herbivores', ['Éléphant', 'Plus grand animal terrestre, doté d’une trompe et de défenses.'], ['Rhinocéros', 'Gros herbivore à peau épaisse, portant une ou deux cornes sur le nez.']),
    pair('Mammifères marins à nageoires', ['Phoque', 'Mammifère marin au corps fuselé, qui se déplace à terre en rampant sur le ventre.'], ['Otarie', 'Mammifère marin à petites oreilles visibles, star des numéros de cirque.']),
    pair('Gros mammifères des forêts', ['Ours', 'Grand mammifère massif et omnivore, qui hiberne et raffole du miel.'], ['Panda', 'Mammifère noir et blanc des montagnes de Chine, qui mange du bambou.']),
    pair('Faune australienne', ['Kangourou', 'Marsupial qui se déplace par bonds et porte son petit dans une poche.'], ['Koala', 'Marsupial grimpeur et dormeur qui se nourrit de feuilles d’eucalyptus.']),
    pair('Grands singes', ['Chimpanzé', 'Singe d’Afrique très proche de l’humain, qui utilise des outils.'], ['Gorille', 'Plus grand des primates, dont le mâle dominant a le dos argenté.']),
    pair('Mollusques de jardin', ['Escargot', 'Mollusque qui porte une coquille en spirale et laisse une trace de bave.'], ['Limace', 'Mollusque terrestre au corps nu et gluant, qui dévore les salades.']),
    pair('Petits mammifères', ['Hérisson', 'Petit mammifère nocturne couvert de piquants, qui se roule en boule.'], ['Porc-épic', 'Rongeur armé de longs piquants creux, qu’il dresse face au danger.']),
    pair('Habitants d’aquarium', ['Poisson rouge', 'Petit poisson orangé d’eau douce, élevé en bocal ou en bassin.'], ['Poisson-clown', 'Poisson marin orange rayé de blanc, qui vit parmi les anémones de mer.']),
    pair('Invertébrés marins', ['Pieuvre', 'Mollusque marin à huit bras munis de ventouses, qui crache de l’encre.'], ['Méduse', 'Animal marin gélatineux et translucide, aux filaments urticants.']),
    pair('Crustacés à pinces', ['Crabe', 'Crustacé à large carapace qui se déplace de côté.'], ['Homard', 'Crustacé marin à grosses pinces, bleu vivant et rouge une fois cuit.']),
    pair('Animaux du désert', ['Chameau', 'Mammifère d’Asie centrale à deux bosses, résistant au froid comme à la chaleur.'], ['Dromadaire', 'Mammifère du Sahara et d’Arabie à une bosse, surnommé vaisseau du désert.']),
    pair('Félins tachetés', ['Guépard', 'Félin élancé de la savane, animal terrestre le plus rapide au monde.'], ['Léopard', 'Félin puissant à taches en rosettes, qui hisse ses proies dans les arbres.']),
    pair('Rongeurs sauvages', ['Écureuil', 'Petit rongeur roux à queue en panache, qui vit dans les arbres.'], ['Marmotte', 'Rongeur des montagnes qui siffle pour alerter et hiberne longuement.']),
    pair('Gibier des forêts', ['Cerf', 'Grand ruminant des forêts dont le mâle porte des bois ramifiés et brame.'], ['Chevreuil', 'Petit ruminant forestier au pelage roux en été, à la tache blanche sur les fesses.']),
    pair('Oiseaux d’eau au long cou', ['Flamant rose', 'Échassier des lagunes qui dort sur une patte, coloré par sa nourriture.'], ['Cygne', 'Grand oiseau aquatique au long cou courbé, généralement blanc.']),
    pair('Oiseaux à longue queue', ['Paon', 'Oiseau qui déploie en roue une traîne ornée d’ocelles bleus et verts.'], ['Faisan', 'Oiseau gibier au mâle cuivré à tête verte, doté d’une longue queue.']),
    pair('Animaux d’Amérique du Sud', ['Lama', 'Animal de bât des Andes, au long cou, réputé pour cracher.'], ['Alpaga', 'Petit camélidé andin élevé pour sa laine fine et très douce.']),
    pair('Mammifères des rivières', ['Loutre', 'Mammifère aquatique joueur au pelage dense, qui pêche des poissons.'], ['Castor', 'Rongeur aquatique à queue plate qui construit des barrages.']),
    pair('Insectes sociaux', ['Fourmi', 'Petit insecte social capable de porter bien plus que son propre poids.'], ['Termite', 'Insecte social qui dévore le bois et peut ravager les charpentes.']),
  ],
});
