import { definePack } from './types';

export default definePack({
  id: 'chanteurs',
  name: 'Chanteurs & Chanteuses',
  description: "Stars de la pop, voix mythiques et idoles d'hier et d'aujourd'hui.",
  icon: 'mic-vocal',
  pairs: [
    ['Beyoncé', 'Rihanna'],
    ['Stromae', 'Orelsan'],
    ['Taylor Swift', 'Katy Perry'],
    ['Ed Sheeran', 'Bruno Mars'],
    ['Michael Jackson', 'Prince'],
    ['Madonna', 'Lady Gaga'],
    ['Whitney Houston', 'Mariah Carey'],
    ['Céline Dion', 'Lara Fabian'],
    ['Johnny Hallyday', 'Eddy Mitchell'],
    ['Angèle', 'Clara Luciani'],
    ['Aya Nakamura', 'Wejdene'],
    ['Vianney', 'Kendji Girac'],
    ['Indila', 'Zaz'],
    ['The Weeknd', 'Drake'],
    ['Billie Eilish', 'Olivia Rodrigo'],
    ['Ariana Grande', 'Selena Gomez'],
    ['Shakira', 'Jennifer Lopez'],
    ['Elvis Presley', 'Johnny Cash'],
    ['Freddie Mercury', 'David Bowie'],
    ['Édith Piaf', 'Dalida'],
    ['Jacques Brel', 'Georges Brassens'],
    ['Mylène Farmer', 'Patricia Kaas'],
    ['Christophe Maé', 'Calogero'],
    ['M. Pokora', 'Amir'],
    ['Louane', 'Vitaa'],
    ['Adele', 'Amy Winehouse'],
    ['Dua Lipa', 'Rita Ora'],
    ['Justin Bieber', 'Shawn Mendes'],
    ['Harry Styles', 'Justin Timberlake'],
    ['Britney Spears', 'Christina Aguilera'],
    ['Francis Cabrel', 'Jean-Jacques Goldman'],
    ['Renaud', 'Alain Souchon'],
    ['Charles Aznavour', 'Serge Gainsbourg'],
    ['Sia', 'Pink'],
    ['Nicki Minaj', 'Cardi B'],
    ['Slimane', 'Claudio Capéo'],
    ['Eminem', 'Snoop Dogg'],
  ],
});
