import { definePack, p, universe, w } from './types';

export default definePack({
  id: 'films-series',
  name: 'Films & Séries',
  description: 'Sagas, sitcoms, blockbusters et séries à dévorer.',
  icon: 'clapperboard',
  universes: [
    universe({
      id: 'general',
      name: 'Films & Séries',
      precise: false,
      words: {
        'harry-potter': w('Harry Potter', 'Saga de huit films sur un jeune sorcier, adaptée des romans de J.K. Rowling.'),
        'seigneur-anneaux': w('Le Seigneur des anneaux', 'Trilogie de Peter Jackson adaptée de Tolkien, qui se déroule en Terre du Milieu.'),
        'star-wars': w('Star Wars', 'Saga de George Lucas avec des chevaliers Jedi, des sabres laser et un Empire galactique.'),
        dune: w('Dune', 'Film de Denis Villeneuve adapté de Frank Herbert, sur la planète désertique Arrakis.'),
        avatar: w('Avatar', 'Film de James Cameron sur la planète Pandora et son peuple à la peau bleue, les Na’vi.'),
        titanic: w('Titanic', 'Film de James Cameron sur le naufrage d’un paquebot en 1912, avec Leonardo DiCaprio.'),
        'game-of-thrones': w('Game of Thrones', 'Série de fantasy où de grandes familles se disputent le Trône de fer à Westeros.'),
        'the-witcher': w('The Witcher', 'Série de fantasy où Geralt de Riv, chasseur de monstres, parcourt le Continent.'),
        friends: w('Friends', 'Sitcom sur six amis new-yorkais qui se retrouvent au café Central Perk.'),
        himym: w('How I Met Your Mother', 'Sitcom où Ted Mosby raconte à ses enfants comment il a rencontré leur mère.'),
        'big-bang-theory': w('The Big Bang Theory', 'Sitcom sur des scientifiques de Pasadena passionnés de comics, dont Sheldon Cooper.'),
        'breaking-bad': w('Breaking Bad', 'Série où un professeur de chimie devient fabricant de méthamphétamine.'),
        narcos: w('Narcos', 'Série sur la traque du baron de la drogue Pablo Escobar en Colombie.'),
        scarface: w('Scarface', 'Film de Brian De Palma sur l’ascension d’un trafiquant cubain à Miami, avec Al Pacino.'),
        parrain: w('Le Parrain', 'Film de Francis Ford Coppola sur la famille mafieuse Corleone, avec Marlon Brando.'),
        'casa-de-papel': w('La Casa de Papel', 'Série espagnole de braqueurs en combinaison rouge portant des masques de Dalí.'),
        'prison-break': w('Prison Break', 'Série où un ingénieur se fait incarcérer volontairement pour faire évader son frère.'),
        lupin: w('Lupin', 'Série Netflix avec Omar Sy en cambrioleur inspiré des romans de Maurice Leblanc.'),
        sherlock: w('Sherlock', 'Série britannique où un détective génial mène ses enquêtes dans le Londres actuel.'),
        'dr-house': w('Dr House', 'Série médicale sur un diagnosticien brillant, boiteux et misanthrope.'),
        'greys-anatomy': w('Grey’s Anatomy', 'Série médicale qui suit des internes en chirurgie dans un hôpital de Seattle.'),
        'stranger-things': w('Stranger Things', 'Série où des enfants des années 80 affrontent des créatures d’une dimension parallèle.'),
        wednesday: w('Wednesday', 'Série où la fille de la famille Addams enquête au sein du pensionnat Nevermore.'),
        'iron-man': w('Iron Man', 'Héros de comics, génie milliardaire qui combat dans une armure high-tech.'),
        batman: w('Batman', 'Justicier masqué de Gotham City, milliardaire sans superpouvoirs, héros de DC.'),
        simpson: w('Les Simpson', 'Série animée sur une famille jaune de Springfield, avec Homer, Marge et Bart.'),
        'south-park': w('South Park', 'Série animée satirique sur quatre écoliers d’une petite ville du Colorado.'),
        griffin: w('Les Griffin', 'Série animée sur une famille de Quahog, avec Peter, Lois, un bébé et un chien qui parle.'),
        shrek: w('Shrek', 'Film d’animation DreamWorks sur un ogre vert accompagné d’un âne bavard.'),
        'age-de-glace': w('L’Âge de glace', 'Film d’animation où un mammouth, un paresseux et un tigre à dents de sabre font équipe.'),
        'toy-story': w('Toy Story', 'Film Pixar où des jouets prennent vie, avec le cow-boy Woody et Buzz l’Éclair.'),
        'monstres-et-cie': w('Monstres et Cie', 'Film Pixar où Sulli et Bob effraient les enfants pour produire de l’énergie.'),
        'roi-lion': w('Le Roi Lion', 'Classique Disney où le jeune Simba doit reprendre le trône volé par son oncle Scar.'),
        'livre-jungle': w('Le Livre de la jungle', 'Classique Disney où Mowgli, enfant élevé par des loups, croise Baloo et Shere Khan.'),
        'reine-des-neiges': w('La Reine des neiges', 'Film Disney où Elsa, dotée de pouvoirs glacés, s’enfuit du royaume d’Arendelle.'),
        raiponce: w('Raiponce', 'Film Disney sur une princesse aux très longs cheveux, enfermée dans une tour.'),
        vaiana: w('Vaiana', 'Film Disney où une fille de chef polynésienne prend la mer avec le demi-dieu Maui.'),
        'jurassic-park': w('Jurassic Park', 'Film de Spielberg sur un parc d’attractions peuplé de dinosaures clonés.'),
        'king-kong': w('King Kong', 'Film sur un gorille géant capturé sur une île et exhibé à New York.'),
        matrix: w('Matrix', 'Film de science-fiction où Neo découvre que le monde est une simulation informatique.'),
        inception: w('Inception', 'Film de Christopher Nolan où des voleurs s’infiltrent dans les rêves de leurs cibles.'),
        terminator: w('Terminator', 'Film où un cyborg venu de l’avenir traque une femme, avec Arnold Schwarzenegger.'),
        'retour-futur': w('Retour vers le futur', 'Film où Marty McFly voyage dans le temps à bord d’une DeLorean.'),
        'fast-furious': w('Fast & Furious', 'Saga d’action américaine autour de courses de voitures, avec Vin Diesel.'),
        taxi: w('Taxi', 'Comédie d’action produite par Luc Besson, avec un chauffeur marseillais ultrarapide.'),
        bronzes: w('Les Bronzés', 'Comédie culte de la troupe du Splendid sur un groupe de vacanciers en club.'),
        camping: w('Camping', 'Comédie avec Franck Dubosc en vacancier maladroit, fidèle des Flots Bleus.'),
        intouchables: w('Intouchables', 'Comédie sur l’amitié entre un riche tétraplégique et son auxiliaire de vie, avec Omar Sy.'),
        chtis: w('Bienvenue chez les Ch’tis', 'Comédie de Dany Boon où un directeur de poste du Sud est muté dans le Nord.'),
        visiteurs: w('Les Visiteurs', 'Comédie où un chevalier du Moyen Âge et son écuyer atterrissent à notre époque.'),
        kaamelott: w('Kaamelott', 'Série humoristique d’Alexandre Astier sur le roi Arthur et ses chevaliers.'),
        'mission-cleopatre': w('Mission Cléopâtre', 'Comédie d’Alain Chabat où deux Gaulois aident un architecte égyptien à bâtir un palais.'),
        'squid-game': w('Squid Game', 'Série coréenne où des endettés s’affrontent dans des jeux d’enfants mortels.'),
        'hunger-games': w('Hunger Games', 'Saga où Katniss Everdeen participe à des jeux télévisés mortels à Panem.'),
        pirates: w('Pirates des Caraïbes', 'Saga Disney avec Johnny Depp dans le rôle de l’excentrique capitaine Jack Sparrow.'),
        'indiana-jones': w('Indiana Jones', 'Saga d’aventures avec Harrison Ford en archéologue au fouet et au chapeau.'),
        'james-bond': w('James Bond', 'Saga d’espionnage autour de l’agent britannique 007, au service de Sa Majesté.'),
        'mission-impossible': w('Mission Impossible', 'Saga d’espionnage avec Tom Cruise en agent Ethan Hunt, adepte des cascades.'),
        'oss-117': w('OSS 117', 'Comédie d’espionnage avec Jean Dujardin en agent secret français sûr de lui et gaffeur.'),
        'walking-dead': w('The Walking Dead', 'Série où un shérif et d’autres survivants affrontent une apocalypse zombie.'),
        'last-of-us': w('The Last of Us', 'Série adaptée d’un jeu vidéo où Joel escorte l’adolescente Ellie dans un monde ravagé.'),
        scream: w('Scream', 'Film d’horreur où un tueur au masque de fantôme harcèle des lycéens au téléphone.'),
        halloween: w('Halloween', 'Film d’horreur de John Carpenter où Michael Myers traque des baby-sitters.'),
        'emily-in-paris': w('Emily in Paris', 'Série où une jeune Américaine travaille dans une agence de marketing parisienne.'),
        'diable-prada': w('Le Diable s’habille en Prada', 'Film avec Meryl Streep en rédactrice en chef tyrannique d’un magazine de mode.'),
      },
      pairs: [
        p('harry-potter', 'seigneur-anneaux', 'Sagas fantastiques'),
        p('harry-potter', 'star-wars', 'Grandes sagas du cinéma'),
        p('seigneur-anneaux', 'game-of-thrones', 'Univers de fantasy'),
        p('star-wars', 'dune', 'Science-fiction au cinéma'),
        p('dune', 'avatar', 'Films de science-fiction'),
        p('avatar', 'titanic', 'Records du box-office'),
        p('game-of-thrones', 'the-witcher', 'Séries de fantasy'),
        p('friends', 'himym', 'Sitcoms américaines'),
        p('friends', 'big-bang-theory', 'Séries comiques'),
        p('breaking-bad', 'narcos', 'Séries criminelles'),
        p('narcos', 'scarface', 'Histoires de gangsters'),
        p('scarface', 'parrain', 'Films de gangsters'),
        p('casa-de-papel', 'prison-break', 'Séries à suspense'),
        p('casa-de-papel', 'lupin', 'Séries Netflix à succès'),
        p('lupin', 'sherlock', 'Séries européennes'),
        p('sherlock', 'dr-house', 'Héros de séries'),
        p('dr-house', 'greys-anatomy', 'Séries médicales'),
        p('stranger-things', 'wednesday', 'Séries fantastiques'),
        p('iron-man', 'batman', 'Super-héros'),
        p('simpson', 'south-park', 'Dessins animés pour adultes'),
        p('simpson', 'griffin', 'Séries d’animation'),
        p('shrek', 'age-de-glace', 'Films d’animation'),
        p('shrek', 'toy-story', 'Dessins animés au cinéma'),
        p('toy-story', 'monstres-et-cie', 'Films pour enfants'),
        p('roi-lion', 'livre-jungle', 'Classiques Disney'),
        p('reine-des-neiges', 'raiponce', 'Films Disney'),
        p('reine-des-neiges', 'vaiana', 'Héroïnes de dessins animés'),
        p('jurassic-park', 'king-kong', 'Créatures au cinéma'),
        p('matrix', 'inception', 'Films à grand spectacle'),
        p('matrix', 'terminator', 'Films de science-fiction'),
        p('terminator', 'retour-futur', 'Films cultes des années 80'),
        p('fast-furious', 'taxi', 'Films d’action'),
        p('bronzes', 'camping', 'Comédies françaises'),
        p('camping', 'chtis', 'Comédies populaires'),
        p('intouchables', 'chtis', 'Succès du cinéma français'),
        p('visiteurs', 'kaamelott', 'Humour à la française'),
        p('visiteurs', 'mission-cleopatre', 'Comédies françaises cultes'),
        p('squid-game', 'hunger-games', 'Fictions de survie'),
        p('pirates', 'indiana-jones', 'Films d’aventure'),
        p('james-bond', 'mission-impossible', 'Films d’espionnage'),
        p('james-bond', 'oss-117', 'Espions de cinéma'),
        p('walking-dead', 'last-of-us', 'Séries post-apocalyptiques'),
        p('scream', 'halloween', 'Films d’horreur'),
        p('emily-in-paris', 'diable-prada', 'Comédies glamour'),
      ],
    }),

    universe({
      id: 'harry-potter',
      name: 'Harry Potter',
      precise: true,
      words: {
        ron: w('Ron Weasley', 'Élève de Gryffondor, sixième enfant d’une famille de sorciers aux cheveux roux.'),
        ginny: w('Ginny Weasley', 'Élève de Gryffondor, benjamine d’une famille de sorciers, joueuse de Quidditch.'),
        neville: w('Neville Londubat', 'Élève de Gryffondor timide et maladroit, doué en botanique, élevé par sa grand-mère.'),
        hermione: w('Hermione Granger', 'Élève de Gryffondor née de parents moldus, brillante et passionnée de livres.'),
        mcgonagall: w('Minerva McGonagall', 'Professeure de métamorphose et directrice de Gryffondor, capable de devenir un chat.'),
        rogue: w('Severus Rogue', 'Professeur de potions aux cheveux noirs et gras, directeur de la maison Serpentard.'),
        dumbledore: w('Albus Dumbledore', 'Directeur de Poudlard à longue barbe blanche, considéré comme un très grand sorcier.'),
        voldemort: w('Voldemort', 'Mage noir au visage sans nez qui cherche à vaincre la mort, chef des Mangemorts.'),
        bellatrix: w('Bellatrix Lestrange', 'Mangemort fanatique aux cheveux noirs en bataille, évadée de la prison des sorciers.'),
        gryffondor: w('Gryffondor', 'Maison de Poudlard symbolisée par un lion, qui valorise le courage.'),
        serdaigle: w('Serdaigle', 'Maison de Poudlard symbolisée par un aigle, qui valorise l’intelligence.'),
        poufsouffle: w('Poufsouffle', 'Maison de Poudlard symbolisée par un blaireau, qui valorise la loyauté.'),
        expelliarmus: w('Expelliarmus', 'Sortilège de désarmement qui fait sauter la baguette des mains de l’adversaire.'),
        stupefix: w('Stupéfix', 'Sortilège de duel qui assomme la cible et la laisse inconsciente.'),
        accio: w('Accio', 'Sortilège d’attraction qui fait venir à soi l’objet que l’on nomme.'),
        wingardium: w('Wingardium Leviosa', 'Sortilège de lévitation appris en première année, qui fait flotter les objets.'),
        'avada-kedavra': w('Avada Kedavra', 'Sortilège impardonnable qui tue instantanément, dans un éclair vert.'),
        endoloris: w('Endoloris', 'Sortilège impardonnable qui inflige une douleur insupportable à la victime.'),
        cape: w('Cape d’invisibilité', 'Étoffe magique héritée de son père par Harry, qui cache entièrement qui s’en couvre.'),
        carte: w('Carte du Maraudeur', 'Parchemin magique qui montre Poudlard et la position de chaque personne.'),
        retourneur: w('Retourneur de temps', 'Sablier magique porté en pendentif, qui permet de remonter de quelques heures.'),
        pensine: w('Pensine', 'Bassine de pierre où l’on verse des souvenirs pour les revivre de l’intérieur.'),
        hippogriffe: w('Hippogriffe', 'Créature mi-aigle mi-cheval qu’il faut saluer d’une révérence avant d’approcher.'),
        sombral: w('Sombral', 'Cheval ailé squelettique, visible seulement par ceux qui ont vu la mort.'),
        fumseck: w('Fumseck', 'Phénix de Dumbledore, dont les larmes guérissent et qui renaît de ses cendres.'),
        hedwige: w('Hedwige', 'Chouette des neiges offerte à Harry par Hagrid pour son onzième anniversaire.'),
        'pre-au-lard': w('Pré-au-Lard', 'Village de sorciers voisin de Poudlard, connu pour ses boutiques et ses pubs.'),
        'chemin-de-traverse': w('Chemin de Traverse', 'Rue commerçante cachée de Londres où les sorciers achètent leurs fournitures.'),
        gringotts: w('Gringotts', 'Banque des sorciers tenue par des gobelins, avec des coffres gardés sous terre.'),
        azkaban: w('Azkaban', 'Prison des sorciers bâtie sur une île de la mer du Nord, gardée par les Détraqueurs.'),
      },
      pairs: [
        p('ron', 'neville', 'Élèves et professeurs'),
        p('ron', 'ginny', 'Personnages'),
        p('hermione', 'ginny', 'Personnages'),
        p('rogue', 'mcgonagall', 'Élèves et professeurs'),
        p('mcgonagall', 'dumbledore', 'Personnages'),
        p('voldemort', 'bellatrix', 'Sorciers et sorcières'),
        p('gryffondor', 'serdaigle', 'Vie à l’école'),
        p('serdaigle', 'poufsouffle', 'Vie à l’école'),
        p('expelliarmus', 'stupefix', 'Sortilèges et potions'),
        p('expelliarmus', 'accio', 'Formules magiques'),
        p('accio', 'wingardium', 'Formules magiques'),
        p('avada-kedavra', 'endoloris', 'Sortilèges et potions'),
        p('cape', 'carte', 'Objets magiques'),
        p('retourneur', 'pensine', 'Objets magiques'),
        p('hippogriffe', 'sombral', 'Créatures'),
        p('hippogriffe', 'fumseck', 'Créatures magiques'),
        p('fumseck', 'hedwige', 'Animaux'),
        p('pre-au-lard', 'chemin-de-traverse', 'Lieux'),
        p('chemin-de-traverse', 'gringotts', 'Lieux du monde magique'),
        p('gringotts', 'azkaban', 'Lieux'),
      ],
    }),

    universe({
      id: 'star-wars',
      name: 'Star Wars',
      precise: true,
      words: {
        luke: w('Luke Skywalker', 'Jeune fermier de Tatooine qui devient chevalier Jedi et affronte l’Empire.'),
        anakin: w('Anakin Skywalker', 'Enfant esclave de Tatooine formé comme Jedi, présenté comme l’Élu d’une prophétie.'),
        rey: w('Rey', 'Ferrailleuse orpheline de Jakku qui découvre qu’elle est sensible à la Force.'),
        'han-solo': w('Han Solo', 'Contrebandier au blaster facile, capitaine du Faucon Millenium avec Chewbacca.'),
        lando: w('Lando Calrissian', 'Joueur charmeur et ancien contrebandier, devenu administrateur de la Cité des nuages.'),
        leia: w('Leia Organa', 'Princesse d’Alderaan et meneuse de la rébellion, célèbre pour sa coiffure en macarons.'),
        padme: w('Padmé Amidala', 'Jeune reine élue de Naboo, devenue ensuite sénatrice de la République.'),
        yoda: w('Yoda', 'Maître Jedi de petite taille à la peau verte, qui parle en inversant ses phrases.'),
        'obi-wan': w('Obi-Wan Kenobi', 'Maître Jedi barbu exilé sur Tatooine, où il se fait appeler Ben.'),
        'dark-vador': w('Dark Vador', 'Seigneur Sith en armure noire, à la respiration mécanique, bras droit de l’Empereur.'),
        'kylo-ren': w('Kylo Ren', 'Guerrier masqué du Premier Ordre, au sabre laser rouge à garde croisée.'),
        'dark-maul': w('Dark Maul', 'Apprenti Sith au visage tatoué de rouge et de noir, armé d’un sabre double.'),
        wookiee: w('Wookiee', 'Espèce de grands humanoïdes velus originaires de Kashyyyk, comme Chewbacca.'),
        ewok: w('Ewok', 'Espèce de petites créatures poilues qui vivent dans les arbres de la lune d’Endor.'),
        stormtrooper: w('Stormtrooper', 'Fantassin de l’Empire en armure blanche intégrale, réputé pour mal viser.'),
        'soldat-clone': w('Soldat clone', 'Fantassin de la République produit en série sur Kamino, à partir de Jango Fett.'),
        'sabre-laser': w('Sabre laser', 'Arme à lame d’énergie, portée par les Jedi comme par les Sith.'),
        blaster: w('Blaster', 'Pistolet ou fusil qui tire des décharges d’énergie, arme courante de la galaxie.'),
        force: w('La Force', 'Champ d’énergie mystique qui relie tous les êtres vivants et donne des pouvoirs.'),
        'cote-obscur': w('Côté obscur', 'Voie nourrie par la colère, la peur et la haine, suivie par les Sith.'),
        faucon: w('Faucon Millenium', 'Cargo léger rapide et rafistolé, piloté par Han Solo et Chewbacca.'),
        'x-wing': w('X-wing', 'Chasseur de l’Alliance rebelle aux ailes en croix, piloté notamment par Luke.'),
        'etoile-mort': w('Étoile de la Mort', 'Station spatiale de l’Empire grande comme une lune, capable de détruire une planète.'),
        destroyer: w('Destroyer stellaire', 'Immense vaisseau de guerre triangulaire de l’Empire, gris et hérissé de canons.'),
        empire: w('Empire galactique', 'Régime dictatorial dirigé par l’Empereur Palpatine, qui domine la galaxie.'),
        'premier-ordre': w('Premier Ordre', 'Régime militaire issu des vestiges impériaux, mené par Snoke puis Kylo Ren.'),
        tatooine: w('Tatooine', 'Planète désertique aux deux soleils, repaire de contrebandiers et de Jawas.'),
        jakku: w('Jakku', 'Planète désertique jonchée d’épaves de vaisseaux, où vit une jeune ferrailleuse.'),
        hoth: w('Hoth', 'Planète glacée où l’Alliance rebelle installe une base secrète, attaquée par l’Empire.'),
        endor: w('Endor', 'Lune forestière où l’Alliance rebelle affronte l’Empire lors d’une bataille décisive.'),
      },
      pairs: [
        p('luke', 'anakin', 'Personnages'),
        p('luke', 'rey', 'Héros et héroïnes'),
        p('anakin', 'kylo-ren', 'Personnages'),
        p('han-solo', 'lando', 'Personnages'),
        p('leia', 'padme', 'Personnages'),
        p('leia', 'rey', 'Héros et héroïnes'),
        p('yoda', 'obi-wan', 'Personnages'),
        p('dark-vador', 'kylo-ren', 'Méchants'),
        p('dark-vador', 'dark-maul', 'Méchants'),
        p('wookiee', 'ewok', 'Peuples et créatures'),
        p('stormtrooper', 'soldat-clone', 'Combattants'),
        p('sabre-laser', 'blaster', 'Armes et équipement'),
        p('force', 'cote-obscur', 'Notions et pouvoirs'),
        p('faucon', 'x-wing', 'Vaisseaux'),
        p('etoile-mort', 'destroyer', 'Machines de guerre'),
        p('empire', 'premier-ordre', 'Factions'),
        p('tatooine', 'jakku', 'Planètes'),
        p('tatooine', 'hoth', 'Planètes'),
        p('hoth', 'endor', 'Lieux'),
      ],
    }),

    universe({
      id: 'marvel',
      name: 'Marvel (films)',
      precise: true,
      words: {
        'iron-man': w('Iron Man', 'Tony Stark, industriel milliardaire et inventeur qui combat dans une armure high-tech.'),
        'doctor-strange': w('Doctor Strange', 'Stephen Strange, ancien neurochirurgien devenu Sorcier suprême après un accident.'),
        'black-panther': w('Black Panther', 'T’Challa, roi du Wakanda, qui combat dans une combinaison en vibranium.'),
        'captain-america': w('Captain America', 'Steve Rogers, soldat transformé par un sérum, resté des décennies pris dans la glace.'),
        'captain-marvel': w('Captain Marvel', 'Carol Danvers, pilote de l’US Air Force dotée de pouvoirs cosmiques après une explosion.'),
        thor: w('Thor', 'Dieu du tonnerre venu d’Asgard, fils d’Odin, doté d’une force immense.'),
        hulk: w('Hulk', 'Bruce Banner, scientifique qui se change en géant vert sous l’effet de la colère.'),
        'black-widow': w('Black Widow', 'Natasha Romanoff, espionne russe formée dans la Chambre rouge, devenue agent du SHIELD.'),
        gamora: w('Gamora', 'Guerrière à la peau verte, fille adoptive de Thanos, entraînée pour tuer.'),
        wanda: w('Wanda Maximoff', 'Sokovienne aux pouvoirs de télékinésie et de magie du chaos, liée à la Vision.'),
        'spider-man': w('Spider-Man', 'Peter Parker, adolescent new-yorkais mordu par une araignée, qui tisse des toiles.'),
        'ant-man': w('Ant-Man', 'Scott Lang, ancien cambrioleur qui porte une combinaison capable de rétrécir.'),
        thanos: w('Thanos', 'Titan à la peau violette qui veut anéantir la moitié de la vie de l’univers.'),
        ultron: w('Ultron', 'Intelligence artificielle créée par Tony Stark et Bruce Banner, qui veut éradiquer l’humanité.'),
        loki: w('Loki', 'Dieu de la malice adopté par Odin, maître des illusions et de la tromperie.'),
        hela: w('Hela', 'Déesse de la mort, fille aînée d’Odin, qui revient réclamer le trône d’Asgard.'),
        killmonger: w('Killmonger', 'Erik Stevens, ancien soldat d’élite qui revendique le trône du Wakanda.'),
        mjolnir: w('Mjolnir', 'Marteau enchanté forgé dans l’uru, que seuls les êtres dignes peuvent soulever.'),
        stormbreaker: w('Stormbreaker', 'Grande hache enchantée forgée à Nidavellir, capable d’invoquer le Bifrost.'),
        bouclier: w('Bouclier de Captain America', 'Disque rond en vibranium aux couleurs du drapeau américain, orné d’une étoile.'),
        'pierre-temps': w('Pierre du Temps', 'Gemme verte d’Infinité cachée dans l’Œil d’Agamotto, gardée par les sorciers.'),
        'pierre-esprit': w('Pierre de l’Esprit', 'Gemme jaune d’Infinité logée d’abord dans un sceptre, puis dans le front de la Vision.'),
        tesseract: w('Tesseract', 'Cube bleu lumineux abritant une gemme d’Infinité, convoité par Loki et HYDRA.'),
        avengers: w('Avengers', 'Équipe de super-héros réunie par Nick Fury pour faire face aux menaces mondiales.'),
        gardiens: w('Gardiens de la Galaxie', 'Équipe de hors-la-loi de l’espace menée par Star-Lord, avec un raton laveur et un arbre.'),
        wakanda: w('Wakanda', 'Royaume africain secret, technologiquement avancé grâce à ses réserves de vibranium.'),
        asgard: w('Asgard', 'Royaume céleste des dieux nordiques, relié aux autres mondes par le Bifrost.'),
      },
      pairs: [
        p('iron-man', 'doctor-strange', 'Super-héros'),
        p('iron-man', 'black-panther', 'Super-héros'),
        p('captain-america', 'captain-marvel', 'Super-héros'),
        p('thor', 'hulk', 'Super-héros'),
        p('thor', 'captain-marvel', 'Super-héros'),
        p('black-widow', 'gamora', 'Personnages'),
        p('black-widow', 'wanda', 'Super-héros'),
        p('wanda', 'doctor-strange', 'Personnages'),
        p('spider-man', 'ant-man', 'Super-héros'),
        p('thanos', 'ultron', 'Méchants'),
        p('loki', 'hela', 'Méchants'),
        p('loki', 'killmonger', 'Personnages'),
        p('mjolnir', 'stormbreaker', 'Objets et armes'),
        p('mjolnir', 'bouclier', 'Objets et armes'),
        p('pierre-temps', 'pierre-esprit', 'Objets de pouvoir'),
        p('pierre-esprit', 'tesseract', 'Objets de pouvoir'),
        p('avengers', 'gardiens', 'Équipes et organisations'),
        p('wakanda', 'asgard', 'Lieux'),
      ],
    }),
  ],
});
