import { definePack } from './types';

export default definePack({
  id: 'films-series',
  name: 'Films & Séries',
  description: 'Sagas, sitcoms, blockbusters et séries à dévorer.',
  icon: 'clapperboard',
  pairs: [
    ['Harry Potter', 'Le Seigneur des anneaux'],
    ['Star Wars', 'Star Trek'],
    ['Titanic', 'Avatar'],
    ['Friends', 'How I Met Your Mother'],
    ['Game of Thrones', 'The Witcher'],
    ['Breaking Bad', 'Narcos'],
    ['La Casa de Papel', 'Prison Break'],
    ['Stranger Things', 'Wednesday'],
    ['Iron Man', 'Batman'],
    ['Spider-Man', 'Deadpool'],
    ['Avengers', 'Justice League'],
    ['Les Simpson', 'South Park'],
    ['Shrek', "L'Âge de glace"],
    ['Le Roi Lion', 'Le Livre de la jungle'],
    ['La Reine des neiges', 'Raiponce'],
    ['Toy Story', 'Monstres et Cie'],
    ['Jurassic Park', 'King Kong'],
    ['Matrix', 'Inception'],
    ['Fast & Furious', 'Taxi'],
    ['Les Bronzés', 'Camping'],
    ['Intouchables', "Bienvenue chez les Ch'tis"],
    ['Les Visiteurs', 'Kaamelott'],
    ['Sherlock', 'Lupin'],
    ['Squid Game', 'Alice in Borderland'],
    ['Pirates des Caraïbes', 'Indiana Jones'],
    ['James Bond', 'Mission Impossible'],
    ['Rocky', 'Karate Kid'],
    ['Retour vers le futur', 'Terminator'],
    ["Grey's Anatomy", 'Dr House'],
    ['The Walking Dead', 'The Last of Us'],
    ['Le Parrain', 'Scarface'],
    ['Scream', 'Halloween'],
    ['Plus belle la vie', 'Demain nous appartient'],
    ['Twilight', 'Hunger Games'],
    ['Dragons', 'Kung Fu Panda'],
    ['SOS Fantômes', 'Men in Black'],
    ['Emily in Paris', 'Gossip Girl'],
  ],
});
