import { definePack, pair } from './types';

export default definePack({
  id: 'films-series',
  name: 'Films & Séries',
  description: 'Sagas, sitcoms, blockbusters et séries à dévorer.',
  icon: 'clapperboard',
  pairs: [
    pair(
      'Sagas de fantasy',
      ['Harry Potter', 'Saga d’un jeune sorcier formé à l’école Poudlard, adaptée des romans de J.K. Rowling.'],
      ['Le Seigneur des anneaux', 'Trilogie de Peter Jackson adaptée de Tolkien, qui se déroule en Terre du Milieu.'],
    ),
    pair(
      'Science-fiction spatiale',
      ['Star Wars', 'Saga de George Lucas avec les Jedi, les sabres laser et l’Empire galactique.'],
      ['Star Trek', 'Saga de science-fiction qui suit l’équipage du vaisseau Enterprise.'],
    ),
    pair('Grandes superproductions',
      ['Titanic', 'Drame romantique sur le naufrage d’un paquebot en 1912, avec Leonardo DiCaprio.'],
      ['Avatar', 'Film de science-fiction sur la planète Pandora et son peuple à la peau bleue, les Na’vi.'],
    ),
    pair(
      'Sitcoms américaines cultes',
      ['Friends', 'Sitcom sur six amis new-yorkais qui se retrouvent au café Central Perk.'],
      ['How I Met Your Mother', 'Sitcom où Ted Mosby raconte à ses enfants comment il a connu leur mère.'],
    ),
    pair(
      'Séries de fantasy médiévale',
      ['Game of Thrones', 'Série de fantasy où de grandes familles se disputent le Trône de fer à Westeros.'],
      ['The Witcher', 'Série de fantasy où Geralt de Riv, chasseur de monstres, parcourt le Continent.'],
    ),
    pair(
      'Séries sur le trafic de drogue',
      ['Breaking Bad', 'Série où un professeur de chimie devient fabricant de méthamphétamine.'],
      ['Narcos', 'Série sur la traque du baron de la drogue Pablo Escobar en Colombie.'],
    ),
    pair(
      'Séries de plans millimétrés',
      ['La Casa de Papel', 'Série espagnole de braqueurs en combinaison rouge portant des masques de Dalí.'],
      ['Prison Break', 'Série où un ingénieur se fait incarcérer volontairement pour faire évader son frère.'],
    ),
    pair(
      'Séries fantastiques Netflix',
      ['Stranger Things', 'Série où des enfants des années 80 affrontent des créatures d’une dimension parallèle.'],
      ['Wednesday', 'Série où la fille de la famille Addams enquête au sein du pensionnat Nevermore.'],
    ),
    pair(
      'Super-héros de comics',
      ['Iron Man', 'Héros Marvel, génie milliardaire qui combat dans une armure high-tech.'],
      ['Batman', 'Justicier masqué de Gotham City, milliardaire sans superpouvoirs, héros de DC.'],
    ),
    pair(
      'Personnages Marvel',
      ['Spider-Man', 'Héros Marvel, jeune New-Yorkais mordu par une araignée radioactive.'],
      ['Deadpool', 'Antihéros Marvel mercenaire, bavard et irrévérencieux, qui brise le quatrième mur.'],
    ),
    pair(
      'Équipes de super-héros',
      ['Avengers', 'Équipe Marvel réunissant notamment Captain America, Thor, Hulk et Black Widow.'],
      ['Justice League', 'Équipe DC réunissant notamment Superman, Wonder Woman, Aquaman et Flash.'],
    ),
    pair(
      'Dessins animés pour adultes',
      ['Les Simpson', 'Série animée sur une famille jaune de Springfield, avec Homer, Marge et Bart.'],
      ['South Park', 'Série animée satirique sur quatre écoliers d’une petite ville du Colorado.'],
    ),
    pair(
      'Animation des années 2000',
      ['Shrek', 'Film d’animation DreamWorks sur un ogre vert accompagné d’un âne bavard.'],
      ["L'Âge de glace", 'Film d’animation où un mammouth, un paresseux et un tigre à dents de sabre font équipe.'],
    ),
    pair(
      'Classiques Disney animaliers',
      ['Le Roi Lion', 'Classique Disney où le jeune Simba doit reprendre le trône volé par son oncle Scar.'],
      ['Le Livre de la jungle', 'Classique Disney où Mowgli, enfant élevé par des loups, croise Baloo et Shere Khan.'],
    ),
    pair(
      'Princesses Disney modernes',
      ['La Reine des neiges', 'Film Disney où Elsa, dotée de pouvoirs glacés, s’enfuit du royaume d’Arendelle.'],
      ['Raiponce', 'Film Disney sur une princesse aux très longs cheveux, enfermée dans une tour.'],
    ),
    pair('Films d’animation cultes',
      ['Toy Story', 'Film Pixar où des jouets prennent vie, avec le cow-boy Woody et Buzz l’Éclair.'],
      ['Monstres et Cie', 'Film Pixar où Sulli et Bob effraient les enfants pour produire de l’énergie.'],
    ),
    pair(
      'Créatures géantes au cinéma',
      ['Jurassic Park', 'Film de Spielberg sur un parc d’attractions peuplé de dinosaures clonés.'],
      ['King Kong', 'Film sur un gorille géant capturé sur une île et exhibé à New York.'],
    ),
    pair(
      'Films de SF cérébraux',
      ['Matrix', 'Film de science-fiction où Neo découvre que le monde est une simulation informatique.'],
      ['Inception', 'Film de Christopher Nolan où des voleurs s’infiltrent dans les rêves de leurs cibles.'],
    ),
    pair(
      'Courses-poursuites au cinéma',
      ['Fast & Furious', 'Saga d’action américaine autour de courses de voitures, avec Vin Diesel.'],
      ['Taxi', 'Comédie d’action produite par Luc Besson, avec un chauffeur marseillais ultrarapide.'],
    ),
    pair('Comédies françaises populaires',
      ['Les Bronzés', 'Comédie culte de la troupe du Splendid sur un groupe de vacanciers en club.'],
      ['Camping', 'Comédie avec Franck Dubosc en vacancier maladroit, fidèle des Flots Bleus.'],
    ),
    pair(
      'Comédies françaises à succès',
      ['Intouchables', 'Comédie sur l’amitié entre un riche tétraplégique et son auxiliaire de vie, avec Omar Sy.'],
      ["Bienvenue chez les Ch'tis", 'Comédie de Dany Boon où un directeur de poste du Sud est muté dans le Nord.'],
    ),
    pair('Comédies françaises cultes',
      ['Les Visiteurs', 'Comédie où un chevalier du Moyen Âge et son écuyer atterrissent à notre époque.'],
      ['Kaamelott', 'Série humoristique d’Alexandre Astier sur le roi Arthur et ses chevaliers.'],
    ),
    pair(
      'Héros de romans revisités',
      ['Sherlock', 'Série britannique où un détective génial mène l’enquête dans le Londres actuel.'],
      ['Lupin', 'Série Netflix avec Omar Sy en cambrioleur inspiré des romans de Maurice Leblanc.'],
    ),
    pair(
      'Séries asiatiques de survie',
      ['Squid Game', 'Série coréenne où des endettés s’affrontent dans des jeux d’enfants mortels.'],
      ['Alice in Borderland', 'Série japonaise où des joueurs piégés dans un Tokyo désert affrontent des épreuves.'],
    ),
    pair(
      'Sagas d’aventure et de trésors',
      ['Pirates des Caraïbes', 'Saga Disney avec Johnny Depp dans le rôle de l’excentrique capitaine Jack Sparrow.'],
      ['Indiana Jones', 'Saga d’aventures avec Harrison Ford en archéologue au fouet et au chapeau.'],
    ),
    pair(
      'Films d’espionnage',
      ['James Bond', 'Espion britannique de fiction, l’agent 007 au service secret de Sa Majesté.'],
      ['Mission Impossible', 'Saga d’espionnage avec Tom Cruise en agent Ethan Hunt, adepte des cascades.'],
    ),
    pair(
      'Films de sport et de combat',
      ['Rocky', 'Film avec Sylvester Stallone en boxeur de Philadelphie qui tente sa chance.'],
      ['Karate Kid', 'Film où un adolescent apprend les arts martiaux auprès de M. Miyagi.'],
    ),
    pair(
      'Films cultes des années 80',
      ['Retour vers le futur', 'Film où Marty McFly voyage dans le temps à bord d’une DeLorean.'],
      ['Terminator', 'Film où un cyborg venu de l’avenir traque une femme, avec Arnold Schwarzenegger.'],
    ),
    pair(
      'Séries médicales',
      ["Grey's Anatomy", 'Série médicale qui suit des internes en chirurgie dans un hôpital de Seattle.'],
      ['Dr House', 'Série médicale sur un diagnosticien brillant, boiteux et misanthrope.'],
    ),
    pair(
      'Survie post-apocalyptique',
      ['The Walking Dead', 'Série où un shérif et d’autres survivants affrontent une apocalypse zombie.'],
      ['The Last of Us', 'Série adaptée d’un jeu vidéo où Joel escorte l’adolescente Ellie dans un monde ravagé.'],
    ),
    pair(
      'Films cultes de gangsters',
      ['Le Parrain', 'Film de Francis Ford Coppola sur la famille mafieuse Corleone, avec Marlon Brando.'],
      ['Scarface', 'Film de Brian De Palma sur l’ascension d’un trafiquant cubain à Miami.'],
    ),
    pair(
      'Slashers et tueurs masqués',
      ['Scream', 'Film d’horreur où un tueur au masque de fantôme harcèle des lycéens au téléphone.'],
      ['Halloween', 'Film d’horreur de John Carpenter où Michael Myers traque des baby-sitters.'],
    ),
    pair('Séries télé françaises',
      ['Plus belle la vie', 'Feuilleton quotidien culte situé dans le quartier du Mistral, à Marseille.'],
      ['Demain nous appartient', 'Feuilleton quotidien de TF1 dont l’intrigue se déroule à Sète.'],
    ),
    pair(
      'Sagas young adult',
      ['Twilight', 'Saga romantique entre une lycéenne et un vampire, adaptée des romans de Stephenie Meyer.'],
      ['Hunger Games', 'Saga où Katniss Everdeen participe à des jeux télévisés mortels à Panem.'],
    ),
    pair(
      'Animation DreamWorks',
      ['Dragons', 'Film DreamWorks où un jeune Viking se lie d’amitié avec Krokmou.'],
      ['Kung Fu Panda', 'Film DreamWorks où Po, un ours maladroit et gourmand, devient maître des arts martiaux.'],
    ),
    pair(
      'Comédies fantastiques new-yorkaises',
      ['SOS Fantômes', 'Comédie fantastique où une équipe de scientifiques chasse les spectres à New York.'],
      ['Men in Black', 'Comédie où des agents en costume sombre surveillent les extraterrestres sur Terre.'],
    ),
    pair(
      'Séries mode et glamour',
      ['Emily in Paris', 'Série où une jeune Américaine travaille dans une agence de marketing parisienne.'],
      ['Gossip Girl', 'Série sur des ados de l’Upper East Side dont une blogueuse anonyme dévoile les secrets.'],
    ),
  ],
});
