import { definePack, pair } from './types';

export default definePack({
  id: 'football',
  name: 'Football',
  description: 'Légendes, clubs rivaux, stades mythiques et gestes techniques.',
  icon: 'volleyball',
  pairs: [
    pair(
      'Superstars du ballon rond',
      ['Messi', 'Attaquant argentin formé au FC Barcelone, champion du monde avec son pays en 2022.'],
      ['Ronaldo', 'Attaquant portugais surnommé CR7, passé notamment par Manchester United et le Real Madrid.'],
    ),
    pair(
      'Grands clubs français',
      ['PSG', 'Club de la capitale française, qui joue au Parc des Princes.'],
      ['Marseille', 'Club phocéen qui joue au stade Vélodrome, au bord de la Méditerranée.'],
    ),
    pair(
      'Buteurs de la nouvelle génération',
      ['Mbappé', 'Attaquant français ultra-rapide, champion du monde en 2018, passé ensuite au Real Madrid.'],
      ['Haaland', 'Buteur norvégien au physique imposant, passé par Dortmund avant Manchester City.'],
    ),
    pair(
      'Meneurs de jeu de légende',
      ['Zidane', 'Milieu offensif français champion du monde en 1998, devenu entraîneur du Real Madrid.'],
      ['Platini', 'Milieu offensif français des années 1980, triple Ballon d’Or, puis président de l’UEFA.'],
    ),
    pair('Grands clubs européens',
      ['Real Madrid', 'Club de la capitale espagnole, recordman des victoires en Ligue des champions.'],
      ['FC Barcelone', 'Club catalan au maillot bleu et grenat, qui joue au Camp Nou.'],
    ),
    pair('Grands tournois de football',
      ['Ligue des champions', 'Compétition de clubs la plus prestigieuse du continent, à l’hymne célèbre.'],
      ['Ligue Europa', 'Compétition de clubs de l’UEFA dont les matchs se disputent généralement le jeudi soir.'],
    ),
    pair('Grands tournois de football',
      ['Coupe du monde', 'Tournoi mondial des sélections nationales, organisé tous les quatre ans par la FIFA.'],
      ['Euro', 'Championnat d’Europe des nations, organisé tous les quatre ans par l’UEFA.'],
    ),
    pair('Décisions de l’arbitre',
      ['Carton jaune', 'Avertissement officiel adressé par l’arbitre à un joueur coupable d’une faute.'],
      ['Carton rouge', 'Sanction de l’arbitre qui exclut aussitôt un joueur pour le reste du match.'],
    ),
    pair(
      'Phases arrêtées',
      ['Penalty', 'Tir au but depuis le point situé à onze mètres, face au seul gardien.'],
      ['Coup franc', 'Tir accordé après une faute, frappé ballon arrêté, souvent face à un mur de joueurs.'],
    ),
    pair(
      'Postes à l’arrière',
      ['Gardien de but', 'Seul joueur autorisé à toucher le ballon de la main, dans sa surface de réparation.'],
      ['Défenseur', 'Joueur placé en retrait, chargé de contrer les attaquants adverses.'],
    ),
    pair('Acteurs d’un match',
      ['Arbitre', 'Officiel au sifflet qui dirige la rencontre et fait respecter les règles du jeu.'],
      ['Juge de touche', 'Assistant qui longe la ligne de côté, drapeau en main, pour signaler hors-jeu et sorties.'],
    ),
    pair('Clubs français historiques',
      ['Lyon', 'Club rhodanien, sacré champion de France sept fois de suite dans les années 2000.'],
      ['Saint-Étienne', 'Club du Forez surnommé les Verts, grande équipe française des années 1970.'],
    ),
    pair('Clubs français historiques',
      ['Lens', 'Club artésien aux couleurs sang et or, porté par le public fervent de Bollaert.'],
      ['Lille', 'Club surnommé les Dogues, qui joue au stade Pierre-Mauroy.'],
    ),
    pair(
      'Grands clubs anglais',
      ['Manchester United', 'Club anglais surnommé les Red Devils, qui joue à Old Trafford.'],
      ['Manchester City', 'Club anglais au maillot bleu ciel surnommé les Citizens, qui joue à l’Etihad Stadium.'],
    ),
    pair(
      'Clubs historiques anglais',
      ['Liverpool', 'Club anglais au maillot rouge, qui joue à Anfield au son de You’ll Never Walk Alone.'],
      ['Chelsea', 'Club londonien au maillot bleu, qui joue à Stamford Bridge.'],
    ),
    pair('Grands clubs européens',
      ['Bayern Munich', 'Club bavarois, le plus titré d’Allemagne, qui joue à l’Allianz Arena.'],
      ['Borussia Dortmund', 'Club de la Ruhr au maillot jaune et noir, célèbre pour son Mur jaune de supporters.'],
    ),
    pair(
      'Grands clubs italiens',
      ['Juventus', 'Club turinois au maillot rayé noir et blanc, surnommé la Vieille Dame.'],
      ['AC Milan', 'Club lombard au maillot rayé rouge et noir, qui partage San Siro avec l’Inter.'],
    ),
    pair(
      'Grands attaquants des Bleus',
      ['Thierry Henry', 'Attaquant français rapide et élégant, champion du monde en 1998 et d’Europe en 2000.'],
      ['Olivier Giroud', 'Avant-centre français au jeu de tête redoutable, champion du monde en 2018.'],
    ),
    pair(
      'Attaquants de l’équipe de France',
      ['Griezmann', 'Attaquant français gaucher, figure de l’Atlético de Madrid et champion du monde en 2018.'],
      ['Dembélé', 'Ailier français ambidextre et très rapide, sacré en Ligue des champions avec le PSG.'],
    ),
    pair(
      'Champions devenus entraîneurs',
      ['Didier Deschamps', 'Ancien milieu défensif, sélectionneur des Bleus lors du sacre mondial de 2018.'],
      ['Laurent Blanc', 'Ancien défenseur central surnommé le Président, devenu entraîneur du PSG.'],
    ),
    pair(
      'Légendes sud-américaines',
      ['Pelé', 'Légende brésilienne surnommée le Roi, seul joueur triple champion du monde.'],
      ['Maradona', 'Génie argentin, champion du monde en 1986, auteur de la célèbre main de Dieu.'],
    ),
    pair(
      'Stars brésiliennes des années 2000',
      ['Ronaldinho', 'Meneur brésilien au sourire célèbre, magicien du dribble au FC Barcelone.'],
      ['Kaká', 'Meneur de jeu brésilien élégant, réputé pour ses grandes chevauchées balle au pied.'],
    ),
    pair(
      'Infractions sifflées',
      ['Hors-jeu', 'Position irrégulière d’un attaquant trop avancé par rapport à la défense lors d’une passe.'],
      ['Main', 'Faute d’un joueur de champ qui touche le ballon avec le bras.'],
    ),
    pair(
      'Sorties de balle',
      ['Corner', 'Coup de pied tiré depuis un coin du terrain, après une sortie derrière la ligne de but.'],
      ['Touche', 'Remise en jeu à deux mains depuis la ligne de côté, quand le ballon sort latéralement.'],
    ),
    pair(
      'Dribbles spectaculaires',
      ['Roulette', 'Dribble où le joueur pivote sur lui-même en faisant rouler le ballon sous ses semelles.'],
      ['Petit pont', 'Dribble qui consiste à faire passer le ballon entre les jambes d’un adversaire.'],
    ),
    pair(
      'Trophées individuels',
      ["Ballon d'Or", 'Trophée créé par France Football, qui distingue chaque année le meilleur joueur.'],
      ["Soulier d'or", 'Trophée remis au meilleur buteur, notamment parmi les championnats européens.'],
    ),
    pair('Grands stades français',
      ['Stade de France', 'Plus grand stade du pays, situé à Saint-Denis et inauguré pour le Mondial 1998.'],
      ['Parc des Princes', 'Enceinte parisienne du 16e arrondissement, antre historique du PSG.'],
    ),
    pair('Grands stades français',
      ['Vélodrome', 'Stade de l’Olympique de Marseille, célèbre pour l’ambiance de ses virages.'],
      ['Geoffroy-Guichard', 'Stade de l’AS Saint-Étienne, surnommé le Chaudron pour son ambiance bouillante.'],
    ),
    pair(
      'Championnats européens majeurs',
      ['Premier League', 'Championnat d’Angleterre de première division, réputé le plus riche du monde.'],
      ['Liga', 'Championnat espagnol de l’élite, longtemps dominé par Madrid et Barcelone.'],
    ),
    pair('Joueurs de l’équipe de France',
      ['Hugo Lloris', 'Gardien français, capitaine des Bleus champions du monde en 2018, passé par Tottenham.'],
      ['Mike Maignan', 'Gardien français formé au PSG, champion d’Italie avec l’AC Milan en 2022.'],
    ),
    pair(
      'Frappes acrobatiques',
      ['Volée', 'Frappe qui reprend le ballon dans les airs, avant qu’il ne touche le sol.'],
      ['Retourné', 'Geste spectaculaire où le joueur, dos au but, frappe par-dessus sa tête en basculant.'],
    ),
    pair(
      'Ambiance des tribunes',
      ['Supporters', 'Personnes qui encouragent leur équipe, au stade comme devant leur écran.'],
      ['Ultras', 'Groupes de fans très organisés qui animent les virages avec chants, tifos et fumigènes.'],
    ),
    pair(
      'Équipement du footballeur',
      ['Crampons', 'Chaussures de foot munies de pointes sous la semelle pour ne pas glisser sur l’herbe.'],
      ['Protège-tibias', 'Plaques rigides portées sous les chaussettes pour amortir les coups sur les jambes.'],
    ),
    pair(
      'Avant-centres charismatiques',
      ['Zlatan', 'Attaquant suédois au charisme légendaire, célèbre pour ses buts acrobatiques.'],
      ['Cavani', 'Buteur uruguayen surnommé El Matador, réputé pour son pressing et ses appels.'],
    ),
    pair(
      'Milieux de terrain français',
      ['Kanté', 'Milieu récupérateur français infatigable, réputé pour sa discrétion et son sourire.'],
      ['Pogba', 'Milieu français technique au grand gabarit, buteur en finale de la Coupe du monde 2018.'],
    ),
    pair(
      'Clubs méditerranéens',
      ['Monaco', 'Club de la Principauté, qui joue au stade Louis-II.'],
      ['Nice', 'Club azuréen surnommé le Gym, qui joue à l’Allianz Riviera.'],
    ),
    pair(
      'Dribbleurs brésiliens',
      ['Neymar', 'Attaquant brésilien virtuose, passé par Santos, le FC Barcelone et le PSG.'],
      ['Vinícius Júnior', 'Ailier brésilien explosif formé à Flamengo, devenu une star du Real Madrid.'],
    ),
  ],
});
