import { definePack } from './types';

export default definePack({
  id: 'football',
  name: 'Football',
  description: 'Légendes, clubs rivaux, stades mythiques et gestes techniques.',
  icon: 'volleyball',
  pairs: [
    ['Messi', 'Ronaldo'],
    ['PSG', 'Marseille'],
    ['Mbappé', 'Haaland'],
    ['Zidane', 'Platini'],
    ['Real Madrid', 'FC Barcelone'],
    ['Ligue des champions', 'Ligue Europa'],
    ['Coupe du monde', 'Euro'],
    ['Carton jaune', 'Carton rouge'],
    ['Penalty', 'Coup franc'],
    ['Gardien de but', 'Défenseur'],
    ['Arbitre', 'Juge de touche'],
    ['Lyon', 'Saint-Étienne'],
    ['Lens', 'Lille'],
    ['Manchester United', 'Manchester City'],
    ['Liverpool', 'Chelsea'],
    ['Bayern Munich', 'Borussia Dortmund'],
    ['Juventus', 'AC Milan'],
    ['Thierry Henry', 'Olivier Giroud'],
    ['Griezmann', 'Dembélé'],
    ['Didier Deschamps', 'Laurent Blanc'],
    ['Pelé', 'Maradona'],
    ['Ronaldinho', 'Kaká'],
    ['Hors-jeu', 'Main'],
    ['Corner', 'Touche'],
    ['Roulette', 'Petit pont'],
    ["Ballon d'Or", "Soulier d'or"],
    ['Stade de France', 'Parc des Princes'],
    ['Vélodrome', 'Geoffroy-Guichard'],
    ['Premier League', 'Liga'],
    ['Hugo Lloris', 'Mike Maignan'],
    ['Volée', 'Retourné'],
    ['Supporters', 'Ultras'],
    ['Crampons', 'Protège-tibias'],
    ['Zlatan', 'Cavani'],
    ['Kanté', 'Pogba'],
    ['Monaco', 'Nice'],
    ['Neymar', 'Vinícius Júnior'],
  ],
});
