import { definePack } from './types';

export default definePack({
  id: 'jeux-video',
  name: 'Jeux vidéo',
  description: 'Consoles, héros pixelisés et classiques du multijoueur.',
  icon: 'gamepad-2',
  pairs: [
    ['Fortnite', 'PUBG'],
    ['Minecraft', 'Terraria'],
    ['Mario', 'Sonic'],
    ['Zelda', 'Skyrim'],
    ['FIFA', 'PES'],
    ['Call of Duty', 'Battlefield'],
    ['GTA', 'Red Dead Redemption'],
    ['League of Legends', 'Dota 2'],
    ['Valorant', 'Counter-Strike'],
    ['Among Us', 'Fall Guys'],
    ['Tetris', 'Pac-Man'],
    ['Mario Kart', 'Crash Team Racing'],
    ['Les Sims', 'Animal Crossing'],
    ['Clash of Clans', 'Boom Beach'],
    ['Clash Royale', 'Brawl Stars'],
    ['Candy Crush', 'Angry Birds'],
    ['Rocket League', 'Trackmania'],
    ['Street Fighter', 'Tekken'],
    ['Super Smash Bros', 'Brawlhalla'],
    ["Assassin's Creed", 'Prince of Persia'],
    ['Resident Evil', 'Silent Hill'],
    ['World of Warcraft', 'Dofus'],
    ['Overwatch', 'Apex Legends'],
    ['Halo', 'Destiny'],
    ['PlayStation', 'Xbox'],
    ['Nintendo Switch', 'Steam Deck'],
    ['Game Boy', 'Nintendo DS'],
    ['Luigi', 'Wario'],
    ['Kirby', 'Yoshi'],
    ['Bowser', 'Donkey Kong'],
    ['Elden Ring', 'Dark Souls'],
    ['Uncharted', 'Tomb Raider'],
    ['Crash Bandicoot', 'Spyro'],
    ['Geometry Dash', 'Flappy Bird'],
    ['Portal', 'Half-Life'],
    ['Just Dance', 'Guitar Hero'],
  ],
});
