import { definePack, pair } from './types';

export default definePack({
  id: 'jeux-video',
  name: 'Jeux vidéo',
  description: 'Consoles, héros pixelisés et classiques du multijoueur.',
  icon: 'gamepad-2',
  pairs: [
    pair(
      'Jeux de survie en ligne',
      ['Fortnite', 'Jeu de tir coloré d’Epic Games où l’on peut construire des structures pour se protéger.'],
      ['PUBG', 'Jeu de tir sud-coréen réaliste, où l’on est parachuté sur une carte pour survivre.'],
    ),
    pair(
      'Bac à sable et artisanat',
      ['Minecraft', 'Jeu bac à sable en 3D fait de cubes, où l’on mine, fabrique et construit librement.'],
      ['Terraria', 'Jeu d’aventure en 2D vue de côté, où l’on creuse, fabrique des objets et combat des boss.'],
    ),
    pair('Héros de jeux vidéo cultes',
      ['Mario', 'Plombier moustachu à casquette rouge, mascotte historique de Nintendo.'],
      ['Sonic', 'Hérisson bleu ultra-rapide, mascotte historique de Sega.'],
    ),
    pair(
      'Grandes épopées de fantasy',
      ['Zelda', 'Saga de Nintendo où le héros Link explore le royaume d’Hyrule.'],
      ['Skyrim', 'Jeu de rôle en monde ouvert de Bethesda, dans une contrée nordique infestée de dragons.'],
    ),
    pair('Jeux de sport',
      ['FIFA', 'Série de football d’EA Sports sous licence officielle, rebaptisée EA Sports FC.'],
      ['PES', 'Série de jeux de football de Konami, rebaptisée eFootball par la suite.'],
    ),
    pair('Jeux de tir en ligne',
      ['Call of Duty', 'Saga de jeux de tir militaires d’Activision, très populaire en multijoueur.'],
      ['Battlefield', 'Série de tir militaire d’EA et DICE, réputée pour ses grandes batailles avec véhicules.'],
    ),
    pair(
      'Crime en monde ouvert',
      ['GTA', 'Série d’action en monde ouvert centrée sur le crime dans des villes modernes.'],
      ['Red Dead Redemption', 'Jeu d’action en monde ouvert où l’on incarne un hors-la-loi dans l’Ouest américain.'],
    ),
    pair('Jeux de stratégie en ligne',
      ['League of Legends', 'Jeu en ligne de Riot Games où deux équipes de cinq champions détruisent la base adverse.'],
      ['Dota 2', 'Jeu en ligne de Valve où deux équipes de cinq héros tentent de détruire l’Ancient adverse.'],
    ),
    pair('Jeux de tir compétitifs',
      ['Valorant', 'Jeu de tir tactique de Riot Games mêlant fusillades et agents aux pouvoirs spéciaux.'],
      ['Counter-Strike', 'Jeu de tir tactique de Valve opposant terroristes et antiterroristes autour d’une bombe.'],
    ),
    pair(
      'Jeux en ligne entre amis',
      ['Among Us', 'Jeu en ligne où de petits astronautes accomplissent des tâches et votent en réunion.'],
      ['Fall Guys', 'Jeu d’obstacles déjanté où des personnages en forme de haricot s’éliminent par manches.'],
    ),
    pair(
      'Classiques rétro indémodables',
      ['Tetris', 'Jeu de puzzle où l’on empile des pièces qui tombent pour compléter des lignes.'],
      ['Pac-Man', 'Jeu d’arcade où un rond jaune mange des pastilles dans un labyrinthe hanté de fantômes.'],
    ),
    pair(
      'Courses arcade délirantes',
      ['Mario Kart', 'Jeu de course de Nintendo où les héros du Royaume Champignon se lancent des objets.'],
      ['Crash Team Racing', 'Jeu de course né sur PlayStation, où un marsupial orange et ses amis se lancent des bonus.'],
    ),
    pair(
      'Vie paisible et décoration',
      ['Les Sims', 'Jeu où l’on crée des personnages et gère leur maison, leur travail et leurs relations.'],
      ['Animal Crossing', 'Jeu Nintendo où l’on aménage paisiblement un village peuplé d’animaux bavards.'],
    ),
    pair(
      'Stratégie de base sur mobile',
      ['Clash of Clans', 'Jeu de stratégie mobile où l’on bâtit un village fortifié et pille celui des autres.'],
      ['Boom Beach', 'Jeu de stratégie mobile où l’on libère un archipel tropical occupé par une armée ennemie.'],
    ),
    pair(
      'Duels en ligne sur mobile',
      ['Clash Royale', 'Jeu mobile de cartes où l’on déploie des troupes pour détruire les tours adverses.'],
      ['Brawl Stars', 'Jeu mobile d’action vu de dessus où des équipes de héros s’affrontent en courtes parties.'],
    ),
    pair(
      'Jeux mobiles addictifs',
      ['Candy Crush', 'Jeu de puzzle mobile où l’on aligne des bonbons de même couleur pour les faire éclater.'],
      ['Angry Birds', 'Jeu mobile où l’on catapulte des oiseaux en colère sur des cochons verts.'],
    ),
    pair(
      'Pilotage acrobatique',
      ['Rocket League', 'Jeu où des voitures à propulsion jouent au football avec un ballon géant.'],
      ['Trackmania', 'Jeu de course français contre la montre, sur des circuits remplis de loopings et de sauts.'],
    ),
    pair(
      'Duels de jeux de combat',
      ['Street Fighter', 'Série de jeux de combat de Capcom, célèbre pour Ryu, Ken et le Hadouken.'],
      ['Tekken', 'Série de jeux de combat en 3D de Bandai Namco, centrée sur la famille Mishima.'],
    ),
    pair(
      'Combats de plateformes multijoueur',
      ['Super Smash Bros', 'Jeu de combat de Nintendo où l’on tente d’éjecter ses adversaires hors de l’arène.'],
      ['Brawlhalla', 'Jeu de combat gratuit où des guerriers de toutes époques s’affrontent au Valhalla.'],
    ),
    pair(
      'Parkour et aventures historiques',
      ["Assassin's Creed", 'Saga d’action où l’on incarne des membres d’une confrérie secrète à travers l’Histoire.'],
      ['Prince of Persia', 'Saga de plateformes acrobatiques dans un Orient légendaire, entre pièges et sabres.'],
    ),
    pair(
      'Horreur et survie',
      ['Resident Evil', 'Série d’horreur de Capcom où l’on affronte des zombies nés d’armes biologiques.'],
      ['Silent Hill', 'Série d’horreur psychologique de Konami, dans une ville brumeuse remplie de monstres.'],
    ),
    pair(
      'Mondes persistants en ligne',
      ['World of Warcraft', 'Jeu de rôle en ligne massif de Blizzard, situé dans l’univers d’Azeroth.'],
      ['Dofus', 'Jeu de rôle en ligne français d’Ankama, aux combats tactiques au tour par tour.'],
    ),
    pair(
      'Jeux de tir à héros',
      ['Overwatch', 'Jeu de tir en équipe de Blizzard, où des héros aux pouvoirs variés s’affrontent.'],
      ['Apex Legends', 'Battle royale gratuit de Respawn, avec des personnages aux capacités uniques.'],
    ),
    pair(
      'Tir futuriste de science-fiction',
      ['Halo', 'Série de tir de science-fiction née sur Xbox, menée par le super-soldat Master Chief.'],
      ['Destiny', 'Jeu de tir en ligne de science-fiction où des Gardiens défendent la dernière cité humaine.'],
    ),
    pair('Matériel de jeu vidéo',
      ['PlayStation', 'Gamme de consoles de salon de Sony, apparue au milieu des années 1990.'],
      ['Xbox', 'Gamme de consoles de salon de Microsoft, lancée au début des années 2000.'],
    ),
    pair('Matériel de jeu vidéo',
      ['Nintendo Switch', 'Console hybride qui se joue sur la télé ou en portable, avec des manettes détachables.'],
      ['Steam Deck', 'Console portable de Valve qui fait tourner une bibliothèque de jeux PC.'],
    ),
    pair('Matériel de jeu vidéo',
      ['Game Boy', 'Console portable monochrome sortie à la fin des années 1980, célèbre pour Tetris.'],
      ['Nintendo DS', 'Console portable à double écran, dont un tactile utilisable au stylet.'],
    ),
    pair(
      'Personnages de Nintendo',
      ['Luigi', 'Frère de Mario, grand et vêtu de vert, souvent un peu peureux.'],
      ['Wario', 'Double maléfique de Mario, vêtu de jaune et violet, obsédé par l’argent.'],
    ),
    pair(
      'Héros mignons de Nintendo',
      ['Kirby', 'Petite boule rose qui aspire ses ennemis pour copier leurs pouvoirs.'],
      ['Yoshi', 'Dinosaure vert à longue langue, fidèle monture de Mario, qui pond des œufs.'],
    ),
    pair(
      'Colosses de Nintendo',
      ['Bowser', 'Roi des Koopas, tortue géante à carapace à piques qui enlève souvent la princesse Peach.'],
      ['Donkey Kong', 'Gorille à cravate rouge, amateur de bananes, qui vit sur une île de la jungle.'],
    ),
    pair(
      'Jeux d’action très exigeants',
      ['Elden Ring', 'Jeu d’action en monde ouvert, dont l’univers a été imaginé avec George R. R. Martin.'],
      ['Dark Souls', 'Jeu d’action très exigeant dans un royaume en déclin, où chaque mort a un prix.'],
    ),
    pair(
      'Chasseurs de trésors',
      ['Uncharted', 'Série d’aventure de Naughty Dog suivant le chasseur de trésors Nathan Drake.'],
      ['Tomb Raider', 'Série d’aventure menée par l’archéologue britannique Lara Croft.'],
    ),
    pair('Héros de plateforme des années 90',
      ['Crash Bandicoot', 'Marsupial orange casse-cou, héros de jeux de plateformes où l’on brise des caisses.'],
      ['Spyro', 'Petit dragon violet qui crache du feu et fonce tête baissée sur ses ennemis.'],
    ),
    pair(
      'Jeux mobiles de réflexes',
      ['Geometry Dash', 'Jeu de rythme où un cube saute par-dessus des obstacles en suivant la musique.'],
      ['Flappy Bird', 'Jeu mobile où l’on tapote l’écran pour faire voler un oiseau entre des tuyaux.'],
    ),
    pair(
      'Laboratoires et expériences',
      ['Portal', 'Jeu de réflexion à la première personne où l’on ouvre des passages entre deux surfaces.'],
      ['Half-Life', 'Jeu de tir où le scientifique Gordon Freeman affronte des créatures extraterrestres.'],
    ),
    pair(
      'Jeux musicaux en soirée',
      ['Just Dance', 'Jeu d’Ubisoft où l’on reproduit à l’écran des chorégraphies sur des tubes.'],
      ['Guitar Hero', 'Jeu de rythme où l’on joue des tubes de rock avec une manette en forme de guitare.'],
    ),
  ],
});
