import { definePack, p, universe, w } from './types';

export default definePack({
  id: 'jeux-video',
  name: 'Jeux vidéo',
  description: 'Consoles, héros pixelisés et classiques du multijoueur.',
  icon: 'gamepad-2',
  universes: [
    universe({
      id: 'general',
      name: 'Jeux vidéo',
      precise: false,
      words: {
        // Jeux de tir
        fortnite: w('Fortnite', 'Battle royale d’Epic Games où l’on peut bâtir des murs et des rampes pour se protéger.'),
        apex: w('Apex Legends', 'Battle royale gratuit de Respawn, où des escouades de personnages aux capacités uniques s’affrontent.'),
        overwatch: w('Overwatch', 'Jeu de tir en équipe de Blizzard, où des héros aux pouvoirs variés se disputent des objectifs.'),
        valorant: w('Valorant', 'Jeu de tir tactique de Riot Games où des agents aux pouvoirs spéciaux posent ou désamorcent le Spike.'),
        'counter-strike': w('Counter-Strike', 'Jeu de tir tactique de Valve opposant terroristes et antiterroristes autour d’une bombe.'),
        'call-of-duty': w('Call of Duty', 'Saga de jeux de tir militaires d’Activision, très populaire en multijoueur.'),
        battlefield: w('Battlefield', 'Série de tir militaire d’EA et DICE, réputée pour ses grandes batailles avec véhicules.'),
        // Création
        minecraft: w('Minecraft', 'Jeu bac à sable fait de cubes, où l’on mine, fabrique et construit librement.'),
        roblox: w('Roblox', 'Plateforme en ligne où les joueurs créent et partagent leurs propres jeux avec leur avatar.'),
        // Héros
        mario: w('Mario', 'Plombier moustachu à casquette rouge, mascotte historique de Nintendo.'),
        sonic: w('Sonic', 'Hérisson bleu ultra-rapide qui ramasse des anneaux, mascotte historique de Sega.'),
        link: w('Link', 'Jeune héros aux oreilles pointues et à la tunique verte, armé d’une épée et d’un bouclier.'),
        crash: w('Crash Bandicoot', 'Marsupial orange casse-cou, héros de jeux de plateformes où l’on brise des caisses.'),
        spyro: w('Spyro', 'Petit dragon violet qui crache du feu et fonce tête baissée sur ses ennemis.'),
        // Jeux de rôle et d'action
        skyrim: w('Skyrim', 'Jeu de rôle en monde ouvert de Bethesda, dans une contrée nordique infestée de dragons.'),
        witcher: w('The Witcher', 'Saga de jeux de rôle polonaise où le chasseur de monstres Geralt de Riv parcourt le monde.'),
        'elden-ring': w('Elden Ring', 'Jeu d’action en monde ouvert de FromSoftware, dont l’univers a été imaginé avec George R. R. Martin.'),
        'dark-souls': w('Dark Souls', 'Jeu d’action très exigeant de FromSoftware, dans un royaume en déclin où chaque mort a un prix.'),
        // Sport et monde ouvert
        fifa: w('FIFA', 'Série de football d’EA Sports sous licence officielle, rebaptisée EA Sports FC en 2023.'),
        pes: w('PES', 'Série de jeux de football de Konami, rebaptisée eFootball en 2021.'),
        gta: w('GTA', 'Série d’action en monde ouvert de Rockstar, centrée sur le crime dans des villes modernes.'),
        'red-dead': w('Red Dead Redemption', 'Jeu d’action en monde ouvert de Rockstar où l’on incarne un hors-la-loi dans l’Ouest américain.'),
        // Entre amis
        'among-us': w('Among Us', 'Jeu en ligne où de petits astronautes accomplissent des tâches et votent en réunion d’urgence.'),
        'fall-guys': w('Fall Guys', 'Jeu d’obstacles déjanté où des personnages en forme de haricot s’éliminent par manches.'),
        'mario-kart': w('Mario Kart', 'Jeu de course de Nintendo où les héros du Royaume Champignon se lancent des objets.'),
        'mario-party': w('Mario Party', 'Jeu de plateau de Nintendo entrecoupé de mini-jeux, où l’on collectionne des étoiles.'),
        smash: w('Super Smash Bros', 'Jeu de combat de Nintendo où l’on tente d’éjecter ses adversaires hors de l’arène.'),
        'just-dance': w('Just Dance', 'Jeu d’Ubisoft où l’on reproduit à l’écran des chorégraphies sur des tubes.'),
        'guitar-hero': w('Guitar Hero', 'Jeu de rythme où l’on joue des tubes de rock avec une manette en forme de guitare.'),
        // Réflexion et mobile
        tetris: w('Tetris', 'Jeu de puzzle soviétique où l’on empile des pièces qui tombent pour compléter des lignes.'),
        'pac-man': w('Pac-Man', 'Jeu d’arcade où un rond jaune mange des pastilles dans un labyrinthe hanté de fantômes.'),
        'candy-crush': w('Candy Crush', 'Jeu de puzzle mobile où l’on aligne des bonbons de même couleur pour les faire éclater.'),
        'angry-birds': w('Angry Birds', 'Jeu mobile où l’on catapulte des oiseaux en colère sur des cochons verts.'),
        'clash-of-clans': w('Clash of Clans', 'Jeu de stratégie mobile de Supercell où l’on bâtit un village fortifié et pille celui des autres.'),
        'clash-royale': w('Clash Royale', 'Jeu mobile de Supercell où l’on joue des cartes de troupes pour détruire les tours adverses.'),
        'brawl-stars': w('Brawl Stars', 'Jeu mobile de Supercell où des équipes de personnages s’affrontent en courtes parties vues de dessus.'),
        // Combat et course
        'street-fighter': w('Street Fighter', 'Série de jeux de combat de Capcom, célèbre pour Ryu, Ken et le Hadouken.'),
        tekken: w('Tekken', 'Série de jeux de combat en 3D de Bandai Namco, centrée sur la famille Mishima.'),
        'rocket-league': w('Rocket League', 'Jeu où des voitures à propulsion jouent au football avec un ballon géant.'),
        trackmania: w('Trackmania', 'Jeu de course français contre la montre, sur des circuits remplis de loopings et de sauts.'),
        // Vie paisible
        sims: w('Les Sims', 'Jeu où l’on crée des personnages et gère leur maison, leur travail et leurs relations.'),
        'animal-crossing': w('Animal Crossing', 'Jeu Nintendo où l’on aménage paisiblement un village peuplé d’animaux bavards.'),
        stardew: w('Stardew Valley', 'Jeu indépendant où l’on reprend la vieille ferme de son grand-père pour cultiver ses champs.'),
        // Aventure et horreur
        'resident-evil': w('Resident Evil', 'Série d’horreur de Capcom où l’on affronte des zombies nés d’armes biologiques.'),
        'last-of-us': w('The Last of Us', 'Jeu de survie de Naughty Dog où Joel et Ellie traversent une Amérique ravagée par un champignon.'),
        uncharted: w('Uncharted', 'Série d’aventure de Naughty Dog suivant le chasseur de trésors Nathan Drake.'),
        'tomb-raider': w('Tomb Raider', 'Série d’aventure menée par l’archéologue britannique Lara Croft.'),
        wow: w('World of Warcraft', 'Jeu de rôle en ligne massif de Blizzard, situé dans l’univers d’Azeroth.'),
        dofus: w('Dofus', 'Jeu de rôle en ligne français d’Ankama, aux combats tactiques au tour par tour.'),
        // Matériel
        playstation: w('PlayStation', 'Gamme de consoles de salon de Sony, apparue au milieu des années 1990.'),
        xbox: w('Xbox', 'Gamme de consoles de salon de Microsoft, lancée au début des années 2000.'),
        switch: w('Nintendo Switch', 'Console hybride qui se joue sur la télé ou en portable, avec des manettes détachables.'),
        'steam-deck': w('Steam Deck', 'Console portable de Valve qui fait tourner une bibliothèque de jeux PC.'),
        wii: w('Wii', 'Console de salon sortie en 2006, célèbre pour sa manette à détection de mouvement.'),
        'game-boy': w('Game Boy', 'Console portable à écran monochrome sortie à la fin des années 1980.'),
        ds: w('Nintendo DS', 'Console portable à double écran, dont un tactile utilisable au stylet.'),
        // Personnages
        kirby: w('Kirby', 'Petite boule rose qui aspire ses ennemis pour copier leurs pouvoirs.'),
        yoshi: w('Yoshi', 'Dinosaure vert à longue langue, fidèle monture de Mario, qui pond des œufs.'),
        bowser: w('Bowser', 'Roi des Koopas, tortue géante à carapace à piques qui enlève souvent la princesse Peach.'),
        'donkey-kong': w('Donkey Kong', 'Gorille à cravate rouge, amateur de bananes, qui vit sur une île de la jungle.'),
        // Vocabulaire
        lag: w('Lag', 'Décalage entre l’action du joueur et la réaction du jeu, souvent dû à la connexion.'),
        bug: w('Bug', 'Erreur de programmation qui provoque un comportement imprévu dans un jeu ou un logiciel.'),
        dlc: w('DLC', 'Contenu additionnel téléchargeable, souvent payant, qui enrichit un jeu déjà sorti.'),
        'mise-a-jour': w('Mise à jour', 'Nouvelle version d’un jeu installée après sa sortie pour corriger ou ajouter des éléments.'),
      },
      pairs: [
        p('fortnite', 'apex', 'Jeux de tir en ligne'),
        p('apex', 'overwatch', 'Jeux de tir en ligne'),
        p('overwatch', 'valorant', 'Jeux de tir en ligne'),
        p('valorant', 'counter-strike', 'Jeux compétitifs'),
        p('counter-strike', 'call-of-duty', 'Jeux de tir'),
        p('call-of-duty', 'battlefield', 'Jeux de tir'),
        p('minecraft', 'roblox', 'Jeux de création'),
        p('mario', 'sonic', 'Héros de jeux vidéo'),
        p('mario', 'link', 'Héros de jeux vidéo'),
        p('sonic', 'crash', 'Héros de jeux vidéo'),
        p('crash', 'spyro', 'Héros de jeux vidéo'),
        p('skyrim', 'witcher', 'Jeux de rôle et d’aventure'),
        p('skyrim', 'elden-ring', 'Jeux de rôle et d’aventure'),
        p('elden-ring', 'dark-souls', 'Jeux d’action et d’aventure'),
        p('fifa', 'pes', 'Jeux de sport'),
        p('gta', 'red-dead', 'Jeux en monde ouvert'),
        p('among-us', 'fall-guys', 'Jeux entre amis'),
        p('mario-kart', 'mario-party', 'Jeux de soirée'),
        p('mario-kart', 'smash', 'Jeux de soirée'),
        p('just-dance', 'guitar-hero', 'Jeux de soirée'),
        p('tetris', 'pac-man', 'Jeux rétro'),
        p('tetris', 'candy-crush', 'Jeux de réflexion'),
        p('candy-crush', 'angry-birds', 'Jeux sur smartphone'),
        p('clash-of-clans', 'clash-royale', 'Jeux sur smartphone'),
        p('clash-royale', 'brawl-stars', 'Jeux sur smartphone'),
        p('street-fighter', 'tekken', 'Jeux de combat'),
        p('rocket-league', 'trackmania', 'Jeux de voitures'),
        p('sims', 'animal-crossing', 'Jeux relaxants'),
        p('animal-crossing', 'stardew', 'Jeux relaxants'),
        p('resident-evil', 'last-of-us', 'Jeux de survie'),
        p('last-of-us', 'uncharted', 'Jeux d’action et d’aventure'),
        p('uncharted', 'tomb-raider', 'Jeux d’action et d’aventure'),
        p('wow', 'dofus', 'Jeux de rôle en ligne'),
        p('playstation', 'xbox', 'Matériel de jeu'),
        p('switch', 'steam-deck', 'Matériel de jeu'),
        p('switch', 'wii', 'Matériel de jeu'),
        p('game-boy', 'ds', 'Matériel de jeu'),
        p('kirby', 'yoshi', 'Personnages de jeux vidéo'),
        p('bowser', 'donkey-kong', 'Personnages de jeux vidéo'),
        p('lag', 'bug', 'Problèmes techniques'),
        p('dlc', 'mise-a-jour', 'Vocabulaire du jeu vidéo'),
      ],
    }),

    universe({
      id: 'league-of-legends',
      name: 'League of Legends',
      precise: true,
      words: {
        mana: w('Mana', 'Ressource bleue consommée par la plupart des champions pour lancer leurs compétences.'),
        energie: w('Énergie', 'Ressource jaune qui se régénère vite, utilisée par Zed, Akali, Shen ou Lee Sin.'),
        armure: w('Armure', 'Statistique défensive qui réduit les dégâts physiques subis par un champion.'),
        'resistance-magique': w('Résistance magique', 'Statistique défensive qui réduit les dégâts magiques subis par un champion.'),
        dragon: w('Dragon', 'Monstre épique de la rivière, souvent lié à un élément, dont l’élimination renforce l’équipe.'),
        baron: w('Baron Nashor', 'Monstre épique de la fosse du haut qui renforce l’équipe et ses sbires après sa mort.'),
        heraut: w('Héraut de la Faille', 'Monstre épique dont l’œil permet de l’invoquer pour charger les structures adverses.'),
        tourelle: w('Tourelle', 'Structure défensive qui tire sur les ennemis proches, alignée le long de chaque voie.'),
        inhibiteur: w('Inhibiteur', 'Structure de la base qui, une fois détruite, laisse l’équipe adverse envoyer des super-sbires.'),
        nexus: w('Nexus', 'Structure au cœur de la base qui produit les sbires et dont la destruction met fin à la partie.'),
        'saut-eclair': w('Saut éclair', 'Sort d’invocateur qui déplace instantanément le champion sur une courte distance.'),
        fantome: w('Fantôme', 'Sort d’invocateur qui augmente fortement la vitesse de déplacement pendant quelques secondes.'),
        teleportation: w('Téléportation', 'Sort d’invocateur qui envoie le champion, après une canalisation, vers une position alliée.'),
        tank: w('Tank', 'Classe de champions très résistants, chargés d’encaisser les dégâts et d’engager les combats.'),
        combattant: w('Combattant', 'Classe de champions de mêlée, à la fois robustes et capables d’infliger de lourds dégâts.'),
        assassin: w('Assassin', 'Classe de champions mobiles et fragiles, spécialisés dans l’élimination rapide d’une cible.'),
        mage: w('Mage', 'Classe de champions qui infligent des dégâts magiques à distance grâce à leurs sorts.'),
        tireur: w('Tireur', 'Classe de champions qui infligent des dégâts physiques continus à distance avec leurs attaques.'),
        'lame-infini': w('Lame d’infini', 'Objet légendaire qui donne des dégâts d’attaque et amplifie les coups critiques.'),
        'coiffe-rabadon': w('Coiffe de Rabadon', 'Objet légendaire qui donne beaucoup de puissance et l’augmente d’un pourcentage.'),
        zhonya: w('Sablier de Zhonya', 'Objet légendaire dont l’actif rend le champion invulnérable mais immobile pendant 2,5 secondes.'),
        'ange-gardien': w('Ange gardien', 'Objet légendaire qui ressuscite le champion sur place quelques secondes après sa mort.'),
        ahri: w('Ahri', 'Championne renarde à neuf queues venue d’Ionia, qui charme ses ennemis et lance un orbe.'),
        lux: w('Lux', 'Championne de Demacia qui maîtrise la lumière et tire un immense rayon en ultime.'),
        jinx: w('Jinx', 'Criminelle déjantée de Zaun armée d’une mitrailleuse et d’un lance-roquettes, héroïne d’Arcane.'),
        'miss-fortune': w('Miss Fortune', 'Chasseuse de primes de Bilgewater armée de deux pistolets, qui déchaîne une pluie de balles.'),
        thresh: w('Thresh', 'Geôlier spectral qui lance sa faux enchaînée pour attraper ses ennemis et tend une lanterne.'),
        blitzcrank: w('Blitzcrank', 'Golem de vapeur de Zaun qui attrape ses ennemis à distance avec son bras mécanique.'),
      },
      pairs: [
        p('mana', 'energie', 'Mécaniques de jeu'),
        p('armure', 'resistance-magique', 'Mécaniques de jeu'),
        p('dragon', 'baron', 'Carte et objectifs'),
        p('baron', 'heraut', 'Carte et objectifs'),
        p('tourelle', 'inhibiteur', 'Carte et objectifs'),
        p('inhibiteur', 'nexus', 'Carte et objectifs'),
        p('saut-eclair', 'fantome', 'Sorts et compétences'),
        p('saut-eclair', 'teleportation', 'Sorts et compétences'),
        p('tank', 'combattant', 'Rôles et classes'),
        p('combattant', 'assassin', 'Rôles et classes'),
        p('assassin', 'mage', 'Rôles et classes'),
        p('mage', 'tireur', 'Rôles et classes'),
        p('lame-infini', 'coiffe-rabadon', 'Objets et équipement'),
        p('coiffe-rabadon', 'zhonya', 'Objets et équipement'),
        p('zhonya', 'ange-gardien', 'Objets et équipement'),
        p('ahri', 'lux', 'Champions'),
        p('jinx', 'miss-fortune', 'Champions'),
        p('thresh', 'blitzcrank', 'Champions'),
      ],
    }),

    universe({
      id: 'pokemon',
      name: 'Pokémon',
      precise: true,
      words: {
        pikachu: w('Pikachu', 'Petite souris électrique jaune aux joues rouges, compagnon du héros de l’animé.'),
        evoli: w('Évoli', 'Petit Pokémon brun au col duveteux, capable d’évoluer en de nombreuses formes.'),
        rondoudou: w('Rondoudou', 'Pokémon rose tout rond qui endort son public en chantant, puis gribouille leur visage.'),
        ronflex: w('Ronflex', 'Pokémon géant et glouton qui passe ses journées à dormir, bloquant parfois la route.'),
        salameche: w('Salamèche', 'Petit lézard orange dont la queue porte une flamme, l’un des Pokémon de départ de Kanto.'),
        carapuce: w('Carapuce', 'Petite tortue bleue qui crache de l’eau, l’un des Pokémon de départ de Kanto.'),
        bulbizarre: w('Bulbizarre', 'Petit Pokémon vert portant un bulbe sur le dos, l’un des Pokémon de départ de Kanto.'),
        psykokwak: w('Psykokwak', 'Canard jaune perpétuellement pris de migraines, qui libère alors des pouvoirs psychiques.'),
        magicarpe: w('Magicarpe', 'Poisson orange réputé inutile, dont l’attaque Trempette n’a aucun effet.'),
        mewtwo: w('Mewtwo', 'Pokémon légendaire créé génétiquement en laboratoire, vedette du premier film.'),
        lugia: w('Lugia', 'Pokémon légendaire blanc, gardien des mers, vedette du deuxième film.'),
        roche: w('Roche', 'Type des Pokémon faits de minéraux, très efficace contre les types Vol et Feu.'),
        sol: w('Sol', 'Type des Pokémon terrestres, qui ne subit aucun dégât des attaques Électrik.'),
        spectre: w('Spectre', 'Type des Pokémon fantômes, insensible aux attaques de type Normal et Combat.'),
        tenebres: w('Ténèbres', 'Type des Pokémon sournois et rusés, introduit dans la deuxième génération de jeux.'),
        psy: w('Psy', 'Type des Pokémon aux pouvoirs mentaux, redoutable dans les tout premiers jeux.'),
        'poke-ball': w('Poké Ball', 'Balle rouge et blanche de base, servant à capturer les Pokémon sauvages.'),
        'super-ball': w('Super Ball', 'Balle bleue ornée de bandes rouges, servant à capturer les Pokémon sauvages.'),
        'hyper-ball': w('Hyper Ball', 'Balle noire ornée de motifs jaunes en forme de H, servant à capturer les Pokémon.'),
        potion: w('Potion', 'Spray violet qui rend des points de vie à un Pokémon blessé.'),
        rappel: w('Rappel', 'Cristal jaune qui ranime un Pokémon K.O. en lui rendant la moitié de ses PV.'),
        sacha: w('Sacha', 'Dresseur de Bourg Palette à casquette, héros de l’animé qui rêve de devenir Maître Pokémon.'),
        ondine: w('Ondine', 'Championne d’arène d’Azuria spécialiste du type Eau, compagne de voyage du héros de l’animé.'),
        pierre: w('Pierre', 'Champion d’arène d’Argenta spécialiste des Pokémon minéraux, qui rêve de devenir éleveur.'),
        'centre-pokemon': w('Centre Pokémon', 'Bâtiment au toit rouge où une infirmière soigne gratuitement les Pokémon.'),
        arene: w('Arène', 'Bâtiment où un champion attend les dresseurs et remet un badge au vainqueur.'),
      },
      pairs: [
        p('pikachu', 'evoli', 'Créatures'),
        p('pikachu', 'rondoudou', 'Créatures'),
        p('rondoudou', 'ronflex', 'Créatures'),
        p('salameche', 'carapuce', 'Créatures'),
        p('carapuce', 'bulbizarre', 'Créatures'),
        p('carapuce', 'psykokwak', 'Créatures'),
        p('psykokwak', 'magicarpe', 'Créatures'),
        p('mewtwo', 'lugia', 'Créatures'),
        p('roche', 'sol', 'Types et attaques'),
        p('spectre', 'tenebres', 'Types et attaques'),
        p('spectre', 'psy', 'Types et attaques'),
        p('poke-ball', 'super-ball', 'Objets'),
        p('super-ball', 'hyper-ball', 'Objets'),
        p('potion', 'rappel', 'Objets'),
        p('ondine', 'pierre', 'Personnages'),
        p('pierre', 'sacha', 'Personnages'),
        p('centre-pokemon', 'arene', 'Lieux'),
      ],
    }),

    universe({
      id: 'minecraft',
      name: 'Minecraft',
      precise: true,
      words: {
        zombie: w('Zombie', 'Créature hostile à la peau verte qui attaque au corps à corps et brûle au soleil.'),
        squelette: w('Squelette', 'Créature hostile qui tire des flèches de loin et brûle à la lumière du soleil.'),
        creeper: w('Creeper', 'Créature verte et silencieuse qui s’approche du joueur puis explose.'),
        ghast: w('Ghast', 'Grande créature blanche flottante du Nether qui crache des boules de feu explosives.'),
        blaze: w('Blaze', 'Créature enflammée du Nether, entourée de bâtonnets, qui lance des boules de feu.'),
        wither: w('Wither', 'Boss à trois têtes que le joueur invoque avec des crânes et du sable des âmes.'),
        'ender-dragon': w('Ender Dragon', 'Boss volant qui garde l’île principale de l’End et se soigne grâce à des cristaux.'),
        villageois: w('Villageois', 'Habitant pacifique des villages, qui échange des objets contre des émeraudes.'),
        piglin: w('Piglin', 'Créature du Nether à tête de cochon, qui troque des objets contre des lingots d’or.'),
        diamant: w('Diamant', 'Minerai rare et précieux, utilisé pour fabriquer des outils et armures bleu clair.'),
        emeraude: w('Émeraude', 'Minerai vert très rare, servant de monnaie d’échange dans les villages.'),
        netherite: w('Netherite', 'Matériau très résistant obtenu dans le Nether à partir de débris antiques.'),
        obsidienne: w('Obsidienne', 'Bloc noir violacé très résistant, formé quand l’eau rencontre une source de lave.'),
        bedrock: w('Bedrock', 'Bloc indestructible en mode Survie, qui forme le fond du monde.'),
        sable: w('Sable', 'Bloc qui tombe s’il n’est pas soutenu et que l’on fait fondre pour obtenir du verre.'),
        gravier: w('Gravier', 'Bloc gris qui tombe s’il n’est pas soutenu et laisse parfois tomber du silex.'),
        pioche: w('Pioche', 'Outil qui sert à miner la roche, les minerais et la plupart des blocs durs.'),
        pelle: w('Pelle', 'Outil qui sert à creuser rapidement la terre, la neige et les blocs meubles.'),
        hache: w('Hache', 'Outil qui abat rapidement les arbres et peut aussi servir d’arme puissante.'),
        epee: w('Épée', 'Arme de corps à corps capable de balayer plusieurs ennemis d’un seul coup.'),
        arc: w('Arc', 'Arme à distance qui tire des flèches, dont la puissance dépend du temps de tension.'),
        arbalete: w('Arbalète', 'Arme à distance qui se charge à l’avance et peut tirer des feux d’artifice.'),
        nether: w('Nether', 'Dimension infernale remplie de lave, accessible par un portail d’obsidienne.'),
        end: w('End', 'Dimension sombre peuplée d’Endermen, accessible par un portail caché dans un fort.'),
        etabli: w('Établi', 'Bloc qui offre une grille de fabrication de trois cases sur trois.'),
        fourneau: w('Fourneau', 'Bloc qui cuit la nourriture et fond les minerais grâce à un combustible.'),
      },
      pairs: [
        p('zombie', 'squelette', 'Créatures'),
        p('squelette', 'creeper', 'Créatures'),
        p('creeper', 'ghast', 'Créatures'),
        p('ghast', 'blaze', 'Créatures'),
        p('wither', 'ender-dragon', 'Créatures'),
        p('villageois', 'piglin', 'Créatures'),
        p('diamant', 'emeraude', 'Ressources et matériaux'),
        p('diamant', 'netherite', 'Ressources et matériaux'),
        p('obsidienne', 'bedrock', 'Blocs'),
        p('sable', 'gravier', 'Blocs'),
        p('etabli', 'fourneau', 'Blocs'),
        p('pioche', 'pelle', 'Outils et armes'),
        p('pioche', 'hache', 'Outils et armes'),
        p('hache', 'epee', 'Outils et armes'),
        p('epee', 'arc', 'Outils et armes'),
        p('arc', 'arbalete', 'Outils et armes'),
        p('nether', 'end', 'Lieux'),
      ],
    }),
  ],
});
