import { definePack } from './types';

export default definePack({
  id: 'nourriture',
  name: 'Nourriture',
  description: 'Plats du quotidien, douceurs sucrées et spécialités du monde.',
  icon: 'pizza',
  pairs: [
    ['Pizza', 'Tarte'],
    ['Sushi', 'Maki'],
    ['Croissant', 'Pain au chocolat'],
    ['Crêpe', 'Gaufre'],
    ['Burger', 'Kebab'],
    ['Frites', 'Chips'],
    ['Pâtes', 'Riz'],
    ['Raclette', 'Fondue'],
    ['Ketchup', 'Mayonnaise'],
    ['Moutarde', 'Wasabi'],
    ['Chocolat', 'Caramel'],
    ['Glace', 'Sorbet'],
    ['Café', 'Thé'],
    ['Coca-Cola', 'Pepsi'],
    ['Camembert', 'Brie'],
    ['Pomme', 'Poire'],
    ['Fraise', 'Framboise'],
    ['Citron', 'Pamplemousse'],
    ['Pastèque', 'Melon'],
    ['Courgette', 'Aubergine'],
    ['Oignon', 'Ail'],
    ['Couscous', 'Tajine'],
    ['Taco', 'Burrito'],
    ['Ramen', 'Pho'],
    ['Omelette', 'Œuf au plat'],
    ['Muffin', 'Cupcake'],
    ['Macaron', 'Meringue'],
    ['Éclair', 'Religieuse'],
    ['Nutella', 'Confiture'],
    ['Lasagnes', 'Moussaka'],
    ['Yaourt', 'Fromage blanc'],
    ['Miel', "Sirop d'érable"],
    ['Saucisson', 'Jambon'],
    ['Poulet', 'Dinde'],
    ['Popcorn', 'Barbe à papa'],
    ['Donut', 'Beignet'],
    ['Paella', 'Risotto'],
    ['Bonbon', 'Sucette'],
    ['Cookie', 'Brownie'],
    ['Tiramisu', 'Panna cotta'],
    ['Baguette', 'Brioche'],
    ['Smoothie', 'Milkshake'],
  ],
});
