import { definePack, pair } from './types';

export default definePack({
  id: 'nourriture',
  name: 'Nourriture',
  description: 'Plats du quotidien, douceurs sucrées et spécialités du monde.',
  icon: 'pizza',
  pairs: [
    pair('Plats cuits au four', ['Pizza', 'Pâte fine garnie de tomate et de fromage, d’origine italienne.'], ['Tarte', 'Pâte cuite au four garnie de fruits ou d’ingrédients salés.']),
    pair('Gastronomie japonaise', ['Sushi', 'Spécialité japonaise de riz vinaigré, souvent associée à du poisson cru.'], ['Maki', 'Rouleau de riz vinaigré et de garniture, enveloppé d’une feuille d’algue nori.']),
    pair('Petit-déjeuner à la française', ['Croissant', 'Viennoiserie feuilletée au beurre, reconnaissable à sa forme arquée.'], ['Pain au chocolat', 'Viennoiserie rectangulaire feuilletée, fourrée de deux barres de chocolat.']),
    pair('Douceurs du goûter', ['Crêpe', 'Fine couche de pâte cuite à la poêle, reine de la Chandeleur.'], ['Gaufre', 'Pâte cuite entre deux plaques alvéolées, spécialité belge et du Nord.']),
    pair('Restauration rapide', ['Burger', 'Pain rond garni d’un steak haché, de fromage et de crudités.'], ['Kebab', 'Viande grillée à la broche verticale, servie en pain ou en galette.']),
    pair('Accompagnements croustillants', ['Frites', 'Bâtonnets de pomme de terre plongés dans l’huile bouillante.'], ['Chips', 'Fines rondelles de pomme de terre croustillantes, vendues en sachet.']),
    pair('Féculents du quotidien', ['Pâtes', 'Aliment à base de blé dur façonné en formes variées, cuit à l’eau.'], ['Riz', 'Céréale en petits grains cultivée en rizière, base de l’alimentation en Asie.']),
    pair('Plats d’hiver conviviaux', ['Raclette', 'Fromage chauffé et raclé, servi sur des pommes de terre avec de la charcuterie.'], ['Fondue', 'Caquelon de fromage chaud dans lequel on trempe des morceaux de pain.']),
    pair('Sauces en condiment', ['Ketchup', 'Sauce rouge et sucrée à base de concentré de tomate et de vinaigre.'], ['Mayonnaise', 'Sauce froide émulsionnée à base de jaune d’œuf, d’huile et de moutarde.']),
    pair('Condiments', ['Moutarde', 'Condiment jaune préparé à partir de graines broyées, emblème de Dijon.'], ['Wasabi', 'Condiment japonais vert et piquant, obtenu en râpant un rhizome.']),
    pair('Parfums de dessert', ['Chocolat', 'Produit à base de cacao et de sucre, noir, au lait ou blanc.'], ['Caramel', 'Sucre chauffé jusqu’à brunir, dur ou fondant, parfois au beurre salé.']),
    pair('Desserts froids en boules', ['Glace', 'Dessert congelé à base de lait ou de crème, servi en cornet ou en pot.'], ['Sorbet', 'Dessert congelé à base de purée ou de jus de fruits et de sucre.']),
    pair('Boissons chaudes', ['Café', 'Boisson chaude et amère faite de grains torréfiés et moulus.'], ['Thé', 'Infusion de feuilles séchées d’un arbuste cultivé surtout en Asie.']),
    pair('Boissons sucrées', ['Coca-Cola', 'Soda créé à Atlanta en 1886, célèbre pour sa bouteille galbée.'], ['Pepsi', 'Soda créé en Caroline du Nord dans les années 1890, au logo rond tricolore.']),
    pair('Fromages français', ['Camembert', 'Fromage normand au lait de vache, vendu dans une boîte ronde en bois.'], ['Brie', 'Fromage au lait de vache d’Île-de-France, en large meule plate servie en pointes.']),
    pair('Fruits du verger', ['Pomme', 'Fruit rond et croquant, rouge, vert ou jaune, base du cidre et de la compote.'], ['Poire', 'Fruit juteux en forme de goutte, à la chair fondante et parfois granuleuse.']),
    pair('Petits fruits rouges', ['Fraise', 'Fruit rouge parsemé de petits grains jaunes à sa surface.'], ['Framboise', 'Petit fruit rouge et creux, formé de minuscules grains veloutés.']),
    pair('Agrumes acidulés', ['Citron', 'Agrume jaune très acide, pressé pour son jus ou râpé pour son zeste.'], ['Pamplemousse', 'Gros agrume à la chair rose ou jaune, au goût acidulé et légèrement amer.']),
    pair('Gros fruits d’été', ['Pastèque', 'Gros fruit à écorce verte et chair rouge parsemée de pépins noirs.'], ['Melon', 'Fruit rond à la chair orange et sucrée, spécialité de Cavaillon.']),
    pair('Légumes de la ratatouille', ['Courgette', 'Légume allongé à peau verte, de la même famille que les courges.'], ['Aubergine', 'Légume à la peau violette et brillante, à la chair spongieuse.']),
    pair('Bulbes aromatiques', ['Oignon', 'Bulbe à couches superposées qui fait pleurer quand on le coupe.'], ['Ail', 'Bulbe formé de gousses au goût fort, réputé pour chasser les vampires.']),
    pair('Cuisine du Maghreb', ['Couscous', 'Semoule de blé servie avec des légumes, de la viande et un bouillon.'], ['Tajine', 'Ragoût mijoté dans un plat en terre cuite à couvercle conique.']),
    pair('Cuisine mexicaine', ['Taco', 'Petite galette de maïs repliée autour d’une garniture, mangée à la main.'], ['Burrito', 'Galette de farine de blé roulée et fermée, garnie de riz, haricots et viande.']),
    pair('Soupes de nouilles asiatiques', ['Ramen', 'Soupe japonaise de nouilles de blé dans un bouillon riche.'], ['Pho', 'Soupe vietnamienne de nouilles de riz dans un bouillon parfumé, souvent au bœuf.']),
    pair('Classiques à la poêle', ['Omelette', 'Jaunes et blancs battus ensemble, cuits à la poêle puis souvent repliés.'], ['Œuf au plat', 'Cassé tel quel dans une poêle chaude, blanc saisi et jaune laissé coulant.']),
    pair('Petits gâteaux individuels', ['Muffin', 'Petit gâteau moelleux et bombé, souvent aux myrtilles ou aux pépites.'], ['Cupcake', 'Petit gâteau individuel surmonté d’un glaçage crémeux décoré.']),
    pair('Petites douceurs de pâtisserie',['Macaron', 'Deux coques lisses à l’amande collées par une garniture crémeuse.'], ['Meringue', 'Blancs d’œufs battus en neige avec du sucre, cuits jusqu’à être croquants.']),
    pair('Pâtisseries françaises', ['Éclair', 'Pâtisserie allongée en pâte à choux, fourrée de crème et glacée dessus.'], ['Religieuse', 'Deux choux superposés garnis de crème, évoquant une silhouette de nonne.']),
    pair('Tartines du matin', ['Nutella', 'Pâte à tartiner italienne aux noisettes et au cacao, vendue en pot.'], ['Confiture', 'Fruits cuits longuement avec du sucre, conservés en pot.']),
    pair('Plats gratinés en couches', ['Lasagnes', 'Plat italien de feuilles de pâte alternées avec sauce bolognaise et béchamel.'], ['Moussaka', 'Plat grec en couches d’aubergines, de viande hachée et de béchamel.']),
    pair('Produits laitiers frais', ['Yaourt', 'Lait fermenté par des bactéries, vendu en petit pot individuel.'], ['Fromage blanc', 'Laitage frais et lisse obtenu par caillage du lait, sans affinage.']),
    pair('Sucrants naturels', ['Miel', 'Substance sucrée fabriquée par les abeilles à partir du nectar des fleurs.'], ["Sirop d'érable", 'Sève d’arbre concentrée par ébullition, emblème du Québec.']),
    pair('Charcuterie de porc', ['Saucisson', 'Charcuterie sèche et cylindrique, coupée en rondelles à l’apéritif.'], ['Jambon', 'Cuisse de porc cuite ou séchée, servie en tranches.']),
    pair('Volailles à rôtir', ['Poulet', 'Jeune volaille d’élevage, très consommée rôtie ou en filets.'], ['Dinde', 'Grosse volaille originaire d’Amérique, traditionnellement farcie à Noël.']),
    pair('Friandises de fête foraine', ['Popcorn', 'Grains de maïs éclatés à la chaleur, salés ou sucrés, grignotés au cinéma.'], ['Barbe à papa', 'Sucre filé en nuage rose ou blanc, enroulé autour d’un bâton.']),
    pair('Pâtisseries frites', ['Donut', 'Anneau de pâte frite nappé de glaçage, popularisé aux États-Unis.'], ['Beignet', 'Pâte frite dans l’huile, souvent fourrée de confiture et sucrée.']),
    pair('Plats du sud de l’Europe', ['Paella', 'Plat espagnol de riz safrané cuit en large poêle, souvent aux fruits de mer.'], ['Risotto', 'Riz italien cuit lentement au bouillon et lié au parmesan, bien crémeux.']),
    pair('Confiseries d’enfance', ['Bonbon', 'Petite friandise sucrée, dure ou gélifiée, souvent emballée.'], ['Sucette', 'Confiserie dure fixée au bout d’un bâtonnet, qu’on lèche.']),
    pair('Gâteaux américains', ['Cookie', 'Biscuit rond et croustillant aux pépites de chocolat.'], ['Brownie', 'Gâteau au chocolat dense et fondant, découpé en carrés.']),
    pair('Desserts italiens', ['Tiramisu', 'Dessert au mascarpone et aux biscuits imbibés de café.'], ['Panna cotta', 'Crème cuite prise en gelée, souvent servie avec un coulis de fruits.']),
    pair('Rayon boulangerie', ['Baguette', 'Pain long et fin à croûte croustillante, symbole de la France.'], ['Brioche', 'Pain moelleux et doré, enrichi en beurre, en œufs et en sucre.']),
    pair('Boissons mixées', ['Smoothie', 'Boisson épaisse de fruits mixés, parfois additionnée de yaourt.'], ['Milkshake', 'Boisson frappée de lait et de crème glacée, servie avec une paille.']),
  ],
});
