import { definePack, p, universe, w } from './types';

export default definePack({
  id: 'nourriture',
  name: 'Nourriture',
  description: 'Plats du quotidien, douceurs sucrées et spécialités du monde.',
  icon: 'pizza',
  universes: [
    universe({
      id: 'general',
      name: 'Nourriture',
      precise: false,
      words: {
        // Plats salés
        pizza: w('Pizza', 'Pâte fine garnie de sauce tomate et de fromage fondu, d’origine napolitaine.'),
        flammekueche: w('Flammekueche', 'Spécialité alsacienne, dite tarte flambée : pâte très fine, crème, oignons, lardons.'),
        quiche: w('Quiche', 'Tarte salée garnie d’œufs battus et de crème, souvent agrémentée de lardons.'),
        omelette: w('Omelette', 'Œufs battus cuits à la poêle, nature ou garnis, souvent repliés en deux.'),
        burger: w('Burger', 'Pain rond garni d’un steak haché, de fromage, de salade et de sauce.'),
        kebab: w('Kebab', 'Viande grillée à la broche verticale, servie en pain ou en galette avec des crudités.'),
        tacos: w('Tacos', 'Spécialité de fast-food née en France : galette de blé, viande, frites et sauce fromagère.'),
        burrito: w('Burrito', 'Grande galette de blé roulée et fermée, garnie de riz, de haricots et de viande.'),
        lasagnes: w('Lasagnes', 'Plat italien de feuilles de pâte superposées avec sauce bolognaise et béchamel.'),
        moussaka: w('Moussaka', 'Plat grec en couches d’aubergines, de viande hachée et de béchamel, gratiné.'),
        'hachis-parmentier': w('Hachis parmentier', 'Viande hachée recouverte de purée de pommes de terre, gratinée au four.'),
        paella: w('Paella', 'Plat espagnol de riz safrané cuit dans une large poêle, souvent aux fruits de mer.'),
        risotto: w('Risotto', 'Riz italien cuit lentement en ajoutant du bouillon, lié au parmesan et au beurre.'),
        couscous: w('Couscous', 'Semoule de blé servie avec des légumes, de la viande et un bouillon épicé.'),
        'pot-au-feu': w('Pot-au-feu', 'Viande et légumes cuits longuement dans un bouillon, servis avec moutarde et gros sel.'),
        bourguignon: w('Bœuf bourguignon', 'Morceaux de viande mijotés dans du vin rouge avec lardons, champignons et oignons.'),
        sushi: w('Sushi', 'Bouchée japonaise de riz vinaigré, souvent surmontée d’une tranche de poisson cru.'),
        poke: w('Poké bowl', 'Bol hawaïen de riz garni de poisson cru mariné, d’avocat et de légumes.'),
        ramen: w('Ramen', 'Soupe japonaise de nouilles de blé dans un bouillon riche, garnie d’un œuf mollet.'),
        pho: w('Pho', 'Soupe vietnamienne de nouilles de riz dans un bouillon parfumé, souvent au bœuf.'),
        raclette: w('Raclette', 'Fromage chauffé et raclé sur des pommes de terre, servi avec de la charcuterie.'),
        tartiflette: w('Tartiflette', 'Gratin savoyard de pommes de terre, de lardons et d’oignons, couvert de reblochon.'),
        fondue: w('Fondue', 'Caquelon de fromage chaud où l’on trempe des cubes de pain au bout d’une longue fourchette.'),
        frites: w('Frites', 'Bâtonnets de pomme de terre plongés dans l’huile bouillante, servis bien dorés.'),
        chips: w('Chips', 'Fines rondelles de pomme de terre croustillantes, vendues en sachet.'),
        popcorn: w('Popcorn', 'Grains de maïs éclatés à la chaleur, salés ou sucrés, grignotés au cinéma.'),

        // Douceurs
        crepe: w('Crêpe', 'Fine galette de pâte cuite à la poêle, reine de la Chandeleur.'),
        pancake: w('Pancake', 'Petite galette épaisse et moelleuse, servie en pile avec un filet de sirop.'),
        gaufre: w('Gaufre', 'Pâte cuite entre deux plaques alvéolées, spécialité belge et du Nord.'),
        churros: w('Churros', 'Bâtonnets de pâte striés, frits puis roulés dans le sucre, d’origine espagnole.'),
        donut: w('Donut', 'Anneau de pâte frite nappé de glaçage coloré, popularisé aux États-Unis.'),
        muffin: w('Muffin', 'Petit gâteau moelleux et bombé, cuit en caissette, souvent aux myrtilles.'),
        croissant: w('Croissant', 'Viennoiserie feuilletée au beurre, reconnaissable à sa forme arquée.'),
        brioche: w('Brioche', 'Pâte moelleuse et dorée, enrichie en beurre, en œufs et en sucre.'),
        'pain-au-chocolat': w('Pain au chocolat', 'Viennoiserie feuilletée rectangulaire, fourrée de deux barres de chocolat.'),
        'pain-aux-raisins': w('Pain aux raisins', 'Viennoiserie en spirale garnie de crème pâtissière et de raisins secs.'),
        chausson: w('Chausson aux pommes', 'Pâte feuilletée repliée en demi-lune sur une compote, dorée au four.'),
        tiramisu: w('Tiramisu', 'Dessert italien au mascarpone et aux biscuits imbibés de café, saupoudré de cacao.'),
        charlotte: w('Charlotte', 'Dessert entouré de biscuits à la cuillère, garni de mousse ou de crème aux fruits.'),
        'creme-brulee': w('Crème brûlée', 'Crème aux œufs cuite au four, couverte de sucre caramélisé au chalumeau.'),
        flan: w('Flan', 'Dessert tremblotant à base de lait, d’œufs et de sucre, pris au four.'),
        miel: w('Miel', 'Substance sucrée fabriquée par les abeilles à partir du nectar des fleurs.'),
        'sirop-erable': w('Sirop d’érable', 'Sève d’arbre concentrée par ébullition, emblème du Québec.'),
        confiture: w('Confiture', 'Fruits cuits longuement avec du sucre, conservés en pot et étalés sur le pain.'),
        nutella: w('Nutella', 'Pâte à tartiner italienne aux noisettes et au cacao, vendue en pot.'),

        // Fruits et légumes
        peche: w('Pêche', 'Fruit d’été à peau duveteuse et à gros noyau, à chair blanche ou jaune.'),
        abricot: w('Abricot', 'Petit fruit orangé à peau veloutée et à noyau, récolté au début de l’été.'),
        fraise: w('Fraise', 'Fruit rouge parsemé de petits grains à sa surface, cueilli au printemps.'),
        cerise: w('Cerise', 'Petit fruit rouge et rond à noyau, suspendu par une longue queue.'),
        orange: w('Orange', 'Agrume à peau épaisse, riche en vitamine C, souvent pressé en jus le matin.'),
        pamplemousse: w('Pamplemousse', 'Gros agrume à chair rose ou jaune, au goût acidulé et légèrement amer.'),
        melon: w('Melon', 'Fruit rond à la chair orangée et sucrée, spécialité de Cavaillon.'),
        pasteque: w('Pastèque', 'Gros fruit à écorce verte et chair rouge parsemée de pépins noirs.'),
        courgette: w('Courgette', 'Légume allongé à peau verte, de la famille des courges, star de la ratatouille.'),
        concombre: w('Concombre', 'Légume allongé à peau verte, croquant et gorgé d’eau, souvent mangé cru.'),
        aubergine: w('Aubergine', 'Légume à la peau violette et brillante, à la chair spongieuse.'),
        oignon: w('Oignon', 'Bulbe à couches superposées qui fait pleurer quand on le coupe.'),
        echalote: w('Échalote', 'Petit bulbe allongé à la saveur fine, émincé dans les sauces et vinaigrettes.'),

        // Boissons
        the: w('Thé', 'Infusion de feuilles séchées d’un arbuste cultivé surtout en Asie.'),
        tisane: w('Tisane', 'Infusion de plantes ou de fleurs séchées, comme la verveine ou la camomille.'),
        cafe: w('Café', 'Boisson amère faite de grains torréfiés et moulus, servie en tasse ou en expresso.'),
        'chocolat-chaud': w('Chocolat chaud', 'Boisson de lait et de cacao, souvent servie avec une tartine au goûter.'),
        milkshake: w('Milkshake', 'Boisson épaisse de lait mixé avec de la crème glacée, servie avec une paille.'),
        smoothie: w('Smoothie', 'Boisson épaisse de fruits mixés, parfois additionnée de yaourt.'),
        fanta: w('Fanta', 'Soda fruité et pétillant créé en Allemagne en 1940, célèbre dans sa version orange.'),
        orangina: w('Orangina', 'Boisson pétillante aux agrumes et à la pulpe, vendue en petite bouteille ronde.'),
      },
      pairs: [
        p('pizza', 'flammekueche', 'Plats cuits au four'),
        p('flammekueche', 'quiche', 'Plats cuits au four'),
        p('quiche', 'omelette', 'Repas simples du soir'),
        p('burger', 'kebab', 'Restauration rapide'),
        p('kebab', 'tacos', 'Restauration rapide'),
        p('tacos', 'burrito', 'Plats à manger avec les mains'),
        p('lasagnes', 'moussaka', 'Plats gratinés'),
        p('lasagnes', 'hachis-parmentier', 'Plats familiaux'),
        p('paella', 'risotto', 'Plats à partager'),
        p('paella', 'couscous', 'Plats de grandes tablées'),
        p('pot-au-feu', 'bourguignon', 'Plats mijotés'),
        p('sushi', 'poke', 'Cuisines du monde'),
        p('ramen', 'pho', 'Cuisine asiatique'),
        p('raclette', 'tartiflette', 'Plats d’hiver'),
        p('fondue', 'tartiflette', 'Soirées d’hiver'),
        p('frites', 'chips', 'Snacks salés'),
        p('chips', 'popcorn', 'Grignotage'),

        p('crepe', 'pancake', 'Douceurs du goûter'),
        p('pancake', 'gaufre', 'Petit-déjeuner gourmand'),
        p('gaufre', 'churros', 'Gourmandises sucrées'),
        p('churros', 'donut', 'Gourmandises sucrées'),
        p('donut', 'muffin', 'Petits gâteaux'),
        p('croissant', 'brioche', 'Rayon boulangerie'),
        p('croissant', 'chausson', 'Petit-déjeuner à la française'),
        p('pain-au-chocolat', 'pain-aux-raisins', 'Rayon boulangerie'),
        p('pain-au-chocolat', 'chausson', 'Goûter à la boulangerie'),
        p('tiramisu', 'charlotte', 'Desserts maison'),
        p('creme-brulee', 'flan', 'Desserts maison'),
        p('miel', 'sirop-erable', 'Produits sucrés'),
        p('miel', 'confiture', 'Sur une tartine'),
        p('confiture', 'nutella', 'Sur une tartine'),

        p('peche', 'abricot', 'Fruits d’été'),
        p('fraise', 'cerise', 'Fruits de saison'),
        p('orange', 'pamplemousse', 'Fruits d’hiver'),
        p('melon', 'pasteque', 'Fruits d’été'),
        p('courgette', 'concombre', 'Légumes du potager'),
        p('courgette', 'aubergine', 'Légumes du potager'),
        p('oignon', 'echalote', 'Ingrédients de cuisine'),

        p('the', 'tisane', 'Boissons chaudes'),
        p('cafe', 'chocolat-chaud', 'Boissons du matin'),
        p('chocolat-chaud', 'milkshake', 'Boissons gourmandes'),
        p('milkshake', 'smoothie', 'Boissons fraîches'),
        p('fanta', 'orangina', 'Boissons pétillantes'),
      ],
    }),
  ],
});
