import { definePack } from './types';

export default definePack({
  id: 'objets',
  name: 'Objets du quotidien',
  description: "Ce qui traîne sur la table, dans le sac ou au fond d'un tiroir.",
  icon: 'lamp',
  pairs: [
    ['Tasse', 'Verre'],
    ['Lampe', 'Bougie'],
    ['Fourchette', 'Cuillère'],
    ['Stylo', 'Crayon'],
    ['Brosse à dents', 'Fil dentaire'],
    ['Oreiller', 'Coussin'],
    ['Couette', 'Drap'],
    ['Smartphone', 'Tablette'],
    ['Clé', 'Cadenas'],
    ['Parapluie', 'Imperméable'],
    ['Montre', 'Réveil'],
    ['Lunettes', 'Lentilles'],
    ['Sac à dos', 'Cartable'],
    ['Ciseaux', 'Cutter'],
    ['Savon', 'Gel douche'],
    ['Télécommande', 'Manette'],
    ['Chaise', 'Tabouret'],
    ['Canapé', 'Fauteuil'],
    ['Rideau', 'Store'],
    ['Casserole', 'Poêle'],
    ['Four', 'Micro-ondes'],
    ['Frigo', 'Congélateur'],
    ['Aspirateur', 'Balai'],
    ['Éponge', 'Chiffon'],
    ['Ordinateur', 'Télévision'],
    ['Écouteurs', 'Casque'],
    ['Chargeur', 'Batterie externe'],
    ['Porte-monnaie', 'Portefeuille'],
    ['Bouteille', 'Gourde'],
    ['Assiette', 'Bol'],
    ['Agrafeuse', 'Trombone'],
    ['Gomme', 'Correcteur'],
    ['Cintre', 'Porte-manteau'],
    ['Radiateur', 'Ventilateur'],
    ['Marteau', 'Tournevis'],
    ['Briquet', 'Allumettes'],
    ['Enveloppe', 'Carte postale'],
    ['Livre', 'Magazine'],
    ['Calendrier', 'Agenda'],
  ],
});
