import { definePack, p, universe, w } from './types';

export default definePack({
  id: 'objets',
  name: 'Objets du quotidien',
  description: "Ce qui traîne sur la table, dans le sac ou au fond d'un tiroir.",
  icon: 'lamp',
  universes: [
    universe({
      id: 'general',
      name: 'Objets du quotidien',
      precise: false,
      words: {
        // Cuisine et table
        tasse: w('Tasse', 'Petit récipient à anse dans lequel on boit une boisson chaude.'),
        bol: w('Bol', 'Récipient rond et profond, sans anse, pour les céréales, la soupe ou le café au lait.'),
        thermos: w('Thermos', 'Bouteille isotherme à double paroi qui garde les boissons chaudes ou froides.'),
        gourde: w('Gourde', 'Flacon réutilisable qu’on emporte en randonnée ou au sport pour boire.'),
        glaciere: w('Glacière', 'Caisse isolante qu’on remplit de pains de glace pour garder les aliments au frais.'),
        frigo: w('Frigo', 'Appareil de cuisine qui conserve les aliments au frais, autour de 4 °C.'),
        fourchette: w('Fourchette', 'Couvert à dents qui sert à piquer les aliments dans l’assiette.'),
        baguettes: w('Baguettes', 'Paire de bâtonnets tenus d’une main pour manger, surtout en Asie.'),
        poele: w('Poêle', 'Ustensile plat à bords bas et à long manche pour saisir ou faire revenir.'),
        wok: w('Wok', 'Large ustensile creux et arrondi, utilisé pour les sautés de la cuisine asiatique.'),
        bouilloire: w('Bouilloire', 'Appareil électrique qui porte rapidement l’eau à ébullition pour le thé ou les infusions.'),
        cafetiere: w('Cafetière', 'Appareil qui prépare le café par filtre ou à capsules, pour une ou plusieurs personnes.'),
        eponge: w('Éponge', 'Bloc souple et absorbant, souvent doté d’une face grattante, pour la vaisselle.'),
        chiffon: w('Chiffon', 'Morceau de tissu qui sert à essuyer ou à dépoussiérer les meubles.'),

        // Salle de bain
        'brosse-a-dents': w('Brosse à dents', 'Petit manche muni de poils qu’on frotte sur les dents matin et soir.'),
        rasoir: w('Rasoir', 'Appareil à lames ou électrique qui sert à couper les poils au ras de la peau.'),
        'seche-cheveux': w('Sèche-cheveux', 'Appareil électrique qui souffle de l’air chaud pour sécher la chevelure.'),
        shampoing: w('Shampoing', 'Produit liquide moussant qu’on applique sur le cuir chevelu pour le laver.'),
        'gel-douche': w('Gel douche', 'Produit liquide moussant, vendu en flacon, pour se laver le corps.'),

        // Maison et mobilier
        oreiller: w('Oreiller', 'Rembourrage sur lequel on pose la tête pour dormir dans un lit.'),
        coussin: w('Coussin', 'Petit rembourrage décoratif posé sur un canapé pour plus de confort.'),
        plaid: w('Plaid', 'Couverture légère qu’on jette sur le canapé ou sur ses épaules pour se réchauffer.'),
        couette: w('Couette', 'Épaisse enveloppe garnie de plumes ou de fibres pour se couvrir au lit.'),
        chaise: w('Chaise', 'Siège à quatre pieds muni d’un dossier, pour une personne.'),
        tabouret: w('Tabouret', 'Petit siège sans dossier ni bras, parfois haut comme au comptoir d’un bar.'),
        fauteuil: w('Fauteuil', 'Siège rembourré à dossier et accoudoirs, pour une seule personne.'),
        transat: w('Transat', 'Siège pliant en toile tendue sur un cadre, pour se prélasser au soleil.'),
        hamac: w('Hamac', 'Toile suspendue entre deux points d’attache, dans laquelle on se balance.'),
        'lampe-de-poche': w('Lampe de poche', 'Éclairage portatif à piles qu’on allume pour y voir dans le noir.'),
        bougie: w('Bougie', 'Bâton de cire muni d’une mèche que l’on allume pour éclairer ou parfumer.'),
        ventilateur: w('Ventilateur', 'Appareil à pales tournantes qui brasse l’air pour rafraîchir une pièce.'),
        eventail: w('Éventail', 'Accessoire pliant qu’on agite devant son visage pour se rafraîchir.'),
        parasol: w('Parasol', 'Grande toile tendue sur un mât, plantée sur la plage ou en terrasse contre le soleil.'),
        parapluie: w('Parapluie', 'Toile tendue sur une armature pliable, tenue au-dessus de la tête.'),

        // Écrans et high-tech
        telecommande: w('Télécommande', 'Petit boîtier à boutons pour changer de chaîne ou régler le volume.'),
        manette: w('Manette', 'Accessoire tenu à deux mains, avec boutons et joysticks, pour jouer sur console.'),
        smartphone: w('Smartphone', 'Téléphone mobile à écran tactile, avec applications et accès à Internet.'),
        tablette: w('Tablette', 'Appareil plat à grand écran tactile pour lire, regarder des vidéos ou dessiner.'),
        ordinateur: w('Ordinateur', 'Machine à clavier et écran pour travailler, naviguer sur Internet ou jouer.'),
        ecouteurs: w('Écouteurs', 'Petits haut-parleurs qu’on insère dans les oreilles, avec ou sans fil.'),
        enceinte: w('Enceinte', 'Haut-parleur qu’on branche ou qu’on connecte en Bluetooth pour diffuser la musique.'),

        // Sur soi et en sortie
        montre: w('Montre', 'Petit cadran qu’on porte au poignet pour lire l’heure.'),
        bracelet: w('Bracelet', 'Bijou en forme d’anneau ou de chaîne qu’on porte autour du poignet.'),
        lunettes: w('Lunettes', 'Deux verres correcteurs fixés sur une monture posée sur le nez.'),
        jumelles: w('Jumelles', 'Instrument optique à deux tubes qui grossit ce qui est loin.'),
        cle: w('Clé', 'Petite pièce métallique dentée qu’on tourne dans une serrure.'),
        badge: w('Badge', 'Petite carte ou pastille qu’on approche d’un lecteur pour ouvrir une porte.'),
        'sac-a-dos': w('Sac à dos', 'Bagage à deux bretelles porté sur les épaules, prisé en randonnée.'),
        valise: w('Valise', 'Bagage rigide ou souple, souvent à roulettes, qu’on remplit avant de partir en voyage.'),
        cartable: w('Cartable', 'Sac rigide d’écolier pour transporter livres et cahiers.'),

        // Bureau, école et bricolage
        stylo: w('Stylo', 'Instrument à encre, souvent à bille, pour écrire sur le papier.'),
        feutre: w('Feutre', 'Tube d’encre terminé par une pointe poreuse, pour colorier ou écrire.'),
        crayon: w('Crayon', 'Baguette de bois à mine, qu’on taille et dont le trait s’efface.'),
        agrafeuse: w('Agrafeuse', 'Appareil de bureau qui fixe des feuilles ensemble avec des agrafes.'),
        trombone: w('Trombone', 'Petit fil de métal replié en boucles qui pince quelques feuilles.'),
        scotch: w('Scotch', 'Ruban adhésif transparent qu’on déroule pour fixer ou fermer un paquet.'),
        colle: w('Colle', 'Substance qu’on étale pour faire adhérer deux surfaces, en tube ou en bâton.'),
        ciseaux: w('Ciseaux', 'Deux lames articulées qu’on actionne avec les doigts pour découper.'),
        cutter: w('Cutter', 'Lame rétractable et sécable glissée dans un manche, pour trancher le carton.'),
        tournevis: w('Tournevis', 'Outil à tige métallique et à manche pour serrer ou desserrer des vis.'),
        perceuse: w('Perceuse', 'Outil électrique qui fait tourner un foret pour percer des trous dans le mur.'),
        livre: w('Livre', 'Ouvrage relié de nombreuses pages : roman, essai ou bande dessinée.'),
        magazine: w('Magazine', 'Publication périodique illustrée, souvent hebdomadaire ou mensuelle.'),
        agenda: w('Agenda', 'Cahier daté où l’on note ses rendez-vous jour par jour.'),
        carnet: w('Carnet', 'Petit cahier de poche où l’on griffonne notes, listes et idées.'),
      },
      pairs: [
        p('tasse', 'bol', 'Vaisselle'),
        p('tasse', 'thermos', 'Vaisselle et contenants'),
        p('thermos', 'gourde', 'Objets à emporter'),
        p('gourde', 'glaciere', 'Pique-nique'),
        p('glaciere', 'frigo', 'Cuisine'),
        p('fourchette', 'baguettes', 'Arts de la table'),
        p('poele', 'wok', 'Ustensiles de cuisine'),
        p('bouilloire', 'cafetiere', 'Petit électroménager'),
        p('eponge', 'chiffon', 'Ménage'),

        p('brosse-a-dents', 'rasoir', 'Salle de bain'),
        p('rasoir', 'seche-cheveux', 'Salle de bain'),
        p('shampoing', 'gel-douche', 'Produits de toilette'),

        p('oreiller', 'coussin', 'Objets moelleux'),
        p('coussin', 'plaid', 'Déco du salon'),
        p('plaid', 'couette', 'Se tenir chaud'),
        p('chaise', 'tabouret', 'Mobilier'),
        p('chaise', 'fauteuil', 'Mobilier'),
        p('fauteuil', 'transat', 'Pour se détendre'),
        p('transat', 'hamac', 'Vacances au soleil'),
        p('lampe-de-poche', 'bougie', 'Éclairage'),
        p('ventilateur', 'eventail', 'En plein été'),
        p('eventail', 'parasol', 'Vacances'),
        p('parasol', 'parapluie', 'Accessoires de sortie'),

        p('telecommande', 'manette', 'Dans le salon'),
        p('smartphone', 'tablette', 'Appareils numériques'),
        p('tablette', 'ordinateur', 'Appareils numériques'),
        p('ecouteurs', 'enceinte', 'Écouter de la musique'),

        p('montre', 'bracelet', 'Accessoires'),
        p('lunettes', 'jumelles', 'Accessoires'),
        p('cle', 'badge', 'Dans la poche'),
        p('sac-a-dos', 'valise', 'Bagages'),
        p('sac-a-dos', 'cartable', 'Bagages'),

        p('stylo', 'feutre', 'Trousse d’écolier'),
        p('feutre', 'crayon', 'Trousse d’écolier'),
        p('agrafeuse', 'trombone', 'Fournitures de bureau'),
        p('agrafeuse', 'scotch', 'Fournitures de bureau'),
        p('scotch', 'colle', 'Travaux manuels'),
        p('ciseaux', 'cutter', 'Fournitures et outils'),
        p('cutter', 'tournevis', 'Boîte à outils'),
        p('tournevis', 'perceuse', 'Bricolage'),
        p('livre', 'magazine', 'Lecture'),
        p('livre', 'carnet', 'Papeterie'),
        p('agenda', 'carnet', 'Papeterie'),
      ],
    }),
  ],
});
