import { definePack, pair } from './types';

export default definePack({
  id: 'objets',
  name: 'Objets du quotidien',
  description: "Ce qui traîne sur la table, dans le sac ou au fond d'un tiroir.",
  icon: 'lamp',
  pairs: [
    pair(
      'Vaisselle pour boire',
      ['Tasse', 'Petit récipient à anse pour les boissons chaudes.'],
      ['Verre', 'Récipient transparent sans anse pour l’eau ou les boissons froides.'],
    ),
    pair(
      'Éclairage d’intérieur',
      ['Lampe', 'Appareil électrique à ampoule qui éclaire une pièce ou un bureau.'],
      ['Bougie', 'Bâton de cire muni d’une mèche que l’on allume pour éclairer.'],
    ),
    pair(
      'Couverts de table',
      ['Fourchette', 'Couvert à dents qui sert à piquer les aliments.'],
      ['Cuillère', 'Couvert au creux arrondi pour manger la soupe ou un yaourt.'],
    ),
    pair(
      'Instruments d’écriture',
      ['Stylo', 'Instrument à encre, souvent à bille, pour écrire sur le papier.'],
      ['Crayon', 'Baguette de bois à mine de graphite, qu’on taille et dont le trait s’efface.'],
    ),
    pair('Salle de bain',
      ['Brosse à dents', 'Petit manche muni de poils qu’on frotte sur les dents avec du dentifrice.'],
      ['Fil dentaire', 'Mince brin qu’on glisse entre chaque dent pour déloger les restes.'],
    ),
    pair(
      'Objets moelleux de la maison',
      ['Oreiller', 'Rembourrage sur lequel on pose la tête pour dormir dans un lit.'],
      ['Coussin', 'Petit rembourrage décoratif posé sur un canapé ou une chaise.'],
    ),
    pair(
      'Linge de lit',
      ['Couette', 'Épaisse enveloppe garnie de plumes ou de fibres pour se couvrir au lit.'],
      ['Drap', 'Grande pièce de tissu fin qui couvre le matelas ou le dormeur.'],
    ),
    pair(
      'Appareils numériques portables',
      ['Smartphone', 'Téléphone mobile à écran tactile, avec applications et accès à Internet.'],
      ['Tablette', 'Appareil plat à grand écran tactile pour lire, regarder ou dessiner.'],
    ),
    pair(
      'Fermeture et sécurité',
      ['Clé', 'Petite pièce métallique dentée qu’on tourne dans une serrure.'],
      ['Cadenas', 'Serrure portative à anse métallique qu’on accroche pour verrouiller.'],
    ),
    pair('Accessoires de sortie',
      ['Parapluie', 'Toile tendue sur une armature pliable, tenue au-dessus de la tête.'],
      ['Imperméable', 'Manteau léger en tissu étanche qu’on enfile quand il pleut.'],
    ),
    pair(
      'Mesure du temps',
      ['Montre', 'Petit cadran qu’on porte au poignet pour lire l’heure.'],
      ['Réveil', 'Horloge de chevet qui sonne à l’heure choisie pour tirer du sommeil.'],
    ),
    pair('Accessoires du quotidien',
      ['Lunettes', 'Deux verres correcteurs fixés sur une monture posée sur le nez.'],
      ['Lentilles', 'Fines coques transparentes posées sur l’œil pour corriger la vue.'],
    ),
    pair(
      'Transporter ses affaires',
      ['Sac à dos', 'Bagage à deux bretelles porté sur les épaules, prisé en randonnée.'],
      ['Cartable', 'Bagage rigide d’écolier pour transporter livres et cahiers.'],
    ),
    pair(
      'Instruments tranchants',
      ['Ciseaux', 'Deux lames articulées qu’on actionne avec les doigts pour découper.'],
      ['Cutter', 'Lame rétractable et sécable glissée dans un manche, pour trancher le carton.'],
    ),
    pair(
      'Produits de toilette',
      ['Savon', 'Pain solide qui mousse au contact de l’eau pour se laver.'],
      ['Gel douche', 'Produit liquide moussant, vendu en flacon, pour se laver le corps.'],
    ),
    pair('Objets du salon',
      ['Télécommande', 'Petit boîtier à boutons pour changer de chaîne ou régler le volume.'],
      ['Manette', 'Accessoire tenu à deux mains, avec boutons et joysticks, pour jouer sur console.'],
    ),
    pair(
      'Sièges individuels',
      ['Chaise', 'Siège à quatre pieds muni d’un dossier, pour une personne.'],
      ['Tabouret', 'Petit siège sans dossier ni bras, parfois haut comme au comptoir d’un bar.'],
    ),
    pair(
      'Mobilier de salon',
      ['Canapé', 'Long siège rembourré où plusieurs personnes s’assoient côte à côte.'],
      ['Fauteuil', 'Siège rembourré à dossier et accoudoirs pour une seule personne.'],
    ),
    pair(
      'Habillage des fenêtres',
      ['Rideau', 'Pièce de tissu suspendue à une tringle devant une fenêtre.'],
      ['Store', 'Toile ou lamelles qui s’enroulent ou se replient pour occulter une fenêtre.'],
    ),
    pair(
      'Ustensiles de cuisson',
      ['Casserole', 'Récipient à bords hauts et à manche pour chauffer l’eau, le lait ou une sauce.'],
      ['Poêle', 'Ustensile plat à bords bas et à long manche pour saisir ou frire.'],
    ),
    pair('Électroménager',
      ['Four', 'Enceinte chauffée pour cuire gâteaux, rôtis et gratins.'],
      ['Micro-ondes', 'Appareil qui réchauffe vite les aliments grâce à des ondes électromagnétiques.'],
    ),
    pair('Électroménager',
      ['Frigo', 'Appareil qui garde les aliments au frais, à environ 4 °C.'],
      ['Congélateur', 'Appareil qui conserve les aliments à environ −18 °C pendant des mois.'],
    ),
    pair(
      'Ménage des sols',
      ['Aspirateur', 'Appareil électrique qui avale poussières et miettes par un tuyau.'],
      ['Balai', 'Long manche muni d’une brosse pour pousser la poussière au sol.'],
    ),
    pair(
      'Accessoires de ménage',
      ['Éponge', 'Bloc souple et absorbant, souvent doté d’une face grattante, pour la vaisselle.'],
      ['Chiffon', 'Morceau d’étoffe qui sert à essuyer ou à dépoussiérer.'],
    ),
    pair(
      'Écrans de la maison',
      ['Ordinateur', 'Machine à clavier qui traite des données, pour travailler ou naviguer.'],
      ['Télévision', 'Appareil pour regarder les chaînes, les émissions et les films diffusés.'],
    ),
    pair('Accessoires high-tech',
      ['Écouteurs', 'Petits haut-parleurs qu’on insère dans les oreilles.'],
      ['Casque', 'Deux haut-parleurs reliés par un arceau qui passe sur la tête.'],
    ),
    pair('Accessoires high-tech',
      ['Chargeur', 'Adaptateur branché sur le secteur pour recharger un téléphone.'],
      ['Batterie externe', 'Réserve d’énergie portable pour recharger un téléphone loin d’une prise.'],
    ),
    pair(
      'Maroquinerie de poche',
      ['Porte-monnaie', 'Petite pochette qui se ferme, surtout pour garder les pièces.'],
      ['Portefeuille', 'Étui plat qui se plie, pour ranger billets et cartes.'],
    ),
    pair(
      'Contenants pour boissons',
      ['Bouteille', 'Récipient à goulot étroit, en verre ou en plastique, pour les liquides.'],
      ['Gourde', 'Flacon réutilisable qu’on emporte en randonnée ou au sport pour boire.'],
    ),
    pair(
      'Vaisselle de table',
      ['Assiette', 'Pièce de vaisselle plate et ronde dans laquelle on sert un plat.'],
      ['Bol', 'Récipient rond et profond, sans anse, pour les céréales ou la soupe.'],
    ),
    pair('Fournitures de bureau',
      ['Agrafeuse', 'Appareil de bureau qui fixe des feuilles ensemble avec des agrafes.'],
      ['Trombone', 'Petit fil de métal replié en boucles qui pince quelques feuilles.'],
    ),
    pair('Fournitures scolaires',
      ['Gomme', 'Petit bloc de caoutchouc qui efface les traits de crayon.'],
      ['Correcteur', 'Liquide ou ruban blanc qui masque les fautes d’encre.'],
    ),
    pair('Dans la chambre',
      ['Cintre', 'Support en forme d’épaules sur lequel on suspend un habit dans l’armoire.'],
      ['Porte-manteau', 'Support mural ou sur pied, muni de patères pour accrocher les habits.'],
    ),
    pair(
      'Confort thermique',
      ['Radiateur', 'Appareil qui diffuse de la chaleur dans une pièce.'],
      ['Ventilateur', 'Appareil à pales tournantes qui brasse l’air pour rafraîchir.'],
    ),
    pair(
      'Outils de bricolage',
      ['Marteau', 'Outil à tête métallique lourde pour enfoncer des clous.'],
      ['Tournevis', 'Outil à tige et à manche pour serrer ou desserrer des vis.'],
    ),
    pair('Petits objets utiles',
      ['Briquet', 'Petit appareil à gaz qui fait jaillir une flamme d’un coup de pouce.'],
      ['Allumettes', 'Petits bâtonnets à tête inflammable qu’on frotte sur un grattoir.'],
    ),
    pair(
      'Courrier papier',
      ['Enveloppe', 'Pochette de papier fermée dans laquelle on glisse une lettre.'],
      ['Carte postale', 'Carton illustré d’un paysage, souvent envoyé depuis un lieu de vacances.'],
    ),
    pair(
      'Lecture imprimée',
      ['Livre', 'Ouvrage relié de nombreuses pages : roman, essai ou bande dessinée.'],
      ['Magazine', 'Publication périodique illustrée, souvent hebdomadaire ou mensuelle.'],
    ),
    pair(
      'Organisation du temps',
      ['Calendrier', 'Tableau des jours, semaines et mois de l’année, souvent accroché au mur.'],
      ['Agenda', 'Carnet où l’on note ses rendez-vous jour par jour.'],
    ),
  ],
});
