import { definePack } from './types';

export default definePack({
  id: 'rap-fr',
  name: 'Rap français',
  description: 'Punchlines, featurings et têtes d’affiche du rap made in France.',
  icon: 'audio-lines',
  pairs: [
    ['Ninho', 'Tiakola'],
    ['SCH', 'Niska'],
    ['Booba', 'Kaaris'],
    ['Nekfeu', 'Lomepal'],
    ['Jul', 'Naps'],
    ['Damso', 'Hamza'],
    ['Gazo', 'Freeze Corleone'],
    ['Soprano', 'Black M'],
    ['Gims', 'Dadju'],
    ['IAM', 'NTM'],
    ['MC Solaar', 'Oxmo Puccino'],
    ['Lacrim', 'Rohff'],
    ['La Fouine', 'Sinik'],
    ['Alonzo', 'Soso Maness'],
    ['Soolking', "L'Algérino"],
    ['Naza', 'KeBlack'],
    ['Vald', 'Lorenzo'],
    ['PLK', 'Hatik'],
    ['Werenoi', 'Leto'],
    ['Dinos', 'Josman'],
    ['Laylow', 'Alpha Wann'],
    ["Sexion d'Assaut", '1995'],
    ['113', "Mafia K'1 Fry"],
    ["Diam's", 'Keny Arkana'],
    ['Kery James', 'Youssoupha'],
    ['Timal', 'Maes'],
    ['Mister You', 'Niro'],
    ['Bigflo & Oli', 'PNL'],
    ['Koba LaD', 'Zola'],
    ["Heuss l'Enfoiré", 'Guy2Bezbar'],
    ['Kalash Criminel', 'Fianso'],
    ['Doc Gynéco', 'Passi'],
  ],
});
