import { definePack, p, universe, w } from './types';

export default definePack({
  id: 'rap-fr',
  name: 'Rap français',
  description: 'Punchlines, featurings et têtes d’affiche du rap made in France.',
  icon: 'audio-lines',
  universes: [
    universe({
      id: 'general',
      name: 'Rap français',
      precise: false,
      words: {
        // Têtes d'affiche actuelles
        ninho: w('Ninho', 'Rappeur francilien très certifié, auteur de la série M.I.L.S et de l’album Jefe.'),
        jul: w('Jul', 'Rappeur marseillais très prolifique, fondateur du label D’or et de platine.'),
        naps: w('Naps', 'Rappeur marseillais aux sons festifs, connu pour le tube La kiffance.'),
        heuss: w("Heuss l'Enfoiré", 'Rappeur au ton humoristique, connu pour les tubes Khapta et Moulaga.'),
        sch: w('SCH', 'Rappeur d’Aubagne à la voix grave, auteur de la saga d’albums JVLIVS.'),
        niska: w('Niska', 'Rappeur d’Évry, connu pour le tube Réseaux et l’album Commando.'),
        booba: w('Booba', 'Rappeur de Boulogne-Billancourt révélé avec Lunatic, fondateur du label 92i.'),
        damso: w('Damso', 'Rappeur belge au ton sombre, auteur des albums Ipséité et Lithopédion.'),
        hamza: w('Hamza', 'Rappeur et chanteur bruxellois aux sonorités RnB, surnommé le Sauce God.'),
        tiakola: w('Tiakola', 'Chanteur et rappeur de La Courneuve révélé avec 4Keus, auteur de l’album Mélo.'),
        werenoi: w('Werenoi', 'Rappeur aux ventes record dans les années 2020, auteur des albums Carré et Pyramide.'),
        leto: w('Leto', 'Rappeur du 17e arrondissement de Paris, auteur des mixtapes Trap$tar.'),
        plk: w('PLK', 'Rappeur d’origine polonaise, membre de Panama Bende, auteur de l’album Polak.'),
        gazo: w('Gazo', 'Figure de la drill française, auteur des mixtapes Drill FR et de l’album KMT.'),
        freeze: w('Freeze Corleone', 'Rappeur du collectif 667 au flow monocorde, auteur de l’album LMF.'),

        // Rap de rue et hardcore
        kaaris: w('Kaaris', 'Rappeur de Sevran au style brutal, auteur de l’album Or Noir et du tube Tchoin.'),
        lacrim: w('Lacrim', 'Rappeur du Val-de-Marne, auteur de la série R.I.P.R.O. et de l’album Corleone.'),
        kalash: w('Kalash Criminel', 'Rappeur de Sevran longtemps apparu cagoulé, auteur de La Fosse aux lions.'),
        rohff: w('Rohff', 'Rappeur vétéran de Vitry-sur-Seine, auteur de l’album La Fierté des nôtres.'),
        lafouine: w('La Fouine', 'Rappeur de Trappes, auteur des tubes Ma meilleure et Du ferme.'),
        sinik: w('Sinik', 'Rappeur des Ulis, en Essonne, auteur de l’album Sang froid.'),

        // Plumes et styles singuliers
        nekfeu: w('Nekfeu', 'Rappeur parisien à la plume travaillée, auteur des albums Feu et Cyborg.'),
        lomepal: w('Lomepal', 'Rappeur parisien et ancien skateur, auteur des albums Flip et Jeannine.'),
        orelsan: w('Orelsan', 'Rappeur normand, auteur des albums Le Chant des sirènes et Civilisation.'),
        vald: w('Vald', 'Rappeur d’Aulnay-sous-Bois au style décalé, auteur de l’album Xeu.'),
        lorenzo: w('Lorenzo', 'Rappeur humoristique au personnage outrancier, autoproclamé Empereur du sale.'),
        dinos: w('Dinos', 'Rappeur de La Courneuve à la plume mélancolique, auteur de l’album Taciturne.'),
        josman: w('Josman', 'Rappeur originaire de Vierzon, auteur des albums J.O.$ et Split.'),
        laylow: w('Laylow', 'Rappeur toulousain à l’univers futuriste, auteur de l’album Trinity.'),
        alphawann: w('Alpha Wann', 'Rappeur très technique, fondateur du label Don Dada et auteur de UMLA.'),
        solaar: w('MC Solaar', 'Rappeur aux jeux de mots raffinés, auteur de Bouge de là et Caroline.'),
        oxmo: w('Oxmo Puccino', 'Rappeur poète à la voix grave, surnommé le Black Jacques Brel.'),

        // Rap engagé
        diams: w("Diam's", 'Rappeuse phare des années 2000, autrice de La Boulette et Dans ma bulle.'),
        kenyarkana: w('Keny Arkana', 'Rappeuse marseillaise engagée, autrice du titre La Rage.'),
        kery: w('Kery James', 'Rappeur engagé, auteur de Lettre à la République et Banlieusards.'),
        youssoupha: w('Youssoupha', 'Rappeur à texte d’origine congolaise, surnommé le Lyriciste bantou.'),

        // Groupes
        iam: w('IAM', 'Groupe marseillais d’Akhenaton et Shurik’n, auteur de L’École du micro d’argent.'),
        ntm: w('NTM', 'Duo de Seine-Saint-Denis formé par JoeyStarr et Kool Shen.'),
        sexion: w("Sexion d'Assaut", 'Collectif parisien de rap, auteur de l’album L’École des points vitaux.'),
        pnl: w('PNL', 'Duo de frères de l’Essonne au rap planant, auteur de l’album Dans la légende.'),
        bigflo: w('Bigflo & Oli', 'Duo de frères toulousains au rap positif, auteur du tube Dommage.'),

        // Rap pop, marseillais et festif
        soprano: w('Soprano', 'Rappeur marseillais révélé avec Psy 4 de la Rime, devenu coach de The Voice Kids.'),
        blackm: w('Black M', 'Chanteur et rappeur révélé avec Sexion d’Assaut, connu pour le tube Sur ma route.'),
        gims: w('Gims', 'Chanteur aux lunettes noires révélé avec Sexion d’Assaut, connu pour le tube Bella.'),
        dadju: w('Dadju', 'Chanteur de RnB français, connu pour les titres Reine et Jaloux.'),
        keblack: w('KeBlack', 'Chanteur aux mélodies afro-pop, révélé par le tube Bazardée.'),
        naza: w('Naza', 'Rappeur et chanteur aux sons festifs, connu pour le tube Joli bébé.'),
        alonzo: w('Alonzo', 'Rappeur marseillais révélé au sein du groupe Psy 4 de la Rime.'),
        soso: w('Soso Maness', 'Rappeur marseillais connu pour le tube Petrouchka.'),
        soolking: w('Soolking', 'Chanteur et rappeur algérien aux influences raï, connu pour Dalida et Suavemente.'),
        lalgerino: w("L'Algérino", 'Rappeur marseillais aux refrains festifs, connu pour le tube Les Menottes.'),

        // Culture et vocabulaire du rap
        drill: w('Drill', 'Courant du rap né à Chicago, aux instrumentales sombres et menaçantes.'),
        trap: w('Trap', 'Courant du rap né dans le sud des États-Unis, aux charleys rapides et basses lourdes.'),
        boombap: w('Boom bap', 'Style de rap aux rythmes de batterie secs, emblématique des années 90.'),
        freestyle: w('Freestyle', 'Couplet rappé improvisé ou hors album, pour montrer sa technique au micro.'),
        battle: w('Battle', 'Affrontement de rappeurs face à face, tour par tour, devant un public.'),
        clash: w('Clash', 'Morceau ou échange dans lequel un rappeur s’en prend à un autre artiste.'),
        punchline: w('Punchline', 'Phrase choc ou jeu de mots marquant, faite pour frapper les esprits.'),
        gimmick: w('Gimmick', 'Courte expression signature qu’un artiste glisse souvent dans ses morceaux.'),
        mixtape: w('Mixtape', 'Projet au format libre, souvent sorti entre deux albums officiels.'),
        ep: w('EP', 'Disque court de quelques titres, entre le single et l’album.'),
        disqueor: w("Disque d'or", 'Certification d’un album en France, atteinte à 50 000 équivalents-ventes.'),
        disqueplatine: w('Disque de platine', 'Certification d’un album en France, atteinte à 100 000 équivalents-ventes.'),
        featuring: w('Featuring', 'Participation d’un artiste invité sur le morceau d’un autre.'),
        remix: w('Remix', 'Nouvelle version d’un morceau, retravaillée sur une autre production.'),
      },
      pairs: [
        p('ninho', 'jul', 'Rappeurs à succès'),
        p('ninho', 'werenoi', 'Gros vendeurs du rap'),
        p('jul', 'naps', 'Scène rap du Sud'),
        p('naps', 'heuss', 'Rap festif'),
        p('sch', 'niska', 'Rap populaire des années 2010'),
        p('sch', 'booba', 'Têtes d’affiche du rap'),
        p('booba', 'damso', 'Poids lourds du rap'),
        p('damso', 'hamza', 'Rap francophone'),
        p('hamza', 'tiakola', 'Rap mélodique'),
        p('plk', 'leto', 'Rap parisien actuel'),
        p('leto', 'werenoi', 'Rap de rue des années 2020'),
        p('gazo', 'freeze', 'Nouvelle école du rap'),

        p('kaaris', 'lacrim', 'Rap hardcore'),
        p('kaaris', 'kalash', 'Rap de banlieue parisienne'),
        p('lacrim', 'rohff', 'Rap de rue francilien'),
        p('rohff', 'lafouine', 'Rap des années 2000'),
        p('lafouine', 'sinik', 'Tubes rap des années 2000'),

        p('nekfeu', 'lomepal', 'Rap parisien à textes'),
        p('nekfeu', 'orelsan', 'Plumes du rap'),
        p('orelsan', 'vald', 'Rap à l’humour décalé'),
        p('orelsan', 'bigflo', 'Rap grand public'),
        p('vald', 'lorenzo', 'Rap décalé et absurde'),
        p('dinos', 'josman', 'Rap introspectif'),
        p('laylow', 'alphawann', 'Rap technique et soigné'),
        p('solaar', 'oxmo', 'Poètes du rap'),

        p('diams', 'kenyarkana', 'Rap engagé des années 2000'),
        p('kenyarkana', 'kery', 'Rap conscient'),
        p('kery', 'youssoupha', 'Rap à message'),

        p('iam', 'sexion', 'Groupes de rap cultes'),
        p('ntm', 'pnl', 'Groupes de rap marquants'),
        p('pnl', 'bigflo', 'Groupes des années 2010'),

        p('soprano', 'blackm', 'Rap pop grand public'),
        p('soprano', 'gims', 'Stars de la pop urbaine'),
        p('dadju', 'keblack', 'Voix de la pop urbaine'),
        p('keblack', 'naza', 'Sons afro festifs'),
        p('alonzo', 'soso', 'Scène marseillaise'),
        p('soolking', 'lalgerino', 'Rap aux influences maghrébines'),

        p('drill', 'trap', 'Styles de musique urbaine'),
        p('trap', 'boombap', 'Courants musicaux'),
        p('freestyle', 'battle', 'Culture hip-hop'),
        p('battle', 'clash', 'Joutes verbales'),
        p('punchline', 'gimmick', 'Écriture d’un morceau'),
        p('mixtape', 'ep', 'Formats de sortie'),
        p('disqueor', 'disqueplatine', 'Distinctions musicales'),
        p('featuring', 'remix', 'Vocabulaire du studio'),
      ],
    }),
  ],
});
