import { definePack } from './types';

export default definePack({
  id: 'voyage',
  name: 'Voyage & Lieux',
  description: "Capitales, paysages de rêve et tout ce qu'il faut pour partir.",
  icon: 'plane',
  pairs: [
    ['Paris', 'Rome'],
    ['Plage', 'Piscine'],
    ['Londres', 'Berlin'],
    ['New York', 'Los Angeles'],
    ['Tour Eiffel', 'Statue de la Liberté'],
    ['Montagne', 'Volcan'],
    ['Forêt', 'Jungle'],
    ['Désert', 'Savane'],
    ['Avion', 'Hélicoptère'],
    ['Train', 'Métro'],
    ['Paquebot', 'Ferry'],
    ['Hôtel', 'Gîte'],
    ['Tente', 'Camping-car'],
    ['Aéroport', 'Gare'],
    ['Musée', 'Bibliothèque'],
    ['Espagne', 'Portugal'],
    ['Italie', 'Grèce'],
    ['Japon', 'Corée du Sud'],
    ['Maroc', 'Tunisie'],
    ['Brésil', 'Argentine'],
    ['Suisse', 'Autriche'],
    ['Égypte', 'Mexique'],
    ['Venise', 'Amsterdam'],
    ['Dubaï', 'Las Vegas'],
    ['Maldives', 'Seychelles'],
    ['Lac', 'Rivière'],
    ['Cascade', 'Fontaine'],
    ['Grotte', 'Tunnel'],
    ['Chalet', 'Refuge'],
    ['Passeport', "Carte d'identité"],
    ['Valise', 'Sac de voyage'],
    ['Mont-Saint-Michel', 'Carcassonne'],
    ['Disneyland', 'Parc Astérix'],
    ['Zoo', 'Aquarium'],
    ['Croisière', 'Road trip'],
    ['Bretagne', 'Normandie'],
    ['Corse', 'Sardaigne'],
    ['Colisée', 'Acropole'],
  ],
});
