import { definePack, pair } from './types';

export default definePack({
  id: 'voyage',
  name: 'Voyage & Lieux',
  description: "Capitales, paysages de rêve et tout ce qu'il faut pour partir.",
  icon: 'plane',
  pairs: [
    pair(
      'Capitales européennes',
      ['Paris', 'Capitale de la France, traversée par la Seine.'],
      ['Rome', 'Capitale de l’Italie, surnommée la Ville éternelle.'],
    ),
    pair(
      'Lieux de baignade',
      ['Plage', 'Étendue de sable ou de galets au bord de la mer.'],
      ['Piscine', 'Bassin artificiel rempli d’eau, souvent chlorée, pour nager.'],
    ),
    pair(
      'Capitales européennes',
      ['Londres', 'Capitale du Royaume-Uni, traversée par la Tamise.'],
      ['Berlin', 'Capitale de l’Allemagne, divisée par un mur de 1961 à 1989.'],
    ),
    pair(
      'Métropoles américaines',
      ['New York', 'Plus grande ville des États-Unis, célèbre pour Manhattan et Times Square.'],
      ['Los Angeles', 'Grande ville de Californie qui abrite Hollywood, capitale du cinéma.'],
    ),
    pair(
      'Monuments emblématiques',
      ['Tour Eiffel', 'Monument de fer de 330 m bâti à Paris pour l’Exposition universelle de 1889.'],
      ['Statue de la Liberté', 'Colosse brandissant une torche à l’entrée du port de New York depuis 1886.'],
    ),
    pair(
      'Reliefs terrestres',
      ['Montagne', 'Relief très élevé aux pentes raides, parfois enneigé au sommet.'],
      ['Volcan', 'Relief d’où peuvent jaillir lave, cendres et gaz venus des profondeurs.'],
    ),
    pair(
      'Milieux naturels boisés',
      ['Forêt', 'Vaste étendue couverte d’arbres, de sous-bois et de sentiers.'],
      ['Jungle', 'Végétation tropicale dense et humide, riche en lianes et en animaux sauvages.'],
    ),
    pair(
      'Grands espaces sauvages',
      ['Désert', 'Région très sèche où il pleut rarement, souvent faite de sable ou de roche.'],
      ['Savane', 'Vaste plaine herbeuse parsemée d’arbres, typique de l’Afrique tropicale.'],
    ),
    pair('Moyens de transport',
      ['Avion', 'Appareil à ailes fixes qui décolle et atterrit sur une piste.'],
      ['Hélicoptère', 'Appareil volant à rotor qui décolle à la verticale et fait du surplace.'],
    ),
    pair('Moyens de transport',
      ['Train', 'Convoi de wagons sur rails qui relie les villes entre elles.'],
      ['Métro', 'Réseau ferré urbain, souvent souterrain, qui dessert une grande ville.'],
    ),
    pair('Moyens de transport',
      ['Paquebot', 'Grand navire de luxe transportant des passagers, comme le Titanic.'],
      ['Ferry', 'Navire qui fait la navette entre deux ports avec passagers et véhicules.'],
    ),
    pair(
      'Hébergement de vacances',
      ['Hôtel', 'Établissement qui loue des chambres à la nuit, avec accueil et service.'],
      ['Gîte', 'Logement meublé à la campagne, loué pour les vacances.'],
    ),
    pair(
      'Hébergements nomades',
      ['Tente', 'Abri de toile monté sur des arceaux et fixé au sol par des piquets.'],
      ['Camping-car', 'Véhicule aménagé avec couchettes et coin cuisine pour voyager.'],
    ),
    pair(
      'Lieux d’embarquement',
      ['Aéroport', 'Lieu équipé de pistes et de terminaux d’où partent les vols.'],
      ['Gare', 'Bâtiment où les voyageurs montent et descendent des trains.'],
    ),
    pair(
      'Lieux culturels',
      ['Musée', 'Lieu qui conserve et expose des œuvres d’art ou des collections.'],
      ['Bibliothèque', 'Lieu où l’on consulte ou emprunte des livres.'],
    ),
    pair(
      'Pays d’Europe du Sud',
      ['Espagne', 'Pays dont la capitale est Madrid, célèbre pour le flamenco et la paella.'],
      ['Portugal', 'Pays dont la capitale est Lisbonne, célèbre pour le fado et le pastel de nata.'],
    ),
    pair(
      'Pays méditerranéens',
      ['Italie', 'Pays en forme de botte dont la capitale est Rome.'],
      ['Grèce', 'Pays aux nombreuses îles dont la capitale est Athènes.'],
    ),
    pair(
      'Pays d’Asie de l’Est',
      ['Japon', 'Archipel d’Asie dont la capitale est Tokyo, pays des sushis et des mangas.'],
      ['Corée du Sud', 'Pays d’Asie dont la capitale est Séoul, patrie de la K-pop.'],
    ),
    pair('Pays d’Afrique',
      ['Maroc', 'Pays d’Afrique du Nord dont la capitale est Rabat, célèbre pour Marrakech.'],
      ['Tunisie', 'Pays d’Afrique du Nord dont la capitale est Tunis, célèbre pour l’île de Djerba.'],
    ),
    pair(
      'Pays d’Amérique du Sud',
      ['Brésil', 'Plus grand pays d’Amérique du Sud, célèbre pour le carnaval de Rio.'],
      ['Argentine', 'Pays d’Amérique du Sud dont la capitale est Buenos Aires, terre du tango.'],
    ),
    pair('Pays européens',
      ['Suisse', 'Pays alpin neutre aux quatre langues nationales, réputé pour son chocolat.'],
      ['Autriche', 'Pays alpin germanophone dont la capitale est Vienne, patrie de Mozart.'],
    ),
    pair(
      'Pays de civilisations anciennes',
      ['Égypte', 'Pays d’Afrique traversé par le Nil, célèbre pour les pharaons de l’Antiquité.'],
      ['Mexique', 'Pays dont la capitale est Mexico, héritier des civilisations aztèque et maya.'],
    ),
    pair(
      'Villes européennes touristiques',
      ['Venise', 'Ville italienne bâtie sur une lagune, où l’on circule en gondole.'],
      ['Amsterdam', 'Capitale des Pays-Bas, connue pour ses canaux et ses vélos.'],
    ),
    pair(
      'Villes de la démesure',
      ['Dubaï', 'Émirat du golfe Persique où se dresse la tour Burj Khalifa.'],
      ['Las Vegas', 'Ville du Nevada célèbre pour ses casinos et ses spectacles.'],
    ),
    pair(
      'Îles paradisiaques',
      ['Maldives', 'Archipel d’atolls de l’océan Indien, parmi les pays les plus plats du monde.'],
      ['Seychelles', 'Archipel de l’océan Indien au large de l’Afrique, réputé pour ses rochers de granit.'],
    ),
    pair(
      'Milieux d’eau douce',
      ['Lac', 'Étendue d’eau douce entourée de terres, comme celui d’Annecy.'],
      ['Rivière', 'Cours d’eau naturel qui se jette dans un autre cours d’eau.'],
    ),
    pair(
      'Eau en mouvement',
      ['Cascade', 'Chute d’eau naturelle qui dévale des rochers.'],
      ['Fontaine', 'Ouvrage d’où l’eau jaillit ou s’écoule, souvent au milieu d’une place.'],
    ),
    pair(
      'Lieux sous terre',
      ['Grotte', 'Cavité naturelle creusée dans la roche, parfois ornée de stalactites.'],
      ['Tunnel', 'Galerie creusée pour faire passer une route ou une voie ferrée.'],
    ),
    pair(
      'Hébergement en altitude',
      ['Chalet', 'Maison en bois typique des Alpes, au toit largement débordant.'],
      ['Refuge', 'Abri de haute montagne où les randonneurs peuvent dormir et manger.'],
    ),
    pair('Préparatifs de voyage',
      ['Passeport', 'Livret officiel où l’on appose visas et tampons pour voyager à l’étranger.'],
      ["Carte d'identité", 'Petit document officiel avec photo qui prouve qui l’on est.'],
    ),
    pair('Avant le grand départ',
      ['Valise', 'Bagage rigide ou souple à poignée, souvent muni de roulettes.'],
      ['Sac de voyage', 'Bagage souple en tissu, porté à la main ou à l’épaule.'],
    ),
    pair(
      'Sites historiques français',
      ['Mont-Saint-Michel', 'Îlot rocheux coiffé d’une abbaye, cerné par les grandes marées d’une baie.'],
      ['Carcassonne', 'Cité médiévale fortifiée de l’Aude, entourée d’une double ligne de remparts.'],
    ),
    pair('Sorties en famille',
      ['Disneyland', 'Complexe de loisirs de Marne-la-Vallée où l’on croise Mickey et ses amis.'],
      ['Parc Astérix', 'Site de loisirs de l’Oise inspiré d’une bande dessinée sur les Gaulois.'],
    ),
    pair(
      'Sorties animalières',
      ['Zoo', 'Lieu où l’on observe des animaux sauvages dans des enclos.'],
      ['Aquarium', 'Lieu où l’on observe poissons et créatures marines derrière des vitres.'],
    ),
    pair(
      'Façons de voyager',
      ['Croisière', 'Voyage en bateau ponctué d’escales dans plusieurs ports.'],
      ['Road trip', 'Long voyage en voiture, étape après étape, au fil des routes.'],
    ),
    pair(
      'Régions françaises',
      ['Bretagne', 'Région de l’ouest de la France, terre de crêpes et de menhirs.'],
      ['Normandie', 'Région du nord-ouest de la France, terre du camembert et du Débarquement.'],
    ),
    pair(
      'Îles de Méditerranée',
      ['Corse', 'Île française de Méditerranée, surnommée l’île de Beauté.'],
      ['Sardaigne', 'Grande île italienne de Méditerranée, connue pour la Costa Smeralda.'],
    ),
    pair(
      'Monuments de l’Antiquité',
      ['Colisée', 'Amphithéâtre antique de Rome où s’affrontaient les gladiateurs.'],
      ['Acropole', 'Colline d’Athènes couronnée par le Parthénon et d’autres temples antiques.'],
    ),
  ],
});
